extension L10n {
    static let ru: [L10nKey: String] = [
        .apiCost: "Эквивалентная стоимость API",
        .apiCostSummaryRange: "Диапазон стоимости API",
        .apiCostSource: "Источник стоимости",
        .apiEquivalent: "Эквивалент API",
        .apiTokenPricing: "Цены на токены API",
        .appearance: "Оформление",
        .appearanceDark: "Тёмная",
        .appearanceLight: "Светлая",
        .appearanceSystem: "Системная",
        .auto: "Авто",
        .about: "О программе",
        .advanced: "Дополнительно",
        .account: "Аккаунт",
        .accounts: "Аккаунты",
        .accountsAdd: "Добавить аккаунт",
        .accountsAddAPIKey: "API Key",
        .accountsAddFile: "Импорт файлов",
        .accountsAddLocal: "Импорт локального auth.json",
        .accountsAddOAuth: "Войти через браузер",
        .accountsAddPaste: "Вставить токен / JSON",
        .accountsAPIKeyHint: "Вставьте ключ OpenAI API. У API-аккаунтов нет индикаторов квоты ChatGPT.",
        .accountsCurrent: "Текущий",
        .accountsDelete: "Удалить",
        .accountsDeleteConfirmMessage: "Удалить этот аккаунт из CodexRunway? Официальный вход Codex не изменится, если это не текущий аккаунт.",
        .accountsDeleteConfirmTitle: "Удалить аккаунт?",
        .accountsDeselectAll: "Снять выделение",
        .accountsEmpty: "Управляемых аккаунтов пока нет. Импортируйте локальный auth.json или добавьте другой аккаунт.",
        .accountsExport: "Экспорт",
        .accountsExportEmpty: "Нет аккаунтов для экспорта.",
        .accountsExportFailed: "Ошибка экспорта",
        .accountsExportHint: "Выберите аккаунты текущей платформы для экспорта. Файл можно импортировать в CodexRunway на другом Mac.",
        .accountsExportSucceeded: "Экспортировано аккаунтов: %d",
        .accountsExportTitle: "Экспорт аккаунтов",
        .accountsExportWarning: "Файл экспорта содержит учётные данные. Храните и передавайте его безопасно.",
        .accountsForceCurrent: "Принудительно сделать текущим входом",
        .accountsImportFailed: "Ошибка импорта",
        .accountsImportNoCredentials: "Учётные данные не найдены. Вставьте auth.json, refresh token или JSON ChatGPT /auth/session (accessToken).",
        .accountsImportPreviewHint: "Проверьте аккаунты из выбранных файлов. Снимите флажки с тех, которые не нужно импортировать.",
        .accountsImportPreviewTitle: "Импорт аккаунтов",
        .accountsImportProgress: "Импорт %d / %d",
        .accountsImportProviderNotice: "Импортировано в аккаунты %@",
        .accountsImportSelected: "Импортировать выбранные",
        .accountsImportSucceeded: "Импортировано аккаунтов: %d",
        .accountsImportWillAdd: "Будет добавлен",
        .accountsImportWillUpdate: "Будет обновлён",
        .accountsUserIdLabel: "ID пользователя:",
        .accountsWorkspaceIdLabel: "ID рабочей области:",
        .accountsWorkspaceNameLabel: "Рабочая область:",
        .accountsIsCurrentLogin: "Это текущий аккаунт входа Codex",
        .accountsMakeCurrent: "Использовать в Codex",
        .accountsMoveDown: "Вниз",
        .accountsMoveUp: "Вверх",
        .accountsNeedsReauth: "Нужна повторная авторизация",
        .accountsNote: "Заметка",
        .accountsOAuthCancelled: "Вход через браузер отменён.",
        .accountsOAuthFailed: "Ошибка входа через браузер",
        .accountsOAuthWaiting: "Завершите вход в браузере…",
        .accountsPasteFromClipboard: "Вставить из буфера",
        .accountsPasteHint: "Вставьте refresh token, ~/.codex/auth.json, JSON ChatGPT /api/auth/session или JSON-массив аккаунтов.",
        .accountsRefreshAll: "Обновить все квоты",
        .accountsReauthRequired: "Войдите снова",
        .accountsRestartCodexAfterSwitch: "Сразу перезапустить Codex после переключения",
        .accountsRestartCodexFailed: "Аккаунт переключён, но Codex не удалось перезапустить: %@",
        .accountsRestartCodexSucceeded: "Аккаунт переключён. Codex перезапущен.",
        .accountsSelectAll: "Выбрать все",
        .accountsSidebarTitle: "Аккаунты",
        .accountsSwitchConfirmTitle: "Переключить аккаунт?",
        .accountsSwitchConfirmMessage: "Заменить ~/.codex/auth.json на «%@», Codex применит это после перезапуска.",
        .accountsSwitchFailed: "Не удалось переключить аккаунт",
        .accountsSwitchInvalidCredential: "Учётные данные этого аккаунта недействительны или неполны, поэтому их нельзя использовать для входа в Codex.",
        .accountsSwitchMissingRefresh: "У этого аккаунта нет refresh_token. Пока access token действителен, переключение возможно; после истечения импортируйте сессию снова или войдите через браузер.",
        .accountsSwitchSessionExpired: "Access token этой сессии истёк, refresh_token отсутствует. Импортируйте снова из /auth/session или войдите через браузер.",
        .accountsSwitching: "Переключение аккаунта…",
        .accountsSwitchRealHint: "Переключение записывает выбранный аккаунт в ~/.codex/auth.json, чтобы Codex CLI и IDE его использовали.",
        .alias: "Псевдоним",
        .automaticallyCheckForUpdates: "Автоматически проверять обновления",
        .available: "Доступно",
        .availableResets: "доступных сбросов",
        .back: "Назад",
        .backup: "Резервная копия",
        .cachedInput: "Кэшированный ввод",
        .cachedInputTokens: "Кэшированные входные токены",
        .cancel: "Отмена",
        .calculate: "Рассчитать",
        .calculating: "Расчёт…",
        .codexFolder: "Открыть папку Codex",
        .controlPanel: "Панель управления",
        .calculatedAt: "Рассчитано",
        .costShare: "Доля стоимости",
        .costScanFailed: "Ошибка сканирования стоимости",
        .costScanPreparing: "Подготовка сканирования использования…",
        .costScanIndexing: "Индексация журналов сессий…",
        .costScanAggregating: "Агрегация использования…",
        .costScanFetchingOnline: "Загрузка онлайн-использования…",
        .costScanProgressFiles: "%d / %d файлов",
        .credit: "Кредит",
        .creditsBalance: "Баланс кредитов",
        .creditsUsed: "Использовано кредитов",
        .currentCycle: "Текущий цикл",
        .currentCycleAmount: "Сумма текущего цикла",
        .customRange: "Свой период",
        .customRangePrompt: "Выберите диапазон дат и нажмите «Рассчитать»",
        .cycleStarted: "Начало",
        .date: "Дата",
        .burnRate: "Скорость расхода",
        .duplicate: "дубликат",
        .duplicateIndexIDs: "Повторяющиеся ID индекса",
        .display: "Отображение",
        .displayAppearanceSection: "Оформление и строка меню",
        .mainPanelBackground: "Фон панели",
        .mainPanelBackgroundDescription: "Полупрозрачный фон показывает окна за панелью.",
        .mainPanelBackgroundOpaque: "Непрозрачный",
        .mainPanelBackgroundTranslucent: "Полупрозрачный",
        .endDate: "Дата окончания",
        .estimatedAPICost: "Оценка стоимости API",
        .expiresRemaining: "Остаток срока",
        .expiresAt: "Истекает",
        .expiryRisk: "Риск истечения",
        .expiringSoon: "Скоро истечёт",
        .exhaustsIn: "Исчерпается через",
        .error: "Ошибка",
        .exportStatusJSON: "Экспорт локального JSON статуса",
        .failed: "Ошибка",
        .checkForUpdates: "Проверить обновления",
        .fiveHourUsage: "5 часов",
        .general: "Основные",
        .grokAccountsAddFile: "Импорт файлов",
        .grokAccountsAddOAuth: "Войти в новый аккаунт Grok",
        .grokAccountsAddPaste: "Вставить токен / JSON",
        .grokAccountsCurrent: "Текущий аккаунт Grok",
        .grokAccountsDeleteConfirmMessage: "Удалить этот аккаунт из CodexRunway? Официальный вход Grok не изменится.",
        .grokAccountsDeleteConfirmTitle: "Удалить аккаунт Grok?",
        .grokAccountsEmpty: "Управляемых аккаунтов Grok пока нет. Войдите, импортируйте текущий вход Grok или вставьте учётные данные.",
        .grokAccountsImportNoCredentials: "Учётные данные не найдены. Вставьте ~/.grok/auth.json или объект учётных данных Grok (key/refresh_token плюс email, user_id или principal_id).",
        .grokAccountsImportOfficial: "Импорт текущего входа Grok",
        .grokAccountsMakeCurrent: "Использовать в Grok",
        .grokAccountsPasteHint: "Вставьте ~/.grok/auth.json, один объект OAuth/legacy-учётных данных Grok или JSON-массив аккаунтов. Учётные данные только с API-ключом не поддерживаются.",
        .grokAccountsRefreshAll: "Обновить все квоты Grok",
        .grokAccountsRemove: "Удалить аккаунт Grok",
        .grokAccountsTitle: "Аккаунты Grok",
        .grokBillingParseFailed: "Grok вернул неподдерживаемый ответ биллинга. Обновите CLI или повторите позже.",
        .grokBillingPeriod: "Расчётный период",
        .grokBillingPeriodMonthly: "Месячная включённая квота",
        .grokBillingPeriodWeekly: "Недельная включённая квота",
        .grokCLIInstallHint: "Установите официальный Grok CLI и войдите через OAuth, чтобы видеть биллинг.",
        .grokCLIOpenInstallGuide: "Открыть руководство по установке Grok CLI",
        .grokCLITooOld: "Эта версия Grok CLI не поддерживает биллинг. Обновите CLI и повторите попытку.",
        .grokCLIUnavailable: "Grok CLI не установлен",
        .grokCurrentAccountCannotDelete: "Перед удалением текущего аккаунта переключитесь на другой аккаунт Grok.",
        .grokDataSource: "Источник данных",
        .grokExternalLoginChanged: "Вход Grok был изменён другим процессом. Состояние аккаунта синхронизировано с официальными учётными данными.",
        .grokImportFailed: "Не удалось импортировать текущий вход Grok",
        .grokImportSucceeded: "Текущий вход Grok импортирован",
        .grokIncludedQuota: "Включённая квота",
        .grokIncludedUSD: "Включённый кредит в USD",
        .grokLocalUsage: "Локальное использование токенов",
        .grokLocalUsageHint: "Из недавних сессий Grok CLI на этом Mac (использование turn_completed).",
        .grokLoginCancelled: "Вход в Grok отменён.",
        .grokLoginFailed: "Ошибка входа в Grok",
        .grokLoginWaiting: "Завершите вход в Grok в браузере (страница кода устройства откроется автоматически)…",
        .grokNoManagedOAuth: "Не найден управляемый OAuth или совместимый legacy-вход Grok.",
        .grokNoQuotaData: "Данные биллинга Grok пока недоступны.",
        .grokNotLoggedIn: "Вход в Grok не выполнен",
        .grokOnDemandLimit: "Лимит по требованию",
        .grokOnDemandUsage: "Использование по требованию",
        .grokPlan: "План Grok",
        .grokPrepaidBalance: "Предоплаченный баланс",
        .grokProductBuild: "Grok Build",
        .grokProductChat: "Grok Chat",
        .grokProductImagine: "Grok Imagine",
        .grokProductUsage: "Использование продуктов",
        .grokReauthenticationRequired: "Вход в Grok истёк. Войдите снова.",
        .grokRefreshFailed: "Не удалось обновить биллинг Grok",
        .grokRefreshCancelled: "Обновление биллинга Grok отменено.",
        .grokRefreshTimedOut: "Запрос биллинга Grok превысил время ожидания.",
        .grokRefreshing: "Обновление биллинга Grok…",
        .grokResetAt: "Сброс",
        .grokSessionsScanned: "Просканировано сессий: %d",
        .grokSourceCLI: "API биллинга Grok CLI",
        .grokSourceLocalSessions: "Локальные сессии Grok",
        .grokSwitchConfirmMessage: "Заменить официальный OAuth-вход Grok на «%@»? Гарантируется только для новых сессий Grok.",
        .grokSwitchConfirmTitle: "Переключить аккаунт Grok?",
        .grokSwitchFailed: "Не удалось переключить аккаунт Grok",
        .grokSwitchOnlyNewSessions: "Переключение аккаунта влияет только на новые сессии Grok.",
        .grokSwitchRunningMessage: "Один или несколько процессов Grok ещё запущены. Они могут записать предыдущий вход обратно после переключения. Продолжение гарантирует использование выбранного аккаунта только для новых сессий Grok.",
        .grokSwitchRunningTitle: "Grok запущен",
        .grokSwitching: "Переключение аккаунта Grok…",
        .grokUnifiedBilling: "Единый биллинг",
        .grokUpdatedAt: "Биллинг Grok обновлён",
        .hours: "ч",
        .modelBreakdown: "Разбивка по моделям",
        .modelSpecificQuotaUsageDescription: "Показывать отдельный прогресс квоты по моделям в строке меню и главной панели.",
        .noModelCostData: "Нет данных о стоимости моделей",
        .nonCachedInput: "Некэшированный ввод",
        .inputShort: "in",
        .inputCachedOutput: "Ввод / кэш / вывод",
        .inputTokens: "Входные токены",
        .invalidDateRange: "Неверный диапазон дат",
        .language: "Язык",
        .languageEnglish: "Английский",
        .languageSimplifiedChinese: "Упрощённый китайский",
        .lastReset: "Последний сброс",
        .lastUpdated: "Обновлено",
        .later: "позже",
        .left: "осталось",
        .minutes: "мин",
        .missing: "отсутствует",
        .missingFromIndex: "Нет в индексе",
        .nextResetIn: "Следующий сброс: ",
        .nextExpiry: "Следующее истечение",
        .needsAttention: "Требует внимания",
        .noExpiry: "без срока",
        .noAvailableResetCredits: "Нет кредитов сброса",
        .notLoggedIn: "Не выполнен вход",
        .authExpired: "Вход истёк. Войдите снова или переключитесь на аккаунт с действительным refresh_token.",
        .authFileInvalid: "Локальный auth.json недействителен или неполон. Восстановите рабочий аккаунт или войдите снова.",
        .noPreviousIndex: "нет предыдущего индекса",
        .notLoaded: "Не загружено",
        .notScanned: "Не просканировано",
        .ok: "ОК",
        .openControlPanel: "Открыть панель управления",
        .openDetailsWindow: "Открыть окно сведений",
        .orphan: "осиротевший",
        .orphanIndexRows: "Осиротевшие строки индекса",
        .outputTokens: "Выходные токены",
        .outputShort: "out",
        .openGithub: "Открыть GitHub",
        .tokenComposition: "Состав токенов",
        .feedbackIssue: "Отзыв",
        .historicalUsage: "Историческое использование",
        .privacy: "Токены остаются на этом Mac. Восстановление сессий переписывает локальный индекс только после создания резервной копии.",
        .plan: "План",
        .planAPI: "API",
        .planBusiness: "Business",
        .planEdu: "Edu",
        .planEnterprise: "Enterprise",
        .planFree: "Free",
        .planPlus: "Plus",
        .planPro5x: "Pro 5X",
        .planPro20x: "Pro 20X",
        .planTeam: "Team",
        .planUnknown: "Неизвестно",
        .plannedEntries: "Запланированные записи",
        .pricingVersion: "Версия прайса",
        .projectBreakdown: "Разбивка по проектам",
        .projectedAtReset: "Прогноз к сбросу",
        .projectedWeeklyTotal: "Прогноз недельного итога",
        .previousCycle: "Предыдущий цикл",
        .providerCodex: "Codex",
        .providerGrok: "Grok",
        .quota: "Квота",
        .quotaAlertBody: "%@ достиг уровня использования %@.",
        .quotaAlertTitle: "Оповещение о квоте Codex",
        .quotaAlertsDescription: "Оповещения при достижении 80%, 95% или 100% использования.",
        .quotaAlerts: "Оповещения о квоте",
        .quotaEstimate: "Оценка недельной квоты",
        .quotaEstimateCannotExtrapolate: "Недостаточно недельного использования для оценки",
        .quotaEstimateCredits: "Credits",
        .quotaEstimateCut: "Возможное снижение",
        .quotaEstimateHistory: "Прошлые оценки",
        .quotaEstimateIncreased: "Выше, чем в прошлый раз",
        .quotaEstimateInfo: "Квота оценивается по официальному проценту использования и дневным Credits. Неофициальный пересчёт 1000 Credits ≈ $40 отличается от справочной стоимости токенов в таблице. Дневная агрегация лишь приблизительно учитывает границы периода; оценка носит справочный характер.",
        .quotaEstimateMethodOfficial: "Автоокно",
        .quotaEstimateMethodRolling: "Последние 7 дней",
        .quotaEstimateMissingCredits: "Официальная статистика не содержит полных данных Credits; оценка квоты недоступна",
        .quotaEstimateNoUsage: "В этом периоде ещё нет использования; оценка квоты недоступна",
        .quotaEstimateShowingPreviousData: "Не удалось обновить; показаны ранее полученные данные",
        .quotaEstimateStatsThrough: "Статистика по %@",
        .quotaEstimateUnavailableWindow: "Нет периода квоты для оценки",
        .quotaEstimateZeroCreditsWithUsage: "Официальная статистика содержит использование токенов, но возвращает 0 Credits; оценка квоты недоступна",
        .quotaEstimateZeroPercent: "Использование составляет 0 %; оценка квоты пока недоступна",
        .quotaEstimateThisWeek: "Эта неделя",
        .quotaEstimateThisWeekUsed: "Использовано за неделю",
        .quotaEstimateUsedPercent: "Процент использования",
        .quotaEstimateWeekValue: "Недельная стоимость (оценка)",
        .quotaEstimateWeeklyAllowance: "Оценка недельной квоты",
        .quotaEstimateWindowMode: "Окно оценки",
        .quotaEstimateWindowOfficial: "Автоокно",
        .quotaEstimateWindowRolling: "Последние 7 календарных дней",
        .quotaEstimateVsLast: "к прошлой оценке",
        .quit: "Выйти",
        .rawAnalyticsCredits: "Сырые кредиты аналитики",
        .rateLimitResetDetectedAlertBody: "Только что обнаружен сброс квоты Codex на сегодня.",
        .rateLimitResetDetectedBankedAlertBody: "Сброс сохранён в банке для использования по запросу; текущая квота не обновляется автоматически.",
        .rateLimitResetDetectedGlobalAndBankedAlertBody: "Глобальный сброс завершён; отдельный сброс сохранён в банке для использования по запросу и сам по себе не обновляет текущую квоту.",
        .rateLimitResetDetectedAlertTitle: "Обнаружен сброс Codex",
        .rateLimitResetDetectedTypedAlertTitle: "Codex: подтверждено — %@",
        .rateLimitResetToday: "Сброс сегодня?",
        .rateLimitResetTodayAlerts: "Оповещения о сбросе сегодня",
        .rateLimitResetTodayAlertsDescription: "Уведомлять о только что обнаруженном сбросе и когда запланированный сброс через 1 час или 30 минут.",
        .rateLimitResetTodayAwaiting: "Сегодня нет завершённого или запланированного сброса",
        .rateLimitResetTodayBankedCompletedHint: "Сброс сохранён в банке для использования по запросу; текущая квота не обновлена",
        .rateLimitResetTodayBankedScheduledHint: "Пополнение банка сбросов запланировано на сегодня, но ещё не поступило",
        .rateLimitResetTodayCheckCost: "Стоимость проверки",
        .rateLimitResetTodayConfidence: "Уверенность",
        .rateLimitResetTodayDescription: "Публичный статус с www.codexrunway.com.",
        .rateLimitResetTodayEvidenceBankedReset: "Объявлен накопленный сброс; это не завершённый сброс.",
        .rateLimitResetTodayEvidenceBankedCompleted: "Подтверждено поступление сброса в банк для использования по запросу.",
        .rateLimitResetTodayEvidenceBankedPreview: "Из контекста выведено высоковероятное пополнение банка сбросов.",
        .rateLimitResetTodayEvidenceBankedScheduled: "Явно запланировано пополнение банка сбросов.",
        .rateLimitResetTodayEvidenceGlobalAndBankedCompleted: "Подтверждены глобальный сброс и пополнение банка сбросов.",
        .rateLimitResetTodayEvidenceGlobalAndBankedPreview: "Из контекста выведены высоковероятные глобальный сброс и пополнение банка.",
        .rateLimitResetTodayEvidenceGlobalAndBankedScheduled: "Явно запланированы глобальный сброс и пополнение банка сбросов.",
        .rateLimitResetTodayEvidenceLimitIncrease: "Объявлено повышение лимита квоты; это не сброс.",
        .rateLimitResetTodayEvidenceResetCompleted: "Объявлен явный сброс квоты Codex.",
        .rateLimitResetTodayEvidenceResetScheduled: "Запланирован явный сброс квоты Codex.",
        .rateLimitResetTodayEvidenceResetPreview: "По контексту выведен высоковероятный сброс квоты Codex.",
        .rateLimitResetTodayEvidenceManualCompletion: "Подтверждено без поста о завершении в X.",
        .rateLimitResetTodayEvidenceOperatorCompletion: "Подтверждено операторами; Tibo не публиковал в X.",
        .rateLimitResetTodayEvidenceOperatorScheduled: "Операторы подтвердили расписание; Tibo не публиковал в X.",
        .rateLimitResetTodayEvidenceUncertain: "Это не явный сигнал сброса.",
        .rateLimitResetTodayLastCheck: "Последняя проверка",
        .rateLimitResetTodayLastFetched: "Последнее обновление",
        .rateLimitResetTodayLocalDayHint: "Использует ваш локальный календарный день и меняется в полночь.",
        .rateLimitResetTodayLatestEvidence: "Последнее свидетельство",
        .rateLimitResetTodayNextScheduled: "Ожидаемый следующий сброс",
        .rateLimitResetTodayNextScheduledWithCountdown: "Ожидаемый следующий сброс: %@ (%@)",
        .rateLimitResetTodayNo: "Нет",
        .rateLimitResetTodayNoHint: "Сегодня нет завершённого или запланированного сброса",
        .rateLimitResetTodayNoHintUncertain: "Сегодня нет явного сигнала сброса",
        .rateLimitResetTodayNoHintUnconfirmedSchedule: "Запланированное время {type} прошло без подтверждения",
        .rateLimitResetTodayNoHintWithLast: "Сегодня нет завершённого или запланированного сброса. Последний {type} был {ago} назад",
        .rateLimitResetTodayNoHintWithNext: "Сегодня сброса нет · ожидаемый следующий сброс %@",
        .rateLimitResetTodayOpenSource: "Открыть страницу статуса",
        .rateLimitResetTodayOpenWebsite: "Смотреть статус и историю сброса на сайте CodexRunway",
        .rateLimitResetTodayOpenEvidence: "Открыть источник в X",
        .rateLimitResetTodayResetAgo: "Сброс %@ назад",
        .rateLimitResetTodayUntilReset: "%@ до сброса",
        .rateLimitResetTodayPlanAll: "Все планы",
        .rateLimitResetTodayPlanBusiness: "Business",
        .rateLimitResetTodayPlanEnterprise: "Enterprise",
        .rateLimitResetTodayPlanFree: "Free",
        .rateLimitResetTodayPlanPlus: "Plus",
        .rateLimitResetTodayPlanPro: "Pro",
        .rateLimitResetTodayPlanTeam: "Team",
        .rateLimitResetTodayPlanUnknown: "План не указан",
        .rateLimitResetTodayPlans: "Планы",
        .rateLimitResetTodayRefreshInterval: "Обновление статуса сброса",
        .rateLimitResetTodayReactionPlease: "Просим сброс",
        .rateLimitResetTodayReactionThank: "Спасибо",
        .rateLimitResetTodayReactionPleaseAria: "Просим сброс, сейчас %@",
        .rateLimitResetTodayReactionThankAria: "Спасибо за сброс, сейчас %@",
        .rateLimitResetTodayReactionLimitReached: "Дневной лимит нажатий исчерпан",
        .rateLimitResetTodaySeen: "Замечено",
        .rateLimitResetTodaySource: "Статус сброса CodexRunway",
        .rateLimitResetTodaySourceInfo: "CodexRunway публикует этот статус с размещённого монитора, который с помощью ИИ анализирует публичные объявления в X. Результаты ИИ могут быть неполными или неверными.",
        .rateLimitResetTodaySourceTitle: "Источник данных",
        .rateLimitResetTodayGlobalAndBankedCompletedHint: "Глобальная квота сброшена; ещё один сброс сохранён в банке для использования по запросу",
        .rateLimitResetTodayGlobalAndBankedScheduledHint: "Глобальный сброс и пополнение банка запланированы на сегодня, но ещё не произошли",
        .rateLimitResetTypeBanked: "Банк сбросов",
        .rateLimitResetTypeGlobal: "Глобальный сброс",
        .rateLimitResetTypeGlobalAndBanked: "Глобальный сброс + банк сбросов",
        .rateLimitResetTodayUnknown: "—",
        .rateLimitResetTodayUnknownHint: "Статус недоступен или устарел",
        .rateLimitResetTodayVerdict: "Вердикт",
        .rateLimitResetTodayWindowFiveHour: "5-часовое окно",
        .rateLimitResetTodayWindowUnknown: "Окно не указано",
        .rateLimitResetTodayWindowWeekly: "Недельный лимит",
        .rateLimitResetTodayWindows: "Окно лимита",
        .rateLimitResetTodayYes: "Да",
        .rateLimitResetTodayYesHint: "Лимиты сегодня сброшены",
        .rateLimitResetTodayYesHintWithTime: "Сброс сегодня · %@",
        .rateLimitResetTodayYesHintScheduled: "Глобальный сброс запланирован на сегодня, но ещё не завершён",
        .rateLimitResetTodayYesHintScheduledWithTime: "Запланировано сегодня, ещё не завершено · %@",
        .rateLimitResetTodayPercentPrefix: "≥%@%%",
        .rateLimitResetTodayPercentExact: "%@%%",
        .rateLimitResetTodayClockLocal: "местному времени",
        .rateLimitResetTodayConfirmedWhen: "%@ (%@ назад)",
        .rateLimitResetTodayConfirmedHint:
            "Сегодня зафиксирован завершённый {type}. Уверенность около {percent}. Время сброса по {zone}: {when}",
        .rateLimitResetTodayConfirmedHintNoPercent:
            "Сегодня зафиксирован завершённый {type}. Время сброса по {zone}: {when}",
        .rateLimitResetTodayScheduledChanceHint:
            "Около {percent} вероятности {type}; сейчас запланировано. Примерное окно сброса ({zone}): {date}",
        .rateLimitResetUpcomingAlertBody1h: "До запланированного сброса Codex меньше 1 часа.",
        .rateLimitResetUpcomingAlertBody30m: "До запланированного сброса Codex меньше 30 минут.",
        .rateLimitResetUpcomingRangeAlertBody: "Ожидаемое окно сброса: %@.",
        .rateLimitResetUpcomingRangeAlertTitle: "Ожидаемое окно сброса Codex",
        .rateLimitResetUpcomingAlertTitle: "Приближается сброс Codex",
        .rateLimitResetUpcomingTypedAlertTitle: "Codex: скоро %@",
        .rateLimitResetUpcomingTypedRangeAlertTitle: "Ожидаемое окно Codex: %@",
        .recent: "Недавние",
        .recentSessionsDescription: "При включении сканирует локальные сессии.",
        .refresh: "Обновить",
        .refreshInterval: "Интервал обновления",
        .rebuilt: "Пересобрано",
        .repair: "Исправить",
        .repairConfirmMessage: "CodexRunway пересоберёт ~/.codex/session_index.jsonl из локальных файлов сессий. Перед записью рядом с индексом будет создана резервная копия с меткой времени. Журналы сессий, auth.json и глобальное состояние не изменяются.",
        .repairConfirmTitle: "Исправить индекс сессий Codex?",
        .repairFailed: "Ошибка восстановления",
        .repairIndex: "Исправить индекс",
        .resetsIn: "сброс через",
        .resetCredits: "Кредиты сброса",
        .resetCreditAlertBody: "Кредит сброса скоро истечёт.",
        .resetCreditAlertTitle: "Истекает кредит сброса",
        .resetCreditAlertsDescription: "Оповещения, если доступный кредит сброса истекает в течение 7 дней.",
        .resetCreditAlerts: "Оповещения о кредитах сброса",
        .resetCreditDetails: "Сведения о кредитах сброса",
        .restoreDefaultOrder: "Восстановить порядок по умолчанию",
        .runway: "Runway",
        .seconds: "с",
        .sessionRepair: "Восстановление сессий",
        .sessionScanFailed: "Ошибка сканирования сессий",
        .recentSessions: "Недавние сессии",
        .settings: "Настройки",
        .selfCheck: "Самопроверка",
        .showDetails: "Показать сведения",
        .showCostSummary: "Показать сводку стоимости API",
        .showModelSpecificQuotaUsage: "Показать использование квоты по моделям",
        .showRateLimitResetToday: "Показать статус сброса сегодня",
        .showRecentSessions: "Показать недавние сессии",
        .showSessionRepairSummary: "Показать сводку восстановления сессий",
        .showTokenUsageHeatmap: "Показать использование токенов",
        .mainPanelModules: "Модули главной панели",
        .mainPanelModulesDescription: "Выберите, какие модули показывать, и их порядок. Скрытые модули сохраняют позицию.",
        .moduleAPICostDescription: "Оценка эквивалентной стоимости API по локальным сессиям.",
        .moduleAppliesCodex: "Codex",
        .moduleAppliesBoth: "Codex и Grok",
        .moduleHidden: "Скрыто",
        .moduleQuotaDescription: "Индикаторы квоты и лимиты по моделям.",
        .moduleQuotaEstimateDescription: "Оценка недельной квоты по истории использования, чтобы заметить снижение.",
        .moduleResetCreditsDescription: "Доступные кредиты сброса и сведения об истечении.",
        .moduleSessionRepairDescription: "Состояние локального индекса сессий и инструменты восстановления.",
        .moduleVisible: "Видимо",
        .notificationSettings: "Уведомления",
        .tokenUsageHeatmap: "Использование токенов",
        .tokenUsageHeatmapDescription: "График использования токенов с начала года (теплокарта, линия или столбцы).",
        .tokenUsageHeatmapUnavailable: "Использование токенов временно недоступно",
        .tokenUsageChartStyle: "Стиль графика",
        .tokenUsageChartHeatmap: "Теплокарта",
        .tokenUsageChartLine: "Линия",
        .tokenUsageChartBar: "Столбцы",
        .heatmapDaily: "По дням",
        .heatmapWeekly: "По неделям",
        .heatmapCumulative: "Итого",
        .heatmapMonthly: "По месяцам",
        .heatmapEmpty: "В этом году использования токенов ещё нет",
        .heatmapAllDevices: "Официальная статистика (все устройства)",
        .heatmapLocalDevice: "Локальные журналы (все сессии)",
        .heatmapLocalShort: "Локально",
        .heatmapOfficialAsOf: "Официально по %@",
        .heatmapSourceDisclosure: "Официальная статистика может запаздывать или пересматриваться. Локальные журналы включают все сессии на этом Mac и могут охватывать несколько аккаунтов. Дневные значения используют даты UTC.",
        .heatmapSourceMismatch: "Разные источники; значения нельзя сравнивать как подмножество.",
        .sourceLocalSessions: "Локальные сессии",
        .sourceOnlineSupplement: "Онлайн-дополнение",
        .staleTitles: "Устаревшие заголовки",
        .status: "Статус",
        .subscriptionExpired: "Истекла",
        .subscriptionExpires: "Действует до",
        .subscriptionExpiringSoon: "Скоро истечёт",
        .statusAvailable: "доступно",
        .statusError: "ош.",
        .statusLogin: "вход",
        .statusBarBattery: "Батарея с обратным отсчётом",
        .statusBarBatteryDetailCountdown: "Обратный отсчёт сброса",
        .statusBarBatteryDetailRemainingPercent: "Оставшийся процент",
        .statusBarBatteryDetailStyle: "Текст в центре батареи",
        .statusBarBatteryScope: "Квота батареи",
        .statusBarBatteryScopeBoth: "Все видимые",
        .statusBarBatteryScopeFiveHour: "5 часов",
        .statusBarBatteryScopeWeekly: "Неделя",
        .statusBarCountdown: "Обратный отсчёт",
        .statusBarMetersDetailResetTime: "Время сброса",
        .statusBarMetersDetailRemainingPercent: "Оставшийся процент",
        .statusBarMetersDetailBoth: "Оба",
        .statusBarMetersDetailStyle: "Детали полосы квоты",
        .statusBarMeters: "Полосы квоты",
        .statusBarProviderScope: "Платформы в строке меню",
        .statusBarProviderScopeBoth: "Codex + Grok",
        .statusBarProviderScopeSelected: "Следовать текущей панели",
        .statusBarRings: "Кольца квоты",
        .statusBarStyle: "Стиль строки меню",
        .statusBarText: "Текст прогресса",
        .statusUsed: "использовано",
        .statusWait: "ожидание",
        .statusUnknown: "неизвестно",
        .startDate: "Дата начала",
        .updateAvailable: "Доступно обновление",
        .updateCheckFailed: "Ошибка проверки обновлений",
        .updateChecking: "Проверка обновлений...",
        .updateDownloadAndInstall: "Скачать и установить",
        .updateDownloadedReady: "CodexRunway %@ скачан и готов к установке.",
        .updateDownloading: "Загрузка обновления...",
        .updateExtracting: "Распаковка обновления...",
        .updateInstallAndRelaunch: "Установить и перезапустить",
        .updateInstallLater: "Позже",
        .updateInstalled: "Обновление установлено",
        .updateInstalledMessage: "CodexRunway обновлён.",
        .updateInstalling: "Установка обновления...",
        .updateLearnMore: "Подробнее",
        .updateNetworkProxyHint: "Если вы используете системный прокси, убедитесь, что github.com и release-assets.githubusercontent.com не в списке обхода системного прокси, либо используйте режим TUN.",
        .updateReadyToInstall: "Готово к установке",
        .updateSigningKeyMissing: "Ключ подписи Sparkle не настроен.",
        .updateSkipVersion: "Пропустить эту версию",
        .updateUnavailableInDevelopment: "Обновления нельзя установить при запуске через swift run. Для проверки обновлений Sparkle используйте упакованный .app или Release-сборку.",
        .updateVersionAvailable: "Доступен CodexRunway %@.",
        .upToDate: "CodexRunway уже обновлён.",
        .total: "Итого",
        .totalRemaining: "Всего осталось",
        .tokens: "Tokens",
        .tokensOnly: "только токены",
        .testNotification: "Тестовое уведомление",
        .testNotificationBody: "Уведомления CodexRunway работают.",
        .testNotificationDevelopmentMode: "Системные уведомления требуют запуска упакованного CodexRunway.app. Их нельзя проверить из swift run.",
        .testNotificationSubtitle: "Запрашивает разрешение на уведомления macOS и отправляет тестовое оповещение.",
        .testNotificationTitle: "Тест CodexRunway",
        .threads: "потоки",
        .today: "Сегодня",
        .thisMonth: "Этот месяц",
        .turns: "ходы",
        .unknown: "неизвестно",
        .unknownAccount: "Неизвестный аккаунт",
        .unknownModels: "Неизвестные модели",
        .unavailableCredits: "Недоступно",
        .usageAnalyticsUnavailable: "Аналитика использования недоступна",
        .usageAnalyticsEmpty: "В этом диапазоне нет использования",
        .used: "использовано",
        .usdPerCredit: "USD за кредит",
        .version: "Версия",
        .weeklyValueEstimate: "Оценка недельной стоимости",
        .weeklyUsage: "Неделя",
        .widgetAllDevices: "Все устройства",
        .widgetBalance: "Баланс",
        .widgetCost: "Эквивалент API",
        .widgetDataCorrupt: "Данные виджета повреждены. Обновите CodexRunway.",
        .widgetDataOld: "Данные устарели",
        .widgetMetricTitle: "Ключевой показатель",
        .widgetNoData: "Откройте CodexRunway, чтобы загрузить данные виджета.",
        .widgetOverviewTitle: "Обзор квоты",
        .widgetRefreshInterval: "Обновление виджета",
        .widgetRefreshIntervalDescription: "CodexRunway запрашивает обновления с этим интервалом во время работы; macOS решает, когда они появятся.",
        .widgetRemaining: "Осталось",
        .widgetResetCredits: "Сбросы",
        .widgetResetTodayTitle: "Сброс сегодня",
        .widgetThisMac: "Этот Mac",
        .widgetTokenTrendTitle: "Тренд токенов",
        .widgetUpdated: "Обновлено",
        .widgetVersionUnsupported: "Обновите CodexRunway, чтобы читать эти данные виджета.",
        .languageTraditionalChinese: "Традиционный китайский",
        .languageKorean: "Корейский",
        .languageJapanese: "Японский",
        .languageRussian: "Русский",
        .languageFrench: "Французский",
    ]
}
