extension L10n {
    static let ko: [L10nKey: String] = [
        .apiCost: "API 환산 비용",
        .apiCostSummaryRange: "API 비용 범위",
        .apiCostSource: "비용 출처",
        .apiEquivalent: "API 환산",
        .apiTokenPricing: "API 토큰 가격",
        .appearance: "모양",
        .appearanceDark: "다크",
        .appearanceLight: "라이트",
        .appearanceSystem: "시스템",
        .auto: "자동",
        .about: "정보",
        .advanced: "고급",
        .account: "계정",
        .accounts: "계정",
        .accountsAdd: "계정 추가",
        .accountsAddAPIKey: "API Key",
        .accountsAddFile: "파일 가져오기",
        .accountsAddLocal: "로컬 auth.json 가져오기",
        .accountsAddOAuth: "브라우저로 로그인",
        .accountsAddPaste: "토큰 / JSON 붙여넣기",
        .accountsAPIKeyHint: "OpenAI API 키를 붙여넣으세요. API 계정은 ChatGPT 할당량 미터를 표시하지 않습니다.",
        .accountsCurrent: "현재",
        .accountsDelete: "제거",
        .accountsDeleteConfirmMessage: "이 계정을 CodexRunway에서 제거할까요? 현재 계정이 아니면 공식 Codex 로그인은 바뀌지 않습니다.",
        .accountsDeleteConfirmTitle: "계정을 제거할까요?",
        .accountsDeselectAll: "모두 선택 해제",
        .accountsEmpty: "관리 계정이 없습니다. 로컬 auth.json을 가져오거나 다른 계정을 추가하세요.",
        .accountsExport: "내보내기",
        .accountsExportEmpty: "내보낼 계정이 없습니다.",
        .accountsExportFailed: "내보내기 실패",
        .accountsExportHint: "현재 플랫폼에서 내보낼 계정을 선택하세요. 파일은 다른 Mac의 CodexRunway에서 가져올 수 있습니다.",
        .accountsExportSucceeded: "%d개 계정을 내보냈습니다",
        .accountsExportTitle: "계정 내보내기",
        .accountsExportWarning: "내보내기 파일에는 로그인 정보가 들어 있습니다. 안전하게 보관하고 전송하세요.",
        .accountsForceCurrent: "환경의 현재 로그인으로 강제 설정",
        .accountsImportFailed: "가져오기 실패",
        .accountsImportNoCredentials: "자격 증명을 찾지 못했습니다. auth.json, refresh token 또는 ChatGPT /auth/session JSON(accessToken)을 붙여넣으세요.",
        .accountsImportPreviewHint: "선택한 파일에서 찾은 계정을 확인하세요. 가져오지 않을 항목은 선택을 해제하세요.",
        .accountsImportPreviewTitle: "계정 가져오기",
        .accountsImportProgress: "가져오는 중 %d / %d",
        .accountsImportProviderNotice: "%@ 계정으로 가져왔습니다",
        .accountsImportSelected: "선택 항목 가져오기",
        .accountsImportSucceeded: "%d개 계정을 가져왔습니다",
        .accountsImportWillAdd: "추가됨",
        .accountsImportWillUpdate: "업데이트됨",
        .accountsUserIdLabel: "사용자 ID:",
        .accountsWorkspaceIdLabel: "워크스페이스 ID:",
        .accountsWorkspaceNameLabel: "워크스페이스:",
        .accountsIsCurrentLogin: "현재 Codex 로그인 계정입니다",
        .accountsMakeCurrent: "Codex에서 사용",
        .accountsMoveDown: "아래로",
        .accountsMoveUp: "위로",
        .accountsNeedsReauth: "재인증 필요",
        .accountsNote: "메모",
        .accountsOAuthCancelled: "브라우저 로그인이 취소되었습니다.",
        .accountsOAuthFailed: "브라우저 로그인 실패",
        .accountsOAuthWaiting: "브라우저에서 로그인을 완료하세요…",
        .accountsPasteFromClipboard: "클립보드에서 붙여넣기",
        .accountsPasteHint: "refresh token, ~/.codex/auth.json, ChatGPT /api/auth/session JSON 또는 계정 JSON 배열을 붙여넣으세요.",
        .accountsRefreshAll: "모든 할당량 새로고침",
        .accountsReauthRequired: "다시 로그인",
        .accountsRestartCodexAfterSwitch: "전환 후 바로 Codex 재시작",
        .accountsRestartCodexFailed: "계정은 전환되었지만 Codex를 재시작하지 못했습니다: %@",
        .accountsRestartCodexSucceeded: "계정이 전환되었습니다. Codex를 재시작했습니다.",
        .accountsSelectAll: "모두 선택",
        .accountsSidebarTitle: "계정",
        .accountsSwitchConfirmTitle: "계정을 전환할까요?",
        .accountsSwitchConfirmMessage: "~/.codex/auth.json을 “%@”(으)로 바꾸고, Codex는 재시작 후 적용합니다.",
        .accountsSwitchFailed: "계정을 전환하지 못했습니다",
        .accountsSwitchInvalidCredential: "이 계정의 자격 증명이 잘못되었거나 불완전하여 Codex 로그인으로 사용할 수 없습니다.",
        .accountsSwitchMissingRefresh: "이 계정에는 refresh_token이 없습니다. 액세스 토큰이 유효한 동안은 전환할 수 있습니다. 만료되면 세션을 다시 가져오거나 브라우저로 로그인하세요.",
        .accountsSwitchSessionExpired: "이 세션의 액세스 토큰이 만료되었고 refresh_token이 없습니다. /auth/session에서 다시 가져오거나 브라우저로 로그인하세요.",
        .accountsSwitching: "계정 전환 중…",
        .accountsSwitchRealHint: "전환하면 선택한 계정이 ~/.codex/auth.json에 쓰여 Codex CLI와 IDE가 사용합니다.",
        .alias: "별칭",
        .automaticallyCheckForUpdates: "업데이트 자동 확인",
        .available: "사용 가능",
        .availableResets: "사용 가능한 리셋",
        .back: "뒤로",
        .backup: "백업",
        .cachedInput: "캐시된 입력",
        .cachedInputTokens: "캐시된 입력 토큰",
        .cancel: "취소",
        .calculate: "계산",
        .calculating: "계산 중",
        .codexFolder: "Codex 폴더 열기",
        .controlPanel: "제어판",
        .calculatedAt: "계산 시각",
        .costShare: "비용 비중",
        .costScanFailed: "비용 스캔 실패",
        .costScanPreparing: "사용량 스캔 준비 중…",
        .costScanIndexing: "세션 로그 인덱싱 중…",
        .costScanAggregating: "사용량 집계 중…",
        .costScanFetchingOnline: "온라인 사용량 가져오는 중…",
        .costScanProgressFiles: "%d / %d개 파일",
        .credit: "크레딧",
        .creditsBalance: "크레딧 잔액",
        .creditsUsed: "사용한 크레딧",
        .currentCycle: "현재 주기",
        .currentCycleAmount: "현재 주기 금액",
        .customRange: "사용자 지정",
        .customRangePrompt: "날짜 범위를 선택한 뒤 계산을 클릭하세요",
        .cycleStarted: "시작",
        .date: "날짜",
        .burnRate: "소진 속도",
        .duplicate: "중복",
        .duplicateIndexIDs: "중복 인덱스 ID",
        .display: "표시",
        .displayAppearanceSection: "모양 및 메뉴 막대",
        .mainPanelBackground: "패널 배경",
        .mainPanelBackgroundDescription: "반투명은 패널 뒤의 창이 비칩니다.",
        .mainPanelBackgroundOpaque: "불투명",
        .mainPanelBackgroundTranslucent: "반투명",
        .endDate: "종료일",
        .estimatedAPICost: "추정 API 비용",
        .expiresRemaining: "남은 유효 기간",
        .expiresAt: "만료",
        .expiryRisk: "만료 위험",
        .expiringSoon: "곧 만료",
        .exhaustsIn: "소진까지",
        .error: "오류",
        .exportStatusJSON: "로컬 상태 JSON 내보내기",
        .failed: "실패",
        .checkForUpdates: "업데이트 확인",
        .fiveHourUsage: "5시간",
        .general: "일반",
        .grokAccountsAddFile: "파일 가져오기",
        .grokAccountsAddOAuth: "새 Grok 계정으로 로그인",
        .grokAccountsAddPaste: "토큰 / JSON 붙여넣기",
        .grokAccountsCurrent: "현재 Grok 계정",
        .grokAccountsDeleteConfirmMessage: "이 계정을 CodexRunway에서 제거할까요? 공식 Grok 로그인은 바뀌지 않습니다.",
        .grokAccountsDeleteConfirmTitle: "Grok 계정을 제거할까요?",
        .grokAccountsEmpty: "관리 중인 Grok 계정이 없습니다. 로그인하거나 현재 Grok 로그인을 가져오거나 자격 증명을 붙여넣으세요.",
        .grokAccountsImportNoCredentials: "자격 증명을 찾지 못했습니다. ~/.grok/auth.json 또는 Grok 자격 증명 객체(key/refresh_token과 email, user_id 또는 principal_id)를 붙여넣으세요.",
        .grokAccountsImportOfficial: "현재 Grok 로그인 가져오기",
        .grokAccountsMakeCurrent: "Grok에서 사용",
        .grokAccountsPasteHint: "~/.grok/auth.json, 단일 Grok OAuth/레거시 자격 증명 객체 또는 계정 JSON 배열을 붙여넣으세요. API 키만 있는 자격 증명은 지원되지 않습니다.",
        .grokAccountsRefreshAll: "모든 Grok 할당량 새로고침",
        .grokAccountsRemove: "Grok 계정 제거",
        .grokAccountsTitle: "Grok 계정",
        .grokBillingParseFailed: "Grok이 지원하지 않는 결제 응답을 반환했습니다. CLI를 업데이트하거나 나중에 다시 시도하세요.",
        .grokBillingPeriod: "결제 주기",
        .grokBillingPeriodMonthly: "월간 포함 할당량",
        .grokBillingPeriodWeekly: "주간 포함 할당량",
        .grokCLIInstallHint: "공식 Grok CLI를 설치한 뒤 OAuth로 로그인하면 결제를 볼 수 있습니다.",
        .grokCLIOpenInstallGuide: "Grok CLI 설치 가이드 열기",
        .grokCLITooOld: "이 Grok CLI 버전은 결제를 지원하지 않습니다. CLI를 업데이트한 뒤 다시 시도하세요.",
        .grokCLIUnavailable: "Grok CLI가 설치되어 있지 않습니다",
        .grokCurrentAccountCannotDelete: "현재 계정을 제거하기 전에 다른 Grok 계정으로 전환하세요.",
        .grokDataSource: "데이터 출처",
        .grokExternalLoginChanged: "다른 프로세스가 Grok 로그인을 변경했습니다. 계정 상태를 공식 자격 증명과 동기화했습니다.",
        .grokImportFailed: "현재 Grok 로그인을 가져오지 못했습니다",
        .grokImportSucceeded: "현재 Grok 로그인을 가져왔습니다",
        .grokIncludedQuota: "포함 할당량",
        .grokIncludedUSD: "포함 USD 크레딧",
        .grokLocalUsage: "로컬 토큰 사용량",
        .grokLocalUsageHint: "이 Mac의 최근 Grok CLI 세션(turn_completed 사용량)에서 가져옵니다.",
        .grokLoginCancelled: "Grok 로그인이 취소되었습니다.",
        .grokLoginFailed: "Grok 로그인 실패",
        .grokLoginWaiting: "브라우저에서 Grok 로그인을 완료하세요(기기 코드 페이지가 자동으로 열립니다)…",
        .grokNoManagedOAuth: "관리 가능한 OAuth 또는 호환 레거시 Grok 로그인을 찾지 못했습니다.",
        .grokNoQuotaData: "아직 Grok 결제 데이터가 없습니다.",
        .grokNotLoggedIn: "Grok에 로그인되어 있지 않습니다",
        .grokOnDemandLimit: "온디맨드 한도",
        .grokOnDemandUsage: "온디맨드 사용량",
        .grokPlan: "Grok 플랜",
        .grokPrepaidBalance: "선불 잔액",
        .grokProductBuild: "Grok Build",
        .grokProductChat: "Grok Chat",
        .grokProductImagine: "Grok Imagine",
        .grokProductUsage: "제품 사용량",
        .grokReauthenticationRequired: "Grok 로그인이 만료되었습니다. 다시 로그인하세요.",
        .grokRefreshFailed: "Grok 결제를 새로고침하지 못했습니다",
        .grokRefreshCancelled: "Grok 결제 새로고침이 취소되었습니다.",
        .grokRefreshTimedOut: "Grok 결제 요청이 시간 초과되었습니다.",
        .grokRefreshing: "Grok 결제 새로고침 중…",
        .grokResetAt: "리셋",
        .grokSessionsScanned: "%d개 세션 스캔됨",
        .grokSourceCLI: "Grok CLI 결제 API",
        .grokSourceLocalSessions: "로컬 Grok 세션",
        .grokSwitchConfirmMessage: "공식 Grok OAuth 로그인을 “%@”(으)로 바꿀까요? 새 Grok 세션만 사용이 보장됩니다.",
        .grokSwitchConfirmTitle: "Grok 계정을 전환할까요?",
        .grokSwitchFailed: "Grok 계정을 전환하지 못했습니다",
        .grokSwitchOnlyNewSessions: "계정 전환은 새 Grok 세션에만 적용됩니다.",
        .grokSwitchRunningMessage: "하나 이상의 Grok 프로세스가 아직 실행 중입니다. 전환 후 이전 로그인을 다시 쓸 수 있습니다. 계속하면 새 Grok 세션만 선택한 계정을 사용하도록 보장됩니다.",
        .grokSwitchRunningTitle: "Grok이 실행 중입니다",
        .grokSwitching: "Grok 계정 전환 중…",
        .grokUnifiedBilling: "통합 결제",
        .grokUpdatedAt: "Grok 결제 업데이트됨",
        .hours: "시간",
        .modelBreakdown: "모델별 내역",
        .modelSpecificQuotaUsageDescription: "메뉴 막대와 메인 패널에 모델별 할당량 진행률을 표시합니다.",
        .noModelCostData: "모델 비용 데이터 없음",
        .nonCachedInput: "비캐시 입력",
        .inputShort: "in",
        .inputCachedOutput: "입력 / 캐시 / 출력",
        .inputTokens: "입력 토큰",
        .invalidDateRange: "잘못된 날짜 범위",
        .language: "언어",
        .languageEnglish: "영어",
        .languageSimplifiedChinese: "중국어 간체",
        .lastReset: "마지막 리셋",
        .lastUpdated: "업데이트됨",
        .later: "나중에",
        .left: "남음",
        .minutes: "분",
        .missing: "누락",
        .missingFromIndex: "인덱스에 없음",
        .nextResetIn: "다음 리셋: ",
        .nextExpiry: "다음 만료",
        .needsAttention: "확인 필요",
        .noExpiry: "만료 없음",
        .noAvailableResetCredits: "리셋 크레딧 없음",
        .notLoggedIn: "로그인되지 않음",
        .authExpired: "로그인이 만료되었습니다. 다시 로그인하거나 유효한 refresh_token이 있는 계정으로 전환하세요.",
        .authFileInvalid: "로컬 auth.json이 잘못되었거나 불완전합니다. 사용 가능한 계정을 복원하거나 다시 로그인하세요.",
        .noPreviousIndex: "이전 인덱스 없음",
        .notLoaded: "불러오지 않음",
        .notScanned: "스캔하지 않음",
        .ok: "확인",
        .openControlPanel: "제어판 열기",
        .openDetailsWindow: "세부 창 열기",
        .orphan: "고아",
        .orphanIndexRows: "고아 인덱스 행",
        .outputTokens: "출력 토큰",
        .outputShort: "out",
        .openGithub: "GitHub 열기",
        .tokenComposition: "토큰 구성",
        .feedbackIssue: "피드백",
        .historicalUsage: "과거 사용량",
        .privacy: "토큰은 이 Mac에만 있습니다. 세션 복구는 백업을 만든 뒤에만 로컬 인덱스를 다시 씁니다.",
        .plan: "플랜",
        .planAPI: "API",
        .planBusiness: "Business",
        .planEdu: "Edu",
        .planEnterprise: "Enterprise",
        .planFree: "Free",
        .planPlus: "Plus",
        .planPro5x: "Pro 5X",
        .planPro20x: "Pro 20X",
        .planTeam: "Team",
        .planUnknown: "알 수 없음",
        .plannedEntries: "예정 항목",
        .pricingVersion: "가격 버전",
        .projectBreakdown: "프로젝트별 내역",
        .projectedAtReset: "리셋 시점 예측",
        .projectedWeeklyTotal: "주간 합계 예측",
        .previousCycle: "이전 주기",
        .providerCodex: "Codex",
        .providerGrok: "Grok",
        .quota: "할당량",
        .quotaAlertBody: "%@의 사용량이 %@에 도달했습니다.",
        .quotaAlertTitle: "Codex 할당량 알림",
        .quotaAlertsDescription: "사용량이 80%, 95% 또는 100%에 도달하면 알립니다.",
        .quotaAlerts: "할당량 알림",
        .quotaEstimate: "구독 한도 추정",
        .quotaEstimateCannotExtrapolate: "이번 주 사용량이 부족해 추정할 수 없음",
        .quotaEstimateCredits: "Credits",
        .quotaEstimateCut: "삭감 가능성",
        .quotaEstimateHistory: "이전 추정",
        .quotaEstimateIncreased: "이전보다 증가",
        .quotaEstimateInfo: "공식 사용률과 일별 Credits로 한도를 추정합니다. 1000 Credits ≈ $40은 비공식 환산이며 표의 토큰 기준가 비용과 다릅니다. 일별 집계로는 할당량 기간 경계를 정확히 나눌 수 없으므로 추정치는 참고용입니다.",
        .quotaEstimateMethodOfficial: "자동 창",
        .quotaEstimateMethodRolling: "최근 7일",
        .quotaEstimateMissingCredits: "공식 통계의 Credits 데이터가 완전하지 않아 한도를 추정할 수 없습니다",
        .quotaEstimateNoUsage: "현재 기간의 사용량이 아직 없어 한도를 추정할 수 없습니다",
        .quotaEstimateShowingPreviousData: "새로고침에 실패하여 이전에 가져온 데이터를 표시합니다",
        .quotaEstimateStatsThrough: "통계 기준일 %@",
        .quotaEstimateUnavailableWindow: "추정에 사용할 할당량 기간이 없습니다",
        .quotaEstimateZeroCreditsWithUsage: "공식 통계에 토큰 사용량이 있지만 Credits가 0으로 반환되어 한도를 추정할 수 없습니다",
        .quotaEstimateZeroPercent: "사용률이 0%이므로 아직 한도를 추정할 수 없습니다",
        .quotaEstimateThisWeek: "이번 주",
        .quotaEstimateThisWeekUsed: "이번 주 사용량",
        .quotaEstimateUsedPercent: "사용 비율",
        .quotaEstimateWeekValue: "주간 가치(추정)",
        .quotaEstimateWeeklyAllowance: "추정 주간 한도",
        .quotaEstimateWindowMode: "추정 창",
        .quotaEstimateWindowOfficial: "자동 창",
        .quotaEstimateWindowRolling: "최근 7 달력일",
        .quotaEstimateVsLast: "이전 대비",
        .quit: "종료",
        .rawAnalyticsCredits: "원시 분석 크레딧",
        .rateLimitResetDetectedAlertBody: "오늘 Codex 할당량 리셋이 방금 감지되었습니다.",
        .rateLimitResetDetectedBankedAlertBody: "필요할 때 사용할 수 있는 리셋 횟수가 리셋 뱅크에 저장되었습니다. 현재 할당량은 자동으로 갱신되지 않습니다.",
        .rateLimitResetDetectedGlobalAndBankedAlertBody: "전체 리셋이 완료되었고 별도의 리셋 횟수가 필요할 때 사용할 수 있도록 리셋 뱅크에 저장되었습니다. 뱅크 횟수 자체는 현재 할당량을 갱신하지 않습니다.",
        .rateLimitResetDetectedAlertTitle: "Codex 리셋 감지됨",
        .rateLimitResetDetectedTypedAlertTitle: "Codex %@ 확인됨",
        .rateLimitResetToday: "오늘 리셋되었나요?",
        .rateLimitResetTodayAlerts: "오늘 리셋 알림",
        .rateLimitResetTodayAlertsDescription: "새로 감지된 리셋과 예정 리셋이 1시간 또는 30분 이내일 때 알립니다.",
        .rateLimitResetTodayAwaiting: "오늘 완료되거나 예정된 리셋이 없습니다",
        .rateLimitResetTodayBankedCompletedHint: "필요할 때 쓸 수 있는 횟수가 리셋 뱅크에 저장되었으며 현재 할당량은 갱신되지 않았습니다",
        .rateLimitResetTodayBankedScheduledHint: "리셋 뱅크 횟수가 오늘 늦게 도착할 예정이며 아직 적립되지 않았습니다",
        .rateLimitResetTodayCheckCost: "확인 비용",
        .rateLimitResetTodayConfidence: "신뢰도",
        .rateLimitResetTodayDescription: "www.codexrunway.com의 공개 상태입니다.",
        .rateLimitResetTodayEvidenceBankedReset: "적립 리셋이 발표되었습니다. 완료된 리셋은 아닙니다.",
        .rateLimitResetTodayEvidenceBankedCompleted: "필요할 때 사용할 수 있는 리셋 뱅크 횟수의 도착이 확인되었습니다.",
        .rateLimitResetTodayEvidenceBankedPreview: "문맥에서 가능성이 높은 리셋 뱅크 적립이 추론되었습니다.",
        .rateLimitResetTodayEvidenceBankedScheduled: "리셋 뱅크 적립이 명시적으로 예정되었습니다.",
        .rateLimitResetTodayEvidenceGlobalAndBankedCompleted: "전체 리셋과 리셋 뱅크 적립이 확인되었습니다.",
        .rateLimitResetTodayEvidenceGlobalAndBankedPreview: "문맥에서 가능성이 높은 전체 리셋과 리셋 뱅크 적립이 추론되었습니다.",
        .rateLimitResetTodayEvidenceGlobalAndBankedScheduled: "전체 리셋과 리셋 뱅크 적립이 명시적으로 예정되었습니다.",
        .rateLimitResetTodayEvidenceLimitIncrease: "할당량 한도 인상이 발표되었습니다. 리셋은 아닙니다.",
        .rateLimitResetTodayEvidenceResetCompleted: "명시적인 Codex 할당량 리셋이 발표되었습니다.",
        .rateLimitResetTodayEvidenceResetScheduled: "명시적인 Codex 할당량 리셋이 예정되었습니다.",
        .rateLimitResetTodayEvidenceResetPreview: "문맥에서 가능성이 높은 Codex 할당량 리셋이 추론되었습니다.",
        .rateLimitResetTodayEvidenceManualCompletion: "X 완료 게시물 없이 확인되었습니다.",
        .rateLimitResetTodayEvidenceOperatorCompletion: "운영자가 리셋을 확인했습니다. Tibo는 X에 게시하지 않았습니다.",
        .rateLimitResetTodayEvidenceOperatorScheduled: "운영자가 리셋 일정을 확인했습니다. Tibo는 X에 게시하지 않았습니다.",
        .rateLimitResetTodayEvidenceUncertain: "명확한 리셋 신호가 아닙니다.",
        .rateLimitResetTodayLastCheck: "마지막 확인",
        .rateLimitResetTodayLastFetched: "마지막 새로고침",
        .rateLimitResetTodayLocalDayHint: "로컬 달력 날짜를 사용하며 자정에 바뀝니다.",
        .rateLimitResetTodayLatestEvidence: "최신 근거",
        .rateLimitResetTodayNextScheduled: "다음 예상 리셋",
        .rateLimitResetTodayNextScheduledWithCountdown: "다음 예상 리셋: %@ (%@)",
        .rateLimitResetTodayNo: "아니요",
        .rateLimitResetTodayNoHint: "오늘 완료되거나 예정된 리셋이 없습니다",
        .rateLimitResetTodayNoHintUncertain: "오늘 명확한 리셋 신호가 없습니다",
        .rateLimitResetTodayNoHintUnconfirmedSchedule: "예정된 {type} 시간이 지났지만 확인되지 않았습니다",
        .rateLimitResetTodayNoHintWithLast: "오늘 완료되거나 예정된 리셋이 없습니다. 마지막 {type}은 {ago} 전",
        .rateLimitResetTodayNoHintWithNext: "오늘은 리셋 없음 · 다음 예상 리셋 %@",
        .rateLimitResetTodayOpenSource: "상태 페이지 열기",
        .rateLimitResetTodayOpenWebsite: "CodexRunway 웹에서 리셋 상태와 기록을 보기",
        .rateLimitResetTodayOpenEvidence: "X 출처 열기",
        .rateLimitResetTodayResetAgo: "%@ 전에 리셋됨",
        .rateLimitResetTodayUntilReset: "리셋까지 %@",
        .rateLimitResetTodayPlanAll: "모든 플랜",
        .rateLimitResetTodayPlanBusiness: "Business",
        .rateLimitResetTodayPlanEnterprise: "Enterprise",
        .rateLimitResetTodayPlanFree: "Free",
        .rateLimitResetTodayPlanPlus: "Plus",
        .rateLimitResetTodayPlanPro: "Pro",
        .rateLimitResetTodayPlanTeam: "Team",
        .rateLimitResetTodayPlanUnknown: "플랜 미지정",
        .rateLimitResetTodayPlans: "플랜",
        .rateLimitResetTodayRefreshInterval: "리셋 상태 새로고침",
        .rateLimitResetTodayReactionPlease: "리셋 요청",
        .rateLimitResetTodayReactionThank: "감사합니다",
        .rateLimitResetTodayReactionPleaseAria: "리셋 요청, 현재 %@",
        .rateLimitResetTodayReactionThankAria: "리셋에 감사, 현재 %@",
        .rateLimitResetTodayReactionLimitReached: "오늘 클릭 한도에 도달했습니다",
        .rateLimitResetTodaySeen: "확인됨",
        .rateLimitResetTodaySource: "CodexRunway 리셋 상태",
        .rateLimitResetTodaySourceInfo: "CodexRunway는 공개 X 발표를 AI로 분석하는 호스티드 모니터에서 이 상태를 게시합니다. AI 결과는 불완전하거나 틀릴 수 있습니다.",
        .rateLimitResetTodaySourceTitle: "데이터 출처",
        .rateLimitResetTodayGlobalAndBankedCompletedHint: "전체 할당량이 리셋되었고 별도의 횟수가 필요할 때 쓰도록 리셋 뱅크에 저장되었습니다",
        .rateLimitResetTodayGlobalAndBankedScheduledHint: "전체 리셋과 리셋 뱅크 적립이 오늘 늦게 예정되어 있으며 아직 발생하지 않았습니다",
        .rateLimitResetTypeBanked: "리셋 뱅크",
        .rateLimitResetTypeGlobal: "전체 리셋",
        .rateLimitResetTypeGlobalAndBanked: "전체 리셋 + 리셋 뱅크",
        .rateLimitResetTodayUnknown: "—",
        .rateLimitResetTodayUnknownHint: "상태를 사용할 수 없거나 오래되었습니다",
        .rateLimitResetTodayVerdict: "판정",
        .rateLimitResetTodayWindowFiveHour: "5시간 창",
        .rateLimitResetTodayWindowUnknown: "창 미지정",
        .rateLimitResetTodayWindowWeekly: "주간 한도",
        .rateLimitResetTodayWindows: "한도 창",
        .rateLimitResetTodayYes: "예",
        .rateLimitResetTodayYesHint: "한도가 오늘 리셋되었습니다",
        .rateLimitResetTodayYesHintWithTime: "오늘 리셋됨 · %@",
        .rateLimitResetTodayYesHintScheduled: "전체 리셋이 오늘 늦게 예정되어 있으며 아직 완료되지 않았습니다",
        .rateLimitResetTodayYesHintScheduledWithTime: "오늘 예정·미완료 · %@",
        .rateLimitResetTodayPercentPrefix: "≥%@%%",
        .rateLimitResetTodayPercentExact: "%@%%",
        .rateLimitResetTodayClockLocal: "현지 시간",
        .rateLimitResetTodayConfirmedWhen: "%@ (%@ 전)",
        .rateLimitResetTodayConfirmedHint:
            "오늘 완료된 {type}이(가) 확인되었습니다. 신뢰도는 약 {percent}입니다. {zone} 리셋 시각: {when}",
        .rateLimitResetTodayConfirmedHintNoPercent:
            "오늘 완료된 {type}이(가) 확인되었습니다. {zone} 리셋 시각: {when}",
        .rateLimitResetTodayScheduledChanceHint:
            "약 {percent} 확률로 {type}이(가) 진행됩니다. 현재 예정되어 있습니다. 대략적인 리셋 구간({zone}): {date}",
        .rateLimitResetUpcomingAlertBody1h: "예정된 Codex 리셋까지 1시간도 남지 않았습니다.",
        .rateLimitResetUpcomingAlertBody30m: "예정된 Codex 리셋까지 30분도 남지 않았습니다.",
        .rateLimitResetUpcomingRangeAlertBody: "예상 리셋 창: %@.",
        .rateLimitResetUpcomingRangeAlertTitle: "예상 Codex 리셋 창",
        .rateLimitResetUpcomingAlertTitle: "Codex 리셋이 다가옵니다",
        .rateLimitResetUpcomingTypedAlertTitle: "Codex %@이(가) 다가옵니다",
        .rateLimitResetUpcomingTypedRangeAlertTitle: "예상 Codex %@ 시간 범위",
        .recent: "최근",
        .recentSessionsDescription: "켜면 로컬 세션을 스캔합니다.",
        .refresh: "새로고침",
        .refreshInterval: "새로고침 간격",
        .rebuilt: "재구성됨",
        .repair: "복구",
        .repairConfirmMessage: "CodexRunway는 로컬 세션 파일에서 ~/.codex/session_index.jsonl을 다시 만듭니다. 쓰기 전에 인덱스 옆에 타임스탬프 백업이 생성됩니다. 세션 로그, auth.json, 전역 상태는 수정되지 않습니다.",
        .repairConfirmTitle: "Codex 세션 인덱스를 복구할까요?",
        .repairFailed: "복구 실패",
        .repairIndex: "인덱스 복구",
        .resetsIn: "리셋까지",
        .resetCredits: "리셋 크레딧",
        .resetCreditAlertBody: "리셋 크레딧이 곧 만료됩니다.",
        .resetCreditAlertTitle: "리셋 크레딧 만료 임박",
        .resetCreditAlertsDescription: "사용 가능한 리셋 크레딧이 7일 이내에 만료되면 알립니다.",
        .resetCreditAlerts: "리셋 크레딧 알림",
        .resetCreditDetails: "리셋 크레딧 상세",
        .restoreDefaultOrder: "기본 순서 복원",
        .runway: "Runway",
        .seconds: "초",
        .sessionRepair: "세션 복구",
        .sessionScanFailed: "세션 스캔 실패",
        .recentSessions: "최근 세션",
        .settings: "설정",
        .selfCheck: "자가 진단",
        .showDetails: "세부 정보 보기",
        .showCostSummary: "API 비용 요약 표시",
        .showModelSpecificQuotaUsage: "모델별 할당량 사용량 표시",
        .showRateLimitResetToday: "오늘 리셋 상태 표시",
        .showRecentSessions: "최근 세션 표시",
        .showSessionRepairSummary: "세션 복구 요약 표시",
        .showTokenUsageHeatmap: "토큰 사용량 표시",
        .mainPanelModules: "메인 패널 모듈",
        .mainPanelModulesDescription: "표시할 모듈을 선택하고 순서를 정하세요. 숨긴 모듈도 위치는 유지됩니다.",
        .moduleAPICostDescription: "로컬 세션의 API 환산 비용 추정.",
        .moduleAppliesCodex: "Codex",
        .moduleAppliesBoth: "Codex & Grok",
        .moduleHidden: "숨김",
        .moduleQuotaDescription: "할당량 미터와 모델별 한도.",
        .moduleQuotaEstimateDescription: "사용 이력으로 이번 주 한도를 추정해 공식 삭감 여부를 확인합니다.",
        .moduleResetCreditsDescription: "사용 가능한 리셋 크레딧과 만료 정보.",
        .moduleSessionRepairDescription: "로컬 세션 인덱스 상태와 복구 도구.",
        .moduleVisible: "표시",
        .notificationSettings: "알림",
        .tokenUsageHeatmap: "토큰 사용량",
        .tokenUsageHeatmapDescription: "연초부터의 토큰 사용량 차트(히트맵, 꺾은선 또는 막대).",
        .tokenUsageHeatmapUnavailable: "토큰 사용량을 일시적으로 사용할 수 없습니다",
        .tokenUsageChartStyle: "차트 스타일",
        .tokenUsageChartHeatmap: "히트맵",
        .tokenUsageChartLine: "꺾은선",
        .tokenUsageChartBar: "막대",
        .heatmapDaily: "일간",
        .heatmapWeekly: "주간",
        .heatmapCumulative: "합계",
        .heatmapMonthly: "월간",
        .heatmapEmpty: "올해 아직 토큰 사용량이 없습니다",
        .heatmapAllDevices: "공식 통계(모든 기기)",
        .heatmapLocalDevice: "로컬 로그(모든 세션)",
        .heatmapLocalShort: "로컬",
        .heatmapOfficialAsOf: "공식 집계일 %@",
        .heatmapSourceDisclosure: "공식 통계는 지연되거나 수정될 수 있습니다. 로컬 로그는 이 Mac에서 보이는 모든 세션을 포함하며 여러 계정에 걸칠 수 있습니다. 일별 데이터에는 UTC 날짜를 사용합니다.",
        .heatmapSourceMismatch: "출처가 다릅니다. 포함 관계로 비교할 수 없습니다.",
        .sourceLocalSessions: "로컬 세션",
        .sourceOnlineSupplement: "온라인 보완",
        .staleTitles: "오래된 제목",
        .status: "상태",
        .subscriptionExpired: "만료됨",
        .subscriptionExpires: "유효 기한",
        .subscriptionExpiringSoon: "곧 만료",
        .statusAvailable: "사용 가능",
        .statusError: "오류",
        .statusLogin: "로그인",
        .statusBarBattery: "카운트다운이 있는 배터리",
        .statusBarBatteryDetailCountdown: "리셋 카운트다운",
        .statusBarBatteryDetailRemainingPercent: "남은 비율",
        .statusBarBatteryDetailStyle: "배터리 중앙 텍스트",
        .statusBarBatteryScope: "배터리 할당량",
        .statusBarBatteryScopeBoth: "모두 표시",
        .statusBarBatteryScopeFiveHour: "5시간",
        .statusBarBatteryScopeWeekly: "주간",
        .statusBarCountdown: "카운트다운",
        .statusBarMetersDetailResetTime: "리셋 시각",
        .statusBarMetersDetailRemainingPercent: "남은 비율",
        .statusBarMetersDetailBoth: "둘 다",
        .statusBarMetersDetailStyle: "할당량 막대 상세",
        .statusBarMeters: "할당량 막대",
        .statusBarProviderScope: "상태 막대 플랫폼",
        .statusBarProviderScopeBoth: "Codex + Grok",
        .statusBarProviderScopeSelected: "현재 패널 따르기",
        .statusBarRings: "할당량 링",
        .statusBarStyle: "메뉴 막대 스타일",
        .statusBarText: "진행 텍스트",
        .statusUsed: "사용됨",
        .statusWait: "대기",
        .statusUnknown: "알 수 없음",
        .startDate: "시작일",
        .updateAvailable: "업데이트 가능",
        .updateCheckFailed: "업데이트 확인 실패",
        .updateChecking: "업데이트 확인 중...",
        .updateDownloadAndInstall: "다운로드 및 설치",
        .updateDownloadedReady: "CodexRunway %@이(가) 다운로드되어 설치할 준비가 되었습니다.",
        .updateDownloading: "업데이트 다운로드 중...",
        .updateExtracting: "업데이트 압축 해제 중...",
        .updateInstallAndRelaunch: "설치하고 다시 실행",
        .updateInstallLater: "나중에",
        .updateInstalled: "업데이트 설치됨",
        .updateInstalledMessage: "CodexRunway가 업데이트되었습니다.",
        .updateInstalling: "업데이트 설치 중...",
        .updateLearnMore: "자세히 알아보기",
        .updateNetworkProxyHint: "시스템 프록시를 사용하는 경우 github.com과 release-assets.githubusercontent.com이 시스템 프록시 우회 목록에 없는지 확인하거나 TUN 모드를 사용하세요.",
        .updateReadyToInstall: "설치 준비됨",
        .updateSigningKeyMissing: "Sparkle 서명 키가 구성되지 않았습니다.",
        .updateSkipVersion: "이 버전 건너뛰기",
        .updateUnavailableInDevelopment: "swift run으로 실행 중에는 업데이트를 설치할 수 없습니다. Sparkle 업데이트를 테스트하려면 패키징된 .app 또는 Release 빌드를 사용하세요.",
        .updateVersionAvailable: "CodexRunway %@을(를) 사용할 수 있습니다.",
        .upToDate: "CodexRunway는 최신 상태입니다.",
        .total: "합계",
        .totalRemaining: "남은 합계",
        .tokens: "Tokens",
        .tokensOnly: "토큰만",
        .testNotification: "테스트 알림",
        .testNotificationBody: "CodexRunway 알림이 정상적으로 표시됩니다.",
        .testNotificationDevelopmentMode: "시스템 알림은 패키징된 CodexRunway.app을 실행해야 합니다. swift run에서는 테스트할 수 없습니다.",
        .testNotificationSubtitle: "macOS 알림 권한을 요청하고 테스트 알림을 보냅니다.",
        .testNotificationTitle: "CodexRunway 테스트",
        .threads: "스레드",
        .today: "오늘",
        .thisMonth: "이번 달",
        .turns: "턴",
        .unknown: "알 수 없음",
        .unknownAccount: "알 수 없는 계정",
        .unknownModels: "알 수 없는 모델",
        .unavailableCredits: "사용 불가",
        .usageAnalyticsUnavailable: "사용량 분석을 사용할 수 없음",
        .usageAnalyticsEmpty: "이 범위에 사용량이 없습니다",
        .used: "사용됨",
        .usdPerCredit: "크레딧당 USD",
        .version: "버전",
        .weeklyValueEstimate: "주간 가치 추정",
        .weeklyUsage: "주간",
        .widgetAllDevices: "모든 기기",
        .widgetBalance: "잔액",
        .widgetCost: "API 환산",
        .widgetDataCorrupt: "위젯 데이터가 손상되었습니다. CodexRunway를 새로고침하세요.",
        .widgetDataOld: "데이터가 오래됨",
        .widgetMetricTitle: "핵심 지표",
        .widgetNoData: "위젯 데이터를 불러오려면 CodexRunway를 여세요.",
        .widgetOverviewTitle: "할당량 개요",
        .widgetRefreshInterval: "데스크톱 위젯 새로고침",
        .widgetRefreshIntervalDescription: "CodexRunway는 실행 중 이 간격으로 업데이트를 요청합니다. 실제 표시 시점은 macOS가 결정합니다.",
        .widgetRemaining: "남음",
        .widgetResetCredits: "리셋",
        .widgetResetTodayTitle: "오늘 리셋",
        .widgetThisMac: "이 Mac",
        .widgetTokenTrendTitle: "토큰 추세",
        .widgetUpdated: "업데이트됨",
        .widgetVersionUnsupported: "이 위젯 데이터를 읽으려면 CodexRunway를 업데이트하세요.",
        .languageTraditionalChinese: "중국어 번체",
        .languageKorean: "한국어",
        .languageJapanese: "일본어",
        .languageRussian: "러시아어",
        .languageFrench: "프랑스어",
    ]
}
