extension L10n {
    static let en: [L10nKey: String] = [
        .apiCost: "API Equivalent Cost",
        .apiCostSummaryRange: "API cost range",
        .apiCostSource: "Cost source",
        .apiEquivalent: "API equivalent",
        .apiTokenPricing: "API token pricing",
        .appearance: "Appearance",
        .appearanceDark: "Dark",
        .appearanceLight: "Light",
        .appearanceSystem: "System",
        .auto: "Auto",
        .about: "About",
        .advanced: "Advanced",
        .account: "Account",
        .accounts: "Accounts",
        .accountsAdd: "Add Account",
        .accountsAddAPIKey: "API Key",
        .accountsAddFile: "Import Files",
        .accountsAddLocal: "Import Local auth.json",
        .accountsAddOAuth: "Sign in with Browser",
        .accountsAddPaste: "Paste Token / JSON",
        .accountsAPIKeyHint: "Paste an OpenAI API key. API accounts do not show ChatGPT quota meters.",
        .accountsCurrent: "Current",
        .accountsDelete: "Remove",
        .accountsDeleteConfirmMessage: "Remove this account from Codex Runway? Official Codex login is unchanged unless it is the current account.",
        .accountsDeleteConfirmTitle: "Remove account?",
        .accountsDeselectAll: "Deselect All",
        .accountsEmpty: "No managed accounts yet. Import the local auth file or add another account.",
        .accountsExport: "Export",
        .accountsExportEmpty: "No accounts to export.",
        .accountsExportFailed: "Export failed",
        .accountsExportHint: "Choose which accounts to export for the current platform. The file can be imported on another Mac running Codex Runway.",
        .accountsExportSucceeded: "Exported %d account(s)",
        .accountsExportTitle: "Export Accounts",
        .accountsExportWarning: "The export file contains login credentials. Store and transfer it securely.",
        .accountsImportFailed: "Import failed",
        .accountsImportNoCredentials: "No credentials found. Paste auth.json, a refresh token, or a ChatGPT /auth/session JSON (accessToken).",
        .accountsImportPreviewHint: "Review the accounts found in the selected file(s). Uncheck any you do not want to import.",
        .accountsImportPreviewTitle: "Import Accounts",
        .accountsImportProgress: "Importing %d / %d",
        .accountsImportProviderNotice: "Imported into %@ accounts",
        .accountsImportSelected: "Import Selected",
        .accountsImportSucceeded: "Imported %d account(s)",
        .accountsImportWillAdd: "Will add",
        .accountsImportWillUpdate: "Will update",
        .accountsIsCurrentLogin: "This is the current Codex login account",
        .accountsMakeCurrent: "Use in Codex",
        .accountsMoveDown: "Move Down",
        .accountsMoveUp: "Move Up",
        .accountsNeedsReauth: "Needs re-auth",
        .accountsNote: "Note",
        .accountsOAuthCancelled: "Browser sign-in was cancelled.",
        .accountsOAuthFailed: "Browser sign-in failed",
        .accountsOAuthWaiting: "Complete sign-in in the browser…",
        .accountsPasteFromClipboard: "Paste from Clipboard",
        .accountsPasteHint: "Paste a refresh token, ~/.codex/auth.json, ChatGPT /api/auth/session JSON, or a JSON array of accounts.",
        .accountsRefreshAll: "Refresh All Quotas",
        .accountsReauthRequired: "Sign in again",
        .accountsRestartCodexAfterSwitch: "Restart Codex immediately after switching",
        .accountsRestartCodexFailed: "Account switched, but Codex could not be restarted: %@",
        .accountsRestartCodexSucceeded: "Account switched. Codex was restarted.",
        .accountsSelectAll: "Select All",
        .accountsSidebarTitle: "Accounts",
        .accountsSwitchConfirmTitle: "Switch account?",
        .accountsSwitchConfirmMessage: "Replace ~/.codex/auth.json with “%@”. Codex picks this up after a restart.",
        .accountsSwitchFailed: "Could not switch account",
        .accountsSwitchInvalidCredential: "This account’s credentials are invalid or incomplete, so they cannot be used as the Codex login.",
        .accountsSwitchMissingRefresh: "This account has no refresh_token. While the access token is still valid you can switch; once it expires, re-import the session or use browser sign-in.",
        .accountsSwitchSessionExpired: "This session access token has expired and there is no refresh_token. Re-import from /auth/session or sign in with the browser.",
        .accountsSwitching: "Switching account…",
        .accountsSwitchRealHint: "Switching writes the selected account to ~/.codex/auth.json so Codex CLI and IDE use it.",
        .alias: "Alias",
        .automaticallyCheckForUpdates: "Automatically check for updates",
        .available: "Available",
        .availableResets: "available resets",
        .back: "Back",
        .backup: "Backup",
        .cachedInput: "Cached input",
        .cachedInputTokens: "Cached input tokens",
        .cancel: "Cancel",
        .calculate: "Calculate",
        .calculating: "Calculating",
        .codexFolder: "Open Codex Folder",
        .controlPanel: "Control Panel",
        .calculatedAt: "Calculated",
        .costShare: "Cost share",
        .costScanFailed: "Cost scan failed",
        .costScanPreparing: "Preparing usage scan…",
        .costScanIndexing: "Indexing session logs…",
        .costScanAggregating: "Aggregating usage…",
        .costScanFetchingOnline: "Fetching online usage…",
        .costScanProgressFiles: "%d / %d files",
        .credit: "Credit",
        .creditsBalance: "Credits balance",
        .creditsUsed: "Credits used",
        .currentCycle: "Current cycle",
        .currentCycleAmount: "Current cycle amount",
        .customRange: "Custom",
        .customRangePrompt: "Select a date range, then click Calculate",
        .cycleStarted: "Started",
        .date: "Date",
        .burnRate: "Burn rate",
        .duplicate: "duplicate",
        .duplicateIndexIDs: "Duplicate index IDs",
        .display: "Display",
        .endDate: "End date",
        .estimatedAPICost: "Estimated API cost",
        .expiresRemaining: "Validity remaining",
        .expiresAt: "Expires",
        .expiryRisk: "Expiry risk",
        .expiringSoon: "Expiring soon",
        .exhaustsIn: "Exhausts in",
        .error: "Error",
        .exportStatusJSON: "Export local status JSON",
        .failed: "Failed",
        .checkForUpdates: "Check for Updates",
        .fiveHourUsage: "5-hour",
        .general: "General",
        .grokAccountsAddFile: "Import Files",
        .grokAccountsAddOAuth: "Sign in to a New Grok Account",
        .grokAccountsAddPaste: "Paste Token / JSON",
        .grokAccountsCurrent: "Current Grok account",
        .grokAccountsDeleteConfirmMessage: "Remove this account from Codex Runway? The official Grok login is not changed.",
        .grokAccountsDeleteConfirmTitle: "Remove Grok account?",
        .grokAccountsEmpty: "No managed Grok accounts yet. Sign in, import the current Grok login, or paste credentials.",
        .grokAccountsImportNoCredentials: "No credentials found. Paste ~/.grok/auth.json or a Grok credential object (key/refresh_token plus email, user_id, or principal_id).",
        .grokAccountsImportOfficial: "Import Current Grok Login",
        .grokAccountsMakeCurrent: "Use in Grok",
        .grokAccountsPasteHint: "Paste ~/.grok/auth.json, a single Grok OAuth/legacy credential object, or a JSON array of accounts. API-key-only credentials are not supported.",
        .grokAccountsRefreshAll: "Refresh All Grok Quotas",
        .grokAccountsRemove: "Remove Grok Account",
        .grokAccountsTitle: "Grok Accounts",
        .grokBillingParseFailed: "Grok returned an unsupported billing response. Update the CLI or try again later.",
        .grokBillingPeriod: "Billing period",
        .grokBillingPeriodMonthly: "Monthly included quota",
        .grokBillingPeriodWeekly: "Weekly included quota",
        .grokCLIInstallHint: "Install the official Grok CLI, then sign in with OAuth to view billing.",
        .grokCLIOpenInstallGuide: "Open Grok CLI installation guide",
        .grokCLITooOld: "This Grok CLI version does not support billing. Update the CLI and try again.",
        .grokCLIUnavailable: "Grok CLI is not installed",
        .grokCurrentAccountCannotDelete: "Switch to another Grok account before removing the current account.",
        .grokDataSource: "Data source",
        .grokExternalLoginChanged: "The Grok login was changed by another process. Account state was synchronized from the official credentials.",
        .grokImportFailed: "Could not import the current Grok login",
        .grokImportSucceeded: "Current Grok login imported",
        .grokIncludedQuota: "Included quota",
        .grokIncludedUSD: "Included USD credit",
        .grokLocalUsage: "Local token usage",
        .grokLocalUsageHint: "From recent Grok CLI sessions on this Mac (turn_completed usage).",
        .grokLoginCancelled: "Grok sign-in was cancelled.",
        .grokLoginFailed: "Grok sign-in failed",
        .grokLoginWaiting: "Complete Grok sign-in in the browser (device code page opens automatically)…",
        .grokNoManagedOAuth: "No manageable OAuth or compatible legacy Grok login was found.",
        .grokNoQuotaData: "No Grok billing data is available yet.",
        .grokNotLoggedIn: "Grok is not signed in",
        .grokOnDemandLimit: "On-demand limit",
        .grokOnDemandUsage: "On-demand usage",
        .grokPlan: "Grok plan",
        .grokPrepaidBalance: "Prepaid balance",
        .grokProductBuild: "Grok Build",
        .grokProductChat: "Grok Chat",
        .grokProductImagine: "Grok Imagine",
        .grokProductUsage: "Product usage",
        .grokReauthenticationRequired: "Grok sign-in has expired. Sign in again.",
        .grokRefreshFailed: "Could not refresh Grok billing",
        .grokRefreshCancelled: "Grok billing refresh was cancelled.",
        .grokRefreshTimedOut: "Grok billing request timed out.",
        .grokRefreshing: "Refreshing Grok billing…",
        .grokResetAt: "Resets",
        .grokSessionsScanned: "%d sessions scanned",
        .grokSourceCLI: "Grok CLI billing API",
        .grokSourceLocalSessions: "Local Grok sessions",
        .grokSwitchConfirmMessage: "Replace the official Grok OAuth login with “%@”? Only new Grok sessions are guaranteed to use it.",
        .grokSwitchConfirmTitle: "Switch Grok account?",
        .grokSwitchFailed: "Could not switch Grok account",
        .grokSwitchOnlyNewSessions: "Account switching only affects new Grok sessions.",
        .grokSwitchRunningMessage: "One or more Grok processes are still running. They may write the previous login back after this switch. Continuing only guarantees that new Grok sessions use the selected account.",
        .grokSwitchRunningTitle: "Grok is running",
        .grokSwitching: "Switching Grok account…",
        .grokUnifiedBilling: "Unified billing",
        .grokUpdatedAt: "Grok billing updated",
        .hours: "hours",
        .modelBreakdown: "Model breakdown",
        .modelSpecificQuotaUsageDescription: "Show separate model-specific quota progress in the menu bar and main panel.",
        .noModelCostData: "No model cost data",
        .nonCachedInput: "Non-cached input",
        .inputShort: "in",
        .inputCachedOutput: "Input / cached / output",
        .inputTokens: "Input tokens",
        .invalidDateRange: "Invalid date range",
        .language: "Language",
        .languageEnglish: "English",
        .languageSimplifiedChinese: "Simplified Chinese",
        .lastReset: "Last reset",
        .lastUpdated: "Updated",
        .later: "later",
        .left: "left",
        .minutes: "minutes",
        .missing: "missing",
        .missingFromIndex: "Missing from index",
        .nextResetIn: "Next reset: ",
        .nextExpiry: "Next expiry",
        .needsAttention: "Needs attention",
        .noExpiry: "no expiry",
        .noAvailableResetCredits: "No reset credits",
        .notLoggedIn: "Not logged in",
        .authExpired: "Login expired. Sign in again or switch to an account that has a valid refresh_token.",
        .authFileInvalid: "Local auth.json is invalid or incomplete. Restore a usable account or sign in again.",
        .noPreviousIndex: "no previous index",
        .notLoaded: "Not loaded",
        .notScanned: "Not scanned",
        .ok: "OK",
        .openControlPanel: "Open Control Panel",
        .openDetailsWindow: "Open Details Window",
        .orphan: "orphan",
        .orphanIndexRows: "Orphan index rows",
        .outputTokens: "Output tokens",
        .outputShort: "out",
        .openGithub: "Open GitHub",
        .tokenComposition: "Token composition",
        .feedbackIssue: "Feedback",
        .historicalUsage: "Historical usage",
        .privacy: "Tokens stay on this Mac. Session repair only rewrites the local index after creating a backup.",
        .plan: "Plan",
        .planAPI: "API",
        .planBusiness: "Business",
        .planEdu: "Edu",
        .planEnterprise: "Enterprise",
        .planFree: "Free",
        .planPlus: "Plus",
        .planPro5x: "Pro 5X",
        .planPro20x: "Pro 20X",
        .planTeam: "Team",
        .planUnknown: "Unknown",
        .plannedEntries: "Planned entries",
        .pricingVersion: "Pricing version",
        .projectBreakdown: "Project breakdown",
        .projectedAtReset: "Projected at reset",
        .projectedWeeklyTotal: "Projected weekly total",
        .previousCycle: "Previous cycle",
        .providerCodex: "Codex",
        .providerGrok: "Grok",
        .quota: "Quota",
        .quotaAlertBody: "%@ has reached %@ usage.",
        .quotaAlertTitle: "Codex quota alert",
        .quotaAlertsDescription: "Alerts when usage reaches 80%, 95%, or 100%.",
        .quotaAlerts: "Quota alerts",
        .quit: "Quit",
        .rawAnalyticsCredits: "Raw analytics credits",
        .rateLimitResetDetectedAlertBody: "A Codex quota reset was just detected for today.",
        .rateLimitResetDetectedAlertTitle: "Codex reset detected",
        .rateLimitResetToday: "Reset today?",
        .rateLimitResetTodayAlerts: "Reset-today alerts",
        .rateLimitResetTodayAlertsDescription: "Notify when a reset is newly detected, and when a scheduled reset is within 1 hour or 30 minutes.",
        .rateLimitResetTodayAwaiting: "No reset completed or scheduled for today",
        .rateLimitResetTodayCheckCost: "Check cost",
        .rateLimitResetTodayConfidence: "Confidence",
        .rateLimitResetTodayDescription: "Public status from www.codexrunway.com.",
        .rateLimitResetTodayEvidenceBankedReset: "A banked reset was announced; this is not a completed reset.",
        .rateLimitResetTodayEvidenceLimitIncrease: "A quota limit increase was announced; this is not a reset.",
        .rateLimitResetTodayEvidenceResetCompleted: "An explicit Codex quota reset was announced.",
        .rateLimitResetTodayEvidenceResetScheduled: "An explicit Codex quota reset was scheduled.",
        .rateLimitResetTodayEvidenceUncertain: "Not a clear reset signal.",
        .rateLimitResetTodayLastCheck: "Last check",
        .rateLimitResetTodayLastFetched: "Last refreshed",
        .rateLimitResetTodayLocalDayHint: "Uses your local calendar day and changes at midnight.",
        .rateLimitResetTodayLatestEvidence: "Latest evidence",
        .rateLimitResetTodayNextScheduled: "Next scheduled",
        .rateLimitResetTodayNextScheduledWithCountdown: "Next scheduled: %@ (%@)",
        .rateLimitResetTodayNo: "No",
        .rateLimitResetTodayNoHint: "No reset completed or scheduled for today",
        .rateLimitResetTodayNoHintUncertain: "No clear reset signal for today",
        .rateLimitResetTodayNoHintWithNext: "No reset for today · next %@",
        .rateLimitResetTodayOpenSource: "Open status page",
        .rateLimitResetTodayOpenEvidence: "Open X source",
        .rateLimitResetTodayResetAgo: "Reset %@ ago",
        .rateLimitResetTodayUntilReset: "%@ until reset",
        .rateLimitResetTodayPlanAll: "All plans",
        .rateLimitResetTodayPlanBusiness: "Business",
        .rateLimitResetTodayPlanEnterprise: "Enterprise",
        .rateLimitResetTodayPlanFree: "Free",
        .rateLimitResetTodayPlanPlus: "Plus",
        .rateLimitResetTodayPlanPro: "Pro",
        .rateLimitResetTodayPlanTeam: "Team",
        .rateLimitResetTodayPlanUnknown: "Plan not specified",
        .rateLimitResetTodayPlans: "Plans",
        .rateLimitResetTodayRefreshInterval: "Reset status refresh",
        .rateLimitResetTodaySeen: "Seen",
        .rateLimitResetTodaySource: "Codex Runway reset status",
        .rateLimitResetTodaySourceInfo: "Codex Runway publishes this status from a hosted monitor that uses AI to analyze public X announcements. AI results may be incomplete or incorrect.",
        .rateLimitResetTodaySourceTitle: "Data source",
        .rateLimitResetTodayUnknown: "—",
        .rateLimitResetTodayUnknownHint: "Status is unavailable or stale",
        .rateLimitResetTodayVerdict: "Verdict",
        .rateLimitResetTodayWindowFiveHour: "5-hour window",
        .rateLimitResetTodayWindowUnknown: "Window not specified",
        .rateLimitResetTodayWindowWeekly: "Weekly limit",
        .rateLimitResetTodayWindows: "Limit window",
        .rateLimitResetTodayYes: "Yes",
        .rateLimitResetTodayYesHint: "Limits have reset today",
        .rateLimitResetTodayYesHintWithTime: "Reset today · %@",
        .rateLimitResetTodayYesHintScheduled: "Reset scheduled for later today",
        .rateLimitResetTodayYesHintScheduledWithTime: "Scheduled today · %@",
        .rateLimitResetUpcomingAlertBody1h: "A scheduled Codex reset is less than 1 hour away.",
        .rateLimitResetUpcomingAlertBody30m: "A scheduled Codex reset is less than 30 minutes away.",
        .rateLimitResetUpcomingAlertTitle: "Codex reset approaching",
        .recent: "Recent",
        .recentSessionsDescription: "Scans local sessions when enabled.",
        .refresh: "Refresh",
        .refreshInterval: "Refresh interval",
        .rebuilt: "Rebuilt",
        .repair: "Repair",
        .repairConfirmMessage: "Codex Runway will rebuild ~/.codex/session_index.jsonl from local session files. A timestamped backup will be created next to the index before writing. Session logs, auth.json, and global state are not modified.",
        .repairConfirmTitle: "Repair Codex session index?",
        .repairFailed: "Repair failed",
        .repairIndex: "Repair Index",
        .resetsIn: "resets in",
        .resetCredits: "Reset Credits",
        .resetCreditAlertBody: "A reset credit expires soon.",
        .resetCreditAlertTitle: "Reset credit expiring",
        .resetCreditAlertsDescription: "Alerts when an available reset credit expires within 7 days.",
        .resetCreditAlerts: "Reset credit alerts",
        .resetCreditDetails: "Reset credit details",
        .runway: "Runway",
        .seconds: "seconds",
        .sessionRepair: "Session Repair",
        .sessionScanFailed: "Session scan failed",
        .recentSessions: "Recent sessions",
        .settings: "Settings",
        .selfCheck: "Self Check",
        .showDetails: "Show Details",
        .showCostSummary: "Show API cost summary",
        .showModelSpecificQuotaUsage: "Show model-specific quota usage",
        .showRateLimitResetToday: "Show reset-today status",
        .showRecentSessions: "Show recent sessions",
        .showSessionRepairSummary: "Show session repair summary",
        .showTokenUsageHeatmap: "Show token usage",
        .tokenUsageHeatmap: "Token usage",
        .tokenUsageHeatmapDescription: "Year-to-date token usage chart under the quota section (heatmap, line, or bar).",
        .tokenUsageHeatmapUnavailable: "Token usage is temporarily unavailable",
        .tokenUsageChartStyle: "Chart style",
        .tokenUsageChartHeatmap: "Heatmap",
        .tokenUsageChartLine: "Line",
        .tokenUsageChartBar: "Bar",
        .heatmapDaily: "Daily",
        .heatmapWeekly: "Weekly",
        .heatmapCumulative: "Total",
        .heatmapMonthly: "Monthly",
        .heatmapEmpty: "No token usage this year yet",
        .heatmapAllDevices: "Official stats (all devices)",
        .heatmapLocalDevice: "Local logs (all sessions)",
        .heatmapLocalShort: "Local",
        .heatmapOfficialAsOf: "Official through %@",
        .heatmapSourceDisclosure: "Official stats may lag or be revised. Local logs include every session visible on this Mac and may span accounts.",
        .heatmapSourceMismatch: "Different sources; values are not a subset comparison.",
        .sourceLocalSessions: "Local sessions",
        .sourceOnlineSupplement: "Online supplement",
        .staleTitles: "Stale titles",
        .status: "Status",
        .subscriptionExpired: "Expired",
        .subscriptionExpires: "Valid until",
        .subscriptionExpiringSoon: "Expiring soon",
        .statusAvailable: "available",
        .statusError: "err",
        .statusLogin: "login",
        .statusBarBattery: "Battery with countdown",
        .statusBarBatteryDetailCountdown: "Reset countdown",
        .statusBarBatteryDetailRemainingPercent: "Remaining percent",
        .statusBarBatteryDetailStyle: "Battery center text",
        .statusBarBatteryScope: "Battery quota",
        .statusBarBatteryScopeBoth: "All visible",
        .statusBarBatteryScopeFiveHour: "5-hour",
        .statusBarBatteryScopeWeekly: "Weekly",
        .statusBarCountdown: "Countdown",
        .statusBarMetersDetailResetTime: "Reset time",
        .statusBarMetersDetailRemainingPercent: "Remaining percent",
        .statusBarMetersDetailBoth: "Both",
        .statusBarMetersDetailStyle: "Quota-bar detail",
        .statusBarMeters: "Quota bars",
        .statusBarProviderScope: "Status bar platforms",
        .statusBarProviderScopeBoth: "Codex + Grok",
        .statusBarProviderScopeSelected: "Follow current panel",
        .statusBarRings: "Quota rings",
        .statusBarStyle: "Menu bar style",
        .statusUsed: "used",
        .statusWait: "wait",
        .statusUnknown: "unknown",
        .startDate: "Start date",
        .updateAvailable: "Update available",
        .updateCheckFailed: "Update check failed",
        .updateChecking: "Checking for updates...",
        .updateDownloadAndInstall: "Download and Install",
        .updateDownloadedReady: "Codex Runway %@ has been downloaded and is ready to install.",
        .updateDownloading: "Downloading update...",
        .updateExtracting: "Extracting update...",
        .updateInstallAndRelaunch: "Install and Relaunch",
        .updateInstallLater: "Later",
        .updateInstalled: "Update installed",
        .updateInstalledMessage: "Codex Runway is now updated.",
        .updateInstalling: "Installing update...",
        .updateLearnMore: "Learn More",
        .updateNetworkProxyHint: "If you use a system proxy, make sure github.com and release-assets.githubusercontent.com are not in the system proxy bypass list, or use TUN mode.",
        .updateReadyToInstall: "Ready to Install",
        .updateSigningKeyMissing: "Sparkle signing key is not configured.",
        .updateSkipVersion: "Skip This Version",
        .updateUnavailableInDevelopment: "Updates cannot be installed when running with swift run. Use a packaged .app or Release build to test Sparkle updates.",
        .updateVersionAvailable: "Codex Runway %@ is available.",
        .upToDate: "Codex Runway is up to date.",
        .total: "Total",
        .totalRemaining: "Total remaining",
        .tokens: "Tokens",
        .tokensOnly: "tokens only",
        .testNotification: "Test Notification",
        .testNotificationBody: "Notifications are working for Codex Runway.",
        .testNotificationDevelopmentMode: "System notifications require running the packaged CodexRunway.app. They cannot be tested from swift run.",
        .testNotificationSubtitle: "Requests macOS notification permission and sends a test alert.",
        .testNotificationTitle: "Codex Runway test",
        .threads: "threads",
        .today: "Today",
        .thisMonth: "This month",
        .turns: "turns",
        .unknown: "unknown",
        .unknownAccount: "Unknown account",
        .unknownModels: "Unknown models",
        .unavailableCredits: "Unavailable",
        .usageAnalyticsUnavailable: "Usage analytics unavailable",
        .usageAnalyticsEmpty: "No usage in this range",
        .used: "used",
        .usdPerCredit: "USD per credit",
        .version: "Version",
        .weeklyValueEstimate: "Weekly value estimate",
        .weeklyUsage: "Weekly",
        .widgetAllDevices: "All devices",
        .widgetBalance: "Balance",
        .widgetCost: "API equivalent",
        .widgetDataCorrupt: "Widget data is damaged. Refresh Codex Runway.",
        .widgetDataOld: "Data is old",
        .widgetMetricTitle: "Key Metric",
        .widgetNoData: "Open Codex Runway to load widget data.",
        .widgetOverviewTitle: "Quota Overview",
        .widgetRemaining: "Remaining",
        .widgetResetCredits: "Resets",
        .widgetResetTodayTitle: "Reset Today",
        .widgetThisMac: "This Mac",
        .widgetTokenTrendTitle: "Token Trend",
        .widgetUpdated: "Updated",
        .widgetVersionUnsupported: "Update Codex Runway to read this widget data.",
    ]

    static let zhHans: [L10nKey: String] = [
        .apiCost: "API 等价成本",
        .apiCostSummaryRange: "API 成本范围",
        .apiCostSource: "成本来源",
        .apiEquivalent: "API 等价",
        .apiTokenPricing: "API token 价格",
        .appearance: "外观",
        .appearanceDark: "深色",
        .appearanceLight: "浅色",
        .appearanceSystem: "跟随系统",
        .auto: "自动",
        .about: "关于",
        .advanced: "高级",
        .account: "账号",
        .accounts: "多账号",
        .accountsAdd: "添加账号",
        .accountsAddAPIKey: "API Key",
        .accountsAddFile: "导入文件",
        .accountsAddLocal: "导入本机 auth.json",
        .accountsAddOAuth: "浏览器登录",
        .accountsAddPaste: "粘贴 Token / JSON",
        .accountsAPIKeyHint: "粘贴 OpenAI API Key。API 账号不会显示 ChatGPT 额度进度条。",
        .accountsCurrent: "当前",
        .accountsDelete: "移除",
        .accountsDeleteConfirmMessage: "从 Codex Runway 移除此账号？除非它是当前账号，否则不会改动官方 Codex 登录。",
        .accountsDeleteConfirmTitle: "移除账号？",
        .accountsDeselectAll: "取消全选",
        .accountsEmpty: "还没有托管账号。请先导入本机 auth.json，或添加其他账号。",
        .accountsExport: "导出",
        .accountsExportEmpty: "没有可导出的账号。",
        .accountsExportFailed: "导出失败",
        .accountsExportHint: "选择要导出的当前平台账号。导出文件可在另一台 Mac 的 Codex Runway 中导入。",
        .accountsExportSucceeded: "已导出 %d 个账号",
        .accountsExportTitle: "导出账号",
        .accountsExportWarning: "导出文件包含登录凭据，请妥善保管与传输。",
        .accountsImportFailed: "导入失败",
        .accountsImportNoCredentials: "未识别到凭据。请粘贴 auth.json、refresh token，或 ChatGPT /auth/session 的 JSON（含 accessToken）。",
        .accountsImportPreviewHint: "以下是从所选文件解析到的账号，可取消勾选不需要导入的项。",
        .accountsImportPreviewTitle: "导入账号",
        .accountsImportProgress: "正在导入 %d / %d",
        .accountsImportProviderNotice: "已导入到 %@ 账号库",
        .accountsImportSelected: "导入选中",
        .accountsImportSucceeded: "已导入 %d 个账号",
        .accountsImportWillAdd: "将新增",
        .accountsImportWillUpdate: "将更新",
        .accountsIsCurrentLogin: "为当前 Codex 的登录账户",
        .accountsMakeCurrent: "设为当前",
        .accountsMoveDown: "下移",
        .accountsMoveUp: "上移",
        .accountsNeedsReauth: "需要重新登录",
        .accountsNote: "备注",
        .accountsOAuthCancelled: "已取消浏览器登录。",
        .accountsOAuthFailed: "浏览器登录失败",
        .accountsOAuthWaiting: "请在浏览器中完成登录…",
        .accountsPasteFromClipboard: "从剪贴板粘贴",
        .accountsPasteHint: "粘贴 refresh token、~/.codex/auth.json、ChatGPT /api/auth/session JSON，或账号 JSON 数组。",
        .accountsRefreshAll: "刷新全部额度",
        .accountsReauthRequired: "请重新登录",
        .accountsRestartCodexAfterSwitch: "切换后立即重启 Codex",
        .accountsRestartCodexFailed: "账号已切换，但重启 Codex 失败：%@",
        .accountsRestartCodexSucceeded: "账号已切换，并已重启 Codex。",
        .accountsSelectAll: "全选",
        .accountsSidebarTitle: "账号",
        .accountsSwitchConfirmTitle: "切换账号？",
        .accountsSwitchConfirmMessage: "将使用「%@」覆盖 ~/.codex/auth.json。需重启 Codex 后才会生效。",
        .accountsSwitchFailed: "切换账号失败",
        .accountsSwitchInvalidCredential: "该账号凭据无效或不完整，不能作为 Codex 登录账号。",
        .accountsSwitchMissingRefresh: "该账号没有 refresh_token。access_token 仍有效时可切换；过期后请重新导入 /auth/session 或使用浏览器登录。",
        .accountsSwitchSessionExpired: "该 session 的 access_token 已过期，且没有 refresh_token，无法切换。请重新从 /auth/session 导入，或使用浏览器登录。",
        .accountsSwitching: "正在切换账号…",
        .accountsSwitchRealHint: "切换会将选中账号写入 ~/.codex/auth.json，Codex CLI 与 IDE 会同步使用。",
        .alias: "别名",
        .automaticallyCheckForUpdates: "自动检查更新",
        .available: "可用",
        .availableResets: "可用重置",
        .back: "返回",
        .backup: "备份",
        .cachedInput: "缓存输入",
        .cachedInputTokens: "缓存输入 tokens",
        .cancel: "取消",
        .calculate: "计算",
        .calculating: "计算中",
        .codexFolder: "打开 Codex 文件夹",
        .controlPanel: "控制台",
        .calculatedAt: "计算于",
        .costShare: "成本占比",
        .costScanFailed: "费用扫描失败",
        .costScanPreparing: "正在准备用量扫描…",
        .costScanIndexing: "正在索引会话日志…",
        .costScanAggregating: "正在汇总用量…",
        .costScanFetchingOnline: "正在请求线上用量…",
        .costScanProgressFiles: "%d / %d 个文件",
        .credit: "次数",
        .creditsBalance: "Credits 余额",
        .creditsUsed: "已用 Credits",
        .currentCycle: "本周期",
        .currentCycleAmount: "本周期金额",
        .customRange: "自定义",
        .customRangePrompt: "请选择日期，然后点击计算",
        .cycleStarted: "始于",
        .date: "日期",
        .burnRate: "消耗速度",
        .duplicate: "重复",
        .duplicateIndexIDs: "重复索引 ID",
        .display: "显示",
        .endDate: "结束日期",
        .estimatedAPICost: "估算 API 成本",
        .expiresRemaining: "有效期剩余",
        .expiresAt: "到期时间",
        .expiryRisk: "到期风险",
        .expiringSoon: "即将过期",
        .exhaustsIn: "预计耗尽于",
        .error: "错误",
        .exportStatusJSON: "导出本地状态 JSON",
        .failed: "失败",
        .checkForUpdates: "检查更新",
        .fiveHourUsage: "5小时",
        .general: "通用",
        .grokAccountsAddFile: "导入文件",
        .grokAccountsAddOAuth: "登录新的 Grok 账号",
        .grokAccountsAddPaste: "粘贴 Token / JSON",
        .grokAccountsCurrent: "当前 Grok 账号",
        .grokAccountsDeleteConfirmMessage: "从 Codex Runway 移除此账号？官方 Grok 登录不会改变。",
        .grokAccountsDeleteConfirmTitle: "移除 Grok 账号？",
        .grokAccountsEmpty: "还没有托管的 Grok 账号。请登录、导入当前 Grok 登录，或粘贴凭据。",
        .grokAccountsImportNoCredentials: "未识别到凭据。请粘贴 ~/.grok/auth.json，或 Grok 凭据对象（含 key/refresh_token，以及 email、user_id 或 principal_id）。",
        .grokAccountsImportOfficial: "导入当前 Grok 登录",
        .grokAccountsMakeCurrent: "设为 Grok 当前账号",
        .grokAccountsPasteHint: "粘贴 ~/.grok/auth.json、单个 Grok OAuth/legacy 凭据对象，或账号 JSON 数组。仅含 API Key 的凭据不受支持。",
        .grokAccountsRefreshAll: "刷新全部 Grok 额度",
        .grokAccountsRemove: "移除 Grok 账号",
        .grokAccountsTitle: "Grok 账号",
        .grokBillingParseFailed: "Grok 返回了不支持的账单结构。请更新 CLI，或稍后重试。",
        .grokBillingPeriod: "账单周期",
        .grokBillingPeriodMonthly: "月度包含额度",
        .grokBillingPeriodWeekly: "周度包含额度",
        .grokCLIInstallHint: "请先安装官方 Grok CLI，再使用 OAuth 登录以查看额度。",
        .grokCLIOpenInstallGuide: "打开 Grok CLI 安装说明",
        .grokCLITooOld: "当前 Grok CLI 版本不支持账单查询。请更新 CLI 后重试。",
        .grokCLIUnavailable: "未安装 Grok CLI",
        .grokCurrentAccountCannotDelete: "请先切换到其他 Grok 账号，再移除当前账号。",
        .grokDataSource: "数据来源",
        .grokExternalLoginChanged: "Grok 登录已被其他进程改变，账号状态已按官方凭据同步。",
        .grokImportFailed: "导入当前 Grok 登录失败",
        .grokImportSucceeded: "已导入当前 Grok 登录",
        .grokIncludedQuota: "包含额度",
        .grokIncludedUSD: "包含美金额度",
        .grokLocalUsage: "本地 Token 用量",
        .grokLocalUsageHint: "来自本机最近 Grok CLI 会话（turn_completed 用量）。",
        .grokLoginCancelled: "已取消 Grok 登录。",
        .grokLoginFailed: "Grok 登录失败",
        .grokLoginWaiting: "请在浏览器中完成 Grok 登录（将自动打开设备授权页）…",
        .grokNoManagedOAuth: "没有找到可托管的 OAuth 或兼容 legacy Grok 登录。",
        .grokNoQuotaData: "暂无 Grok 额度数据。",
        .grokNotLoggedIn: "Grok 未登录",
        .grokOnDemandLimit: "按需使用上限",
        .grokOnDemandUsage: "按需使用",
        .grokPlan: "Grok 套餐",
        .grokPrepaidBalance: "预付余额",
        .grokProductBuild: "Grok Build",
        .grokProductChat: "Grok Chat",
        .grokProductImagine: "Grok Imagine",
        .grokProductUsage: "产品用量",
        .grokReauthenticationRequired: "Grok 登录已失效，请重新登录。",
        .grokRefreshFailed: "Grok 额度刷新失败",
        .grokRefreshCancelled: "已取消 Grok 额度刷新。",
        .grokRefreshTimedOut: "Grok 额度刷新超时。",
        .grokRefreshing: "正在刷新 Grok 额度…",
        .grokResetAt: "重置时间",
        .grokSessionsScanned: "已扫描 %d 个会话",
        .grokSourceCLI: "Grok CLI 账单 API",
        .grokSourceLocalSessions: "本地 Grok 会话",
        .grokSwitchConfirmMessage: "将官方 Grok OAuth 登录切换为「%@」？仅保证新的 Grok 会话使用该账号。",
        .grokSwitchConfirmTitle: "切换 Grok 账号？",
        .grokSwitchFailed: "Grok 账号切换失败",
        .grokSwitchOnlyNewSessions: "账号切换只影响新的 Grok 会话。",
        .grokSwitchRunningMessage: "检测到仍在运行的 Grok 进程。切换后，这些进程可能把旧登录重新写回；继续操作只保证新的 Grok 会话使用所选账号。",
        .grokSwitchRunningTitle: "Grok 正在运行",
        .grokSwitching: "正在切换 Grok 账号…",
        .grokUnifiedBilling: "统一计费",
        .grokUpdatedAt: "Grok 额度更新于",
        .hours: "小时",
        .modelBreakdown: "模型明细",
        .modelSpecificQuotaUsageDescription: "在菜单栏和主面板中显示特有模型的独立额度进度。",
        .noModelCostData: "暂无模型成本数据",
        .nonCachedInput: "非缓存输入",
        .inputShort: "输入",
        .inputCachedOutput: "输入 / 缓存 / 输出",
        .inputTokens: "输入 tokens",
        .invalidDateRange: "日期范围无效",
        .language: "语言",
        .languageEnglish: "英文",
        .languageSimplifiedChinese: "简体中文",
        .lastReset: "上次重置",
        .lastUpdated: "更新于",
        .later: "后",
        .left: "剩余",
        .minutes: "分钟",
        .missing: "缺失",
        .missingFromIndex: "索引缺失",
        .nextResetIn: "下次重置于：",
        .nextExpiry: "最近到期",
        .needsAttention: "需要处理",
        .noExpiry: "无到期时间",
        .noAvailableResetCredits: "无可用重置次数",
        .notLoggedIn: "未登录",
        .authExpired: "登录已失效。请重新登录，或切换到含有效 refresh_token 的账号。",
        .authFileInvalid: "本地 auth.json 无效或不完整。请恢复可用账号，或重新登录。",
        .noPreviousIndex: "没有旧索引",
        .notLoaded: "未加载",
        .notScanned: "未扫描",
        .ok: "好",
        .openControlPanel: "打开控制台",
        .openDetailsWindow: "打开详情窗口",
        .orphan: "孤立",
        .orphanIndexRows: "孤立索引行",
        .outputTokens: "输出 tokens",
        .outputShort: "输出",
        .openGithub: "打开 GitHub",
        .tokenComposition: "Tokens 组成",
        .feedbackIssue: "反馈建议",
        .historicalUsage: "历史记录",
        .privacy: "Token 只保留在本机。会话修复只会在创建备份后重建本地索引。",
        .plan: "套餐",
        .planAPI: "API",
        .planBusiness: "Business",
        .planEdu: "Edu",
        .planEnterprise: "Enterprise",
        .planFree: "Free",
        .planPlus: "Plus",
        .planPro5x: "Pro 5X",
        .planPro20x: "Pro 20X",
        .planTeam: "Team",
        .planUnknown: "Unknown",
        .plannedEntries: "计划写入条目",
        .pricingVersion: "价格版本",
        .projectBreakdown: "项目明细",
        .projectedAtReset: "重置时预计",
        .projectedWeeklyTotal: "推算周总额",
        .previousCycle: "上个周期",
        .providerCodex: "Codex",
        .providerGrok: "Grok",
        .quota: "配额",
        .quotaAlertBody: "%@ 已达到 %@ 用量。",
        .quotaAlertTitle: "Codex 配额提醒",
        .quotaAlertsDescription: "用量达到 80%、95% 或 100% 时提醒。",
        .quotaAlerts: "配额提醒",
        .quit: "退出",
        .rawAnalyticsCredits: "原始 analytics Credits",
        .rateLimitResetDetectedAlertBody: "刚刚检测到今日 Codex 配额已重置。",
        .rateLimitResetDetectedAlertTitle: "检测到 Codex 重置",
        .rateLimitResetToday: "今日是否重置",
        .rateLimitResetTodayAlerts: "重置提醒",
        .rateLimitResetTodayAlertsDescription: "新检测到重置时提醒；计划重置不足 1 小时或 30 分钟时也会提醒。",
        .rateLimitResetTodayAwaiting: "今日没有已完成或已排期的重置",
        .rateLimitResetTodayCheckCost: "检查成本",
        .rateLimitResetTodayConfidence: "置信度",
        .rateLimitResetTodayDescription: "数据来自 www.codexrunway.com。",
        .rateLimitResetTodayEvidenceBankedReset: "公告涉及 banked reset，不代表已完成重置。",
        .rateLimitResetTodayEvidenceLimitIncrease: "公告涉及提高配额，不代表发生重置。",
        .rateLimitResetTodayEvidenceResetCompleted: "发现明确的 Codex 配额重置公告。",
        .rateLimitResetTodayEvidenceResetScheduled: "发现明确的 Codex 配额重置安排。",
        .rateLimitResetTodayEvidenceUncertain: "不是明确的重置信号。",
        .rateLimitResetTodayLastCheck: "最近检查",
        .rateLimitResetTodayLastFetched: "最后刷新",
        .rateLimitResetTodayLocalDayHint: "按本机时区的自然日计算，午夜切换。",
        .rateLimitResetTodayLatestEvidence: "最近依据",
        .rateLimitResetTodayNextScheduled: "下次计划",
        .rateLimitResetTodayNextScheduledWithCountdown: "下次计划：%@（%@）",
        .rateLimitResetTodayNo: "否",
        .rateLimitResetTodayNoHint: "今日没有已完成或已排期的重置",
        .rateLimitResetTodayNoHintUncertain: "今日无明确的重置信号",
        .rateLimitResetTodayNoHintWithNext: "今日没有重置 · 下次 %@",
        .rateLimitResetTodayOpenSource: "打开状态页",
        .rateLimitResetTodayOpenEvidence: "打开 X 来源",
        .rateLimitResetTodayResetAgo: "已重置%@",
        .rateLimitResetTodayUntilReset: "距离重置还有%@",
        .rateLimitResetTodayPlanAll: "全部套餐",
        .rateLimitResetTodayPlanBusiness: "Business",
        .rateLimitResetTodayPlanEnterprise: "Enterprise",
        .rateLimitResetTodayPlanFree: "Free",
        .rateLimitResetTodayPlanPlus: "Plus",
        .rateLimitResetTodayPlanPro: "Pro",
        .rateLimitResetTodayPlanTeam: "Team",
        .rateLimitResetTodayPlanUnknown: "套餐未指明",
        .rateLimitResetTodayPlans: "套餐",
        .rateLimitResetTodayRefreshInterval: "重置状态刷新",
        .rateLimitResetTodaySeen: "见于",
        .rateLimitResetTodaySource: "Codex Runway 重置状态",
        .rateLimitResetTodaySourceInfo: "该状态由 Codex Runway 托管的监控任务生成，并使用 AI 分析公开的 X 公告。AI 结果可能不完整或有误。",
        .rateLimitResetTodaySourceTitle: "数据来源",
        .rateLimitResetTodayUnknown: "—",
        .rateLimitResetTodayUnknownHint: "状态不可用或已过期",
        .rateLimitResetTodayVerdict: "判定",
        .rateLimitResetTodayWindowFiveHour: "5 小时窗口",
        .rateLimitResetTodayWindowUnknown: "窗口未指明",
        .rateLimitResetTodayWindowWeekly: "周额度",
        .rateLimitResetTodayWindows: "额度窗口",
        .rateLimitResetTodayYes: "是",
        .rateLimitResetTodayYesHint: "今日额度已重置",
        .rateLimitResetTodayYesHintWithTime: "今日已重置 · %@",
        .rateLimitResetTodayYesHintScheduled: "今日稍后有计划重置",
        .rateLimitResetTodayYesHintScheduledWithTime: "今日计划 · %@",
        .rateLimitResetUpcomingAlertBody1h: "计划中的 Codex 重置将在 1 小时内到来。",
        .rateLimitResetUpcomingAlertBody30m: "计划中的 Codex 重置将在 30 分钟内到来。",
        .rateLimitResetUpcomingAlertTitle: "即将重置",
        .recent: "最近活跃",
        .recentSessionsDescription: "开启后才扫描本地最近会话。",
        .refresh: "刷新",
        .refreshInterval: "刷新间隔",
        .rebuilt: "已重建",
        .repair: "修复",
        .repairConfirmMessage: "Codex Runway 将从本机会话文件重建 ~/.codex/session_index.jsonl。写入前会在同目录创建带时间戳的备份。不会修改会话日志、auth.json 或全局状态。",
        .repairConfirmTitle: "修复 Codex 会话索引？",
        .repairFailed: "修复失败",
        .repairIndex: "修复索引",
        .resetsIn: "重置于",
        .resetCredits: "重置次数",
        .resetCreditAlertBody: "有重置次数即将过期。",
        .resetCreditAlertTitle: "重置次数即将过期",
        .resetCreditAlertsDescription: "可用重置次数将在 7 天内过期时提醒。",
        .resetCreditAlerts: "重置次数提醒",
        .resetCreditDetails: "重置次数详情",
        .runway: "Runway",
        .seconds: "秒",
        .sessionRepair: "会话修复",
        .sessionScanFailed: "会话扫描失败",
        .recentSessions: "最近会话",
        .settings: "设置",
        .selfCheck: "自检",
        .showDetails: "显示详情",
        .showCostSummary: "显示 API 成本摘要",
        .showModelSpecificQuotaUsage: "特有模型额度用量展示",
        .showRateLimitResetToday: "显示今日是否重置",
        .showRecentSessions: "显示最近会话",
        .showSessionRepairSummary: "显示会话修复摘要",
        .showTokenUsageHeatmap: "显示 Token 用量",
        .tokenUsageHeatmap: "Token 用量",
        .tokenUsageHeatmapDescription: "在配额下方显示本年至今的 token 用量图表（热力图、折线图或柱状图）。",
        .tokenUsageHeatmapUnavailable: "Token 用量暂时不可用",
        .tokenUsageChartStyle: "图表类型",
        .tokenUsageChartHeatmap: "热力图",
        .tokenUsageChartLine: "折线图",
        .tokenUsageChartBar: "柱状图",
        .heatmapDaily: "每日",
        .heatmapWeekly: "每周",
        .heatmapCumulative: "累计",
        .heatmapMonthly: "每月",
        .heatmapEmpty: "本年暂无 token 用量",
        .heatmapAllDevices: "官方统计（多端）",
        .heatmapLocalDevice: "本机日志（全部本机会话）",
        .heatmapLocalShort: "本机",
        .heatmapOfficialAsOf: "官方截至 %@",
        .heatmapSourceDisclosure: "官方统计可能延迟或调整；本机日志包含这台 Mac 可见的全部会话，可能跨账号。",
        .heatmapSourceMismatch: "数据源口径不同，不能作为包含关系比较",
        .sourceLocalSessions: "本地会话",
        .sourceOnlineSupplement: "在线补全",
        .staleTitles: "过期标题",
        .status: "状态",
        .subscriptionExpired: "已到期",
        .subscriptionExpires: "订阅有效期至",
        .subscriptionExpiringSoon: "订阅即将到期",
        .statusAvailable: "可用",
        .statusError: "错",
        .statusLogin: "登录",
        .statusBarBattery: "电池倒计时",
        .statusBarBatteryDetailCountdown: "刷新倒计时",
        .statusBarBatteryDetailRemainingPercent: "剩余百分比",
        .statusBarBatteryDetailStyle: "电池中心显示",
        .statusBarBatteryScope: "电池额度",
        .statusBarBatteryScopeBoth: "全部可见额度",
        .statusBarBatteryScopeFiveHour: "5小时",
        .statusBarBatteryScopeWeekly: "每周",
        .statusBarCountdown: "倒计时",
        .statusBarMetersDetailResetTime: "重置时间",
        .statusBarMetersDetailRemainingPercent: "剩余百分比",
        .statusBarMetersDetailBoth: "两者都显示",
        .statusBarMetersDetailStyle: "额度条右侧显示",
        .statusBarMeters: "额度条",
        .statusBarProviderScope: "状态栏平台",
        .statusBarProviderScopeBoth: "Codex + Grok",
        .statusBarProviderScopeSelected: "跟随当前面板",
        .statusBarRings: "圆环进度",
        .statusBarStyle: "状态栏样式",
        .statusUsed: "已使用",
        .statusWait: "等",
        .statusUnknown: "未知",
        .startDate: "开始日期",
        .updateAvailable: "发现新版本",
        .updateCheckFailed: "更新检查失败",
        .updateChecking: "正在检查更新...",
        .updateDownloadAndInstall: "下载并安装",
        .updateDownloadedReady: "Codex Runway %@ 已下载，可以安装。",
        .updateDownloading: "正在下载更新...",
        .updateExtracting: "正在解压更新...",
        .updateInstallAndRelaunch: "安装并重启",
        .updateInstallLater: "稍后",
        .updateInstalled: "更新已安装",
        .updateInstalledMessage: "Codex Runway 已完成更新。",
        .updateInstalling: "正在安装更新...",
        .updateLearnMore: "了解更多",
        .updateNetworkProxyHint: "如果你使用系统代理，请确认 github.com 和 release-assets.githubusercontent.com 不在系统代理绕过列表中，或使用 TUN 模式。",
        .updateReadyToInstall: "准备安装",
        .updateSigningKeyMissing: "Sparkle 签名公钥未配置。",
        .updateSkipVersion: "跳过此版本",
        .updateUnavailableInDevelopment: "使用 swift run 运行时无法安装更新。请使用打包后的 .app 或 Release 版本测试 Sparkle 更新。",
        .updateVersionAvailable: "Codex Runway %@ 可用。",
        .upToDate: "Codex Runway 已是最新版本。",
        .total: "总数",
        .totalRemaining: "总剩余",
        .tokens: "Tokens",
        .tokensOnly: "仅 tokens",
        .testNotification: "测试提醒",
        .testNotificationBody: "Codex Runway 的通知可以正常显示。",
        .testNotificationDevelopmentMode: "系统通知需要运行打包后的 CodexRunway.app，无法在 swift run 中测试。",
        .testNotificationSubtitle: "请求 macOS 通知权限并发送一条测试提醒。",
        .testNotificationTitle: "Codex Runway 测试提醒",
        .threads: "线程",
        .today: "今日",
        .thisMonth: "本月",
        .turns: "轮",
        .unknown: "未知",
        .unknownAccount: "未知账号",
        .unknownModels: "未知模型",
        .unavailableCredits: "不可用次数",
        .usageAnalyticsUnavailable: "用量分析不可用",
        .usageAnalyticsEmpty: "该时间段暂无用量",
        .used: "已用",
        .usdPerCredit: "每 Credit 美元",
        .version: "版本",
        .weeklyValueEstimate: "周总额估算",
        .weeklyUsage: "每周",
        .widgetAllDevices: "所有设备",
        .widgetBalance: "余额",
        .widgetCost: "API 等价成本",
        .widgetDataCorrupt: "组件数据已损坏，请刷新 Codex Runway。",
        .widgetDataOld: "数据已过期",
        .widgetMetricTitle: "关键指标",
        .widgetNoData: "打开 Codex Runway 以加载组件数据。",
        .widgetOverviewTitle: "额度总览",
        .widgetRemaining: "剩余额度",
        .widgetResetCredits: "重置次数",
        .widgetResetTodayTitle: "今日重置",
        .widgetThisMac: "本机",
        .widgetTokenTrendTitle: "Token 趋势",
        .widgetUpdated: "更新于",
        .widgetVersionUnsupported: "请更新 Codex Runway 以读取组件数据。",
    ]
}
