extension L10n {
    static let fr: [L10nKey: String] = [
        .apiCost: "Coût équivalent API",
        .apiCostSummaryRange: "Plage de coût API",
        .apiCostSource: "Source du coût",
        .apiEquivalent: "Équivalent API",
        .apiTokenPricing: "Tarifs des jetons API",
        .appearance: "Apparence",
        .appearanceDark: "Sombre",
        .appearanceLight: "Clair",
        .appearanceSystem: "Système",
        .auto: "Auto",
        .about: "À propos",
        .advanced: "Avancé",
        .account: "Compte",
        .accounts: "Comptes",
        .accountsAdd: "Ajouter un compte",
        .accountsAddAPIKey: "API Key",
        .accountsAddFile: "Importer des fichiers",
        .accountsAddLocal: "Importer auth.json local",
        .accountsAddOAuth: "Connexion via le navigateur",
        .accountsAddPaste: "Coller un jeton / JSON",
        .accountsAPIKeyHint: "Collez une clé API OpenAI. Les comptes API n’affichent pas les jauges de quota ChatGPT.",
        .accountsCurrent: "Actuel",
        .accountsDelete: "Retirer",
        .accountsDeleteConfirmMessage: "Retirer ce compte de CodexRunway ? La connexion officielle Codex reste inchangée, sauf s’il s’agit du compte actuel.",
        .accountsDeleteConfirmTitle: "Retirer le compte ?",
        .accountsDeselectAll: "Tout désélectionner",
        .accountsEmpty: "Aucun compte géré. Importez le fichier auth.json local ou ajoutez un autre compte.",
        .accountsExport: "Exporter",
        .accountsExportEmpty: "Aucun compte à exporter.",
        .accountsExportFailed: "Échec de l’export",
        .accountsExportHint: "Choisissez les comptes de la plateforme actuelle à exporter. Le fichier peut être importé sur un autre Mac dans CodexRunway.",
        .accountsExportSucceeded: "%d compte(s) exporté(s)",
        .accountsExportTitle: "Exporter les comptes",
        .accountsExportWarning: "Le fichier d’export contient des identifiants. Conservez-le et transmettez-le en toute sécurité.",
        .accountsForceCurrent: "Forcer comme connexion actuelle",
        .accountsImportFailed: "Échec de l’import",
        .accountsImportNoCredentials: "Aucune information d’identification. Collez auth.json, un refresh token ou un JSON ChatGPT /auth/session (accessToken).",
        .accountsImportPreviewHint: "Vérifiez les comptes trouvés dans les fichiers sélectionnés. Décochez ceux que vous ne voulez pas importer.",
        .accountsImportPreviewTitle: "Importer des comptes",
        .accountsImportProgress: "Importation %d / %d",
        .accountsImportProviderNotice: "Importé dans les comptes %@",
        .accountsImportSelected: "Importer la sélection",
        .accountsImportSucceeded: "%d compte(s) importé(s)",
        .accountsImportWillAdd: "Sera ajouté",
        .accountsImportWillUpdate: "Sera mis à jour",
        .accountsUserIdLabel: "ID utilisateur :",
        .accountsWorkspaceIdLabel: "ID de l’espace :",
        .accountsWorkspaceNameLabel: "Espace :",
        .accountsIsCurrentLogin: "Ceci est le compte de connexion Codex actuel",
        .accountsMakeCurrent: "Utiliser dans Codex",
        .accountsMoveDown: "Descendre",
        .accountsMoveUp: "Monter",
        .accountsNeedsReauth: "Réauthentification requise",
        .accountsNote: "Note",
        .accountsOAuthCancelled: "La connexion via le navigateur a été annulée.",
        .accountsOAuthFailed: "Échec de la connexion via le navigateur",
        .accountsOAuthWaiting: "Terminez la connexion dans le navigateur…",
        .accountsPasteFromClipboard: "Coller depuis le presse-papiers",
        .accountsPasteHint: "Collez un refresh token, ~/.codex/auth.json, un JSON ChatGPT /api/auth/session ou un tableau JSON de comptes.",
        .accountsRefreshAll: "Actualiser tous les quotas",
        .accountsReauthRequired: "Reconnectez-vous",
        .accountsRestartCodexAfterSwitch: "Redémarrer Codex immédiatement après le basculement",
        .accountsRestartCodexFailed: "Compte basculé, mais Codex n’a pas pu être redémarré : %@",
        .accountsRestartCodexSucceeded: "Compte basculé. Codex a été redémarré.",
        .accountsSelectAll: "Tout sélectionner",
        .accountsSidebarTitle: "Comptes",
        .accountsSwitchConfirmTitle: "Basculer de compte ?",
        .accountsSwitchConfirmMessage: "Remplacer ~/.codex/auth.json par « %@ », Codex le prendra en compte après un redémarrage.",
        .accountsSwitchFailed: "Impossible de basculer de compte",
        .accountsSwitchInvalidCredential: "Les identifiants de ce compte sont invalides ou incomplets, ils ne peuvent pas servir de connexion Codex.",
        .accountsSwitchMissingRefresh: "Ce compte n’a pas de refresh_token. Tant que le jeton d’accès est valide, vous pouvez basculer ; une fois expiré, réimportez la session ou connectez-vous via le navigateur.",
        .accountsSwitchSessionExpired: "Le jeton d’accès de cette session a expiré et il n’y a pas de refresh_token. Réimportez depuis /auth/session ou connectez-vous via le navigateur.",
        .accountsSwitching: "Basculement de compte…",
        .accountsSwitchRealHint: "Le basculement écrit le compte sélectionné dans ~/.codex/auth.json pour que Codex CLI et l’IDE l’utilisent.",
        .alias: "Alias",
        .automaticallyCheckForUpdates: "Rechercher automatiquement les mises à jour",
        .available: "Disponible",
        .availableResets: "réinitialisations disponibles",
        .back: "Retour",
        .backup: "Sauvegarde",
        .cachedInput: "Entrée en cache",
        .cachedInputTokens: "Jetons d’entrée en cache",
        .cancel: "Annuler",
        .calculate: "Calculer",
        .calculating: "Calcul…",
        .codexFolder: "Ouvrir le dossier Codex",
        .controlPanel: "Panneau de configuration",
        .calculatedAt: "Calculé",
        .costShare: "Part du coût",
        .costScanFailed: "Échec de l’analyse des coûts",
        .costScanPreparing: "Préparation de l’analyse d’usage…",
        .costScanIndexing: "Indexation des journaux de session…",
        .costScanAggregating: "Agrégation de l’usage…",
        .costScanFetchingOnline: "Récupération de l’usage en ligne…",
        .costScanProgressFiles: "%d / %d fichiers",
        .credit: "Crédit",
        .creditsBalance: "Solde de crédits",
        .creditsUsed: "Crédits utilisés",
        .currentCycle: "Cycle actuel",
        .currentCycleAmount: "Montant du cycle actuel",
        .customRange: "Personnalisé",
        .customRangePrompt: "Sélectionnez une plage de dates, puis cliquez sur Calculer",
        .cycleStarted: "Début",
        .date: "Date",
        .burnRate: "Rythme de consommation",
        .duplicate: "doublon",
        .duplicateIndexIDs: "ID d’index en double",
        .display: "Affichage",
        .displayAppearanceSection: "Apparence et barre de menus",
        .mainPanelBackground: "Fond du panneau",
        .mainPanelBackgroundDescription: "Le fond translucide laisse voir les fenêtres derrière le panneau.",
        .mainPanelBackgroundOpaque: "Opaque",
        .mainPanelBackgroundTranslucent: "Translucide",
        .endDate: "Date de fin",
        .estimatedAPICost: "Coût API estimé",
        .expiresRemaining: "Validité restante",
        .expiresAt: "Expire",
        .expiryRisk: "Risque d’expiration",
        .expiringSoon: "Expire bientôt",
        .exhaustsIn: "Épuisé dans",
        .error: "Erreur",
        .exportStatusJSON: "Exporter le JSON d’état local",
        .failed: "Échec",
        .checkForUpdates: "Rechercher des mises à jour",
        .fiveHourUsage: "5 heures",
        .general: "Général",
        .grokAccountsAddFile: "Importer des fichiers",
        .grokAccountsAddOAuth: "Se connecter à un nouveau compte Grok",
        .grokAccountsAddPaste: "Coller un jeton / JSON",
        .grokAccountsCurrent: "Compte Grok actuel",
        .grokAccountsDeleteConfirmMessage: "Retirer ce compte de CodexRunway ? La connexion officielle Grok n’est pas modifiée.",
        .grokAccountsDeleteConfirmTitle: "Retirer le compte Grok ?",
        .grokAccountsEmpty: "Aucun compte Grok géré. Connectez-vous, importez la connexion Grok actuelle ou collez des identifiants.",
        .grokAccountsImportNoCredentials: "Aucune information d’identification. Collez ~/.grok/auth.json ou un objet d’identifiants Grok (key/refresh_token plus email, user_id ou principal_id).",
        .grokAccountsImportOfficial: "Importer la connexion Grok actuelle",
        .grokAccountsMakeCurrent: "Utiliser dans Grok",
        .grokAccountsPasteHint: "Collez ~/.grok/auth.json, un objet d’identifiants OAuth/legacy Grok ou un tableau JSON de comptes. Les identifiants uniquement par clé API ne sont pas pris en charge.",
        .grokAccountsRefreshAll: "Actualiser tous les quotas Grok",
        .grokAccountsRemove: "Retirer le compte Grok",
        .grokAccountsTitle: "Comptes Grok",
        .grokBillingParseFailed: "Grok a renvoyé une réponse de facturation non prise en charge. Mettez à jour le CLI ou réessayez plus tard.",
        .grokBillingPeriod: "Période de facturation",
        .grokBillingPeriodMonthly: "Quota inclus mensuel",
        .grokBillingPeriodWeekly: "Quota inclus hebdomadaire",
        .grokCLIInstallHint: "Installez le CLI Grok officiel, puis connectez-vous avec OAuth pour voir la facturation.",
        .grokCLIOpenInstallGuide: "Ouvrir le guide d’installation du CLI Grok",
        .grokCLITooOld: "Cette version du CLI Grok ne prend pas en charge la facturation. Mettez à jour le CLI et réessayez.",
        .grokCLIUnavailable: "Le CLI Grok n’est pas installé",
        .grokCurrentAccountCannotDelete: "Basculez vers un autre compte Grok avant de retirer le compte actuel.",
        .grokDataSource: "Source des données",
        .grokExternalLoginChanged: "La connexion Grok a été modifiée par un autre processus. L’état du compte a été synchronisé à partir des identifiants officiels.",
        .grokImportFailed: "Impossible d’importer la connexion Grok actuelle",
        .grokImportSucceeded: "Connexion Grok actuelle importée",
        .grokIncludedQuota: "Quota inclus",
        .grokIncludedUSD: "Crédit USD inclus",
        .grokLocalUsage: "Usage local des jetons",
        .grokLocalUsageHint: "Issu des sessions Grok CLI récentes sur ce Mac (usage turn_completed).",
        .grokLoginCancelled: "La connexion Grok a été annulée.",
        .grokLoginFailed: "Échec de la connexion Grok",
        .grokLoginWaiting: "Terminez la connexion Grok dans le navigateur (la page du code d’appareil s’ouvre automatiquement)…",
        .grokNoManagedOAuth: "Aucune connexion Grok OAuth gérable ou legacy compatible n’a été trouvée.",
        .grokNoQuotaData: "Aucune donnée de facturation Grok n’est encore disponible.",
        .grokNotLoggedIn: "Grok n’est pas connecté",
        .grokOnDemandLimit: "Plafond à la demande",
        .grokOnDemandUsage: "Usage à la demande",
        .grokPlan: "Offre Grok",
        .grokPrepaidBalance: "Solde prépayé",
        .grokProductBuild: "Grok Build",
        .grokProductChat: "Grok Chat",
        .grokProductImagine: "Grok Imagine",
        .grokProductUsage: "Usage par produit",
        .grokReauthenticationRequired: "La connexion Grok a expiré. Connectez-vous à nouveau.",
        .grokRefreshFailed: "Impossible d’actualiser la facturation Grok",
        .grokRefreshCancelled: "L’actualisation de la facturation Grok a été annulée.",
        .grokRefreshTimedOut: "La requête de facturation Grok a expiré.",
        .grokRefreshing: "Actualisation de la facturation Grok…",
        .grokResetAt: "Réinitialisation",
        .grokSessionsScanned: "%d session(s) analysée(s)",
        .grokSourceCLI: "API de facturation du CLI Grok",
        .grokSourceLocalSessions: "Sessions Grok locales",
        .grokSwitchConfirmMessage: "Remplacer la connexion OAuth officielle Grok par « %@ » ? Seules les nouvelles sessions Grok sont garanties de l’utiliser.",
        .grokSwitchConfirmTitle: "Basculer de compte Grok ?",
        .grokSwitchFailed: "Impossible de basculer de compte Grok",
        .grokSwitchOnlyNewSessions: "Le basculement de compte n’affecte que les nouvelles sessions Grok.",
        .grokSwitchRunningMessage: "Un ou plusieurs processus Grok sont encore en cours. Ils peuvent réécrire la connexion précédente après ce basculement. Continuer ne garantit que l’utilisation du compte sélectionné pour les nouvelles sessions Grok.",
        .grokSwitchRunningTitle: "Grok est en cours d’exécution",
        .grokSwitching: "Basculement du compte Grok…",
        .grokUnifiedBilling: "Facturation unifiée",
        .grokUpdatedAt: "Facturation Grok mise à jour",
        .hours: "heures",
        .modelBreakdown: "Répartition par modèle",
        .modelSpecificQuotaUsageDescription: "Afficher la progression des quotas par modèle dans la barre de menus et le panneau principal.",
        .noModelCostData: "Aucune donnée de coût par modèle",
        .nonCachedInput: "Entrée non mise en cache",
        .inputShort: "in",
        .inputCachedOutput: "Entrée / cache / sortie",
        .inputTokens: "Jetons d’entrée",
        .invalidDateRange: "Plage de dates invalide",
        .language: "Langue",
        .languageEnglish: "Anglais",
        .languageSimplifiedChinese: "Chinois simplifié",
        .lastReset: "Dernière réinitialisation",
        .lastUpdated: "Mis à jour",
        .later: "plus tard",
        .left: "restant",
        .minutes: "minutes",
        .missing: "manquant",
        .missingFromIndex: "Absent de l’index",
        .nextResetIn: "Prochaine réinit. : ",
        .nextExpiry: "Prochaine expiration",
        .latestExpiry: "Dernière expiration",
        .resetExpiryUnavailable: "Aucune date d’expiration disponible",
        .resetExpirySummaryHelp: "Seuls les crédits disponibles lors de la dernière mise à jour et dont la date d’expiration est connue sont pris en compte.",
        .needsAttention: "Attention requise",
        .noExpiry: "sans expiration",
        .noAvailableResetCredits: "Aucun crédit de réinitialisation",
        .notLoggedIn: "Non connecté",
        .authExpired: "La connexion a expiré. Reconnectez-vous ou basculez vers un compte qui a un refresh_token valide.",
        .authFileInvalid: "Le auth.json local est invalide ou incomplet. Restaurez un compte utilisable ou reconnectez-vous.",
        .noPreviousIndex: "pas d’index précédent",
        .notLoaded: "Non chargé",
        .notScanned: "Non analysé",
        .ok: "OK",
        .openControlPanel: "Ouvrir le panneau de configuration",
        .openDetailsWindow: "Ouvrir la fenêtre de détails",
        .orphan: "orphelin",
        .orphanIndexRows: "Lignes d’index orphelines",
        .outputTokens: "Jetons de sortie",
        .outputShort: "out",
        .openGithub: "Ouvrir GitHub",
        .tokenComposition: "Composition des jetons",
        .feedbackIssue: "Commentaires",
        .historicalUsage: "Usage historique",
        .privacy: "Les jetons restent sur ce Mac. La réparation des sessions ne réécrit l’index local qu’après une sauvegarde.",
        .plan: "Offre",
        .planAPI: "API",
        .planBusiness: "Business",
        .planEdu: "Edu",
        .planEnterprise: "Enterprise",
        .planFree: "Free",
        .planPlus: "Plus",
        .planPro5x: "Pro 5X",
        .planPro20x: "Pro 20X",
        .planTeam: "Team",
        .planUnknown: "Inconnu",
        .plannedEntries: "Entrées planifiées",
        .pricingVersion: "Version des tarifs",
        .projectBreakdown: "Répartition par projet",
        .projectedAtReset: "Projection à la réinitialisation",
        .projectedWeeklyTotal: "Total hebdomadaire projeté",
        .previousCycle: "Cycle précédent",
        .providerCodex: "Codex",
        .providerGrok: "Grok",
        .quota: "Quota",
        .quotaAlertBody: "%@ a atteint %@ d’utilisation.",
        .quotaAlertTitle: "Alerte de quota Codex",
        .quotaAlertsDescription: "Alerte lorsque l’usage atteint 80 %, 95 % ou 100 %.",
        .quotaAlerts: "Alertes de quota",
        .quotaEstimate: "Estimation de quota",
        .quotaEstimateCannotExtrapolate: "Pas assez d’usage hebdomadaire pour estimer",
        .quotaEstimateCredits: "Credits",
        .quotaEstimateCut: "Possible baisse",
        .quotaEstimateHistory: "Estimations précédentes",
        .quotaEstimateIncreased: "Plus élevé qu’avant",
        .quotaEstimateInfo: "Estime le quota à partir du pourcentage officiel et des Credits journaliers. La conversion non officielle de 1000 Credits ≈ $40 diffère du coût de référence par jeton du tableau. Les agrégats journaliers n’épousent qu’approximativement les limites de période ; les estimations sont indicatives.",
        .quotaEstimateMethodOfficial: "Fenêtre auto",
        .quotaEstimateMethodRolling: "7 derniers jours",
        .quotaEstimateMissingCredits: "Les statistiques officielles ne fournissent pas de Credits complets ; estimation impossible",
        .quotaEstimateNoUsage: "Aucune utilisation dans cette période ; estimation impossible pour le moment",
        .quotaEstimateShowingPreviousData: "Échec de l’actualisation ; affichage des dernières données récupérées",
        .quotaEstimateStatsThrough: "Statistiques jusqu’au %@",
        .quotaEstimateUnavailableWindow: "Aucune période de quota disponible pour l’estimation",
        .quotaEstimateZeroCreditsWithUsage: "Les statistiques officielles indiquent une utilisation de jetons mais 0 Credits ; estimation impossible",
        .quotaEstimateZeroPercent: "Le pourcentage utilisé est de 0 % ; estimation impossible pour le moment",
        .quotaEstimateThisWeek: "Cette semaine",
        .quotaEstimateThisWeekUsed: "Utilisé cette semaine",
        .quotaEstimateUsedPercent: "Pourcentage utilisé",
        .quotaEstimateWeekValue: "Valeur hebdomadaire (estimée)",
        .quotaEstimateWeeklyAllowance: "Quota hebdomadaire estimé",
        .quotaEstimateWindowMode: "Fenêtre d’estimation",
        .quotaEstimateWindowOfficial: "Fenêtre auto",
        .quotaEstimateWindowRolling: "7 derniers jours calendaires",
        .quotaEstimateVsLast: "vs dernière estimation",
        .quit: "Quitter",
        .rawAnalyticsCredits: "Crédits d’analyse bruts",
        .rateLimitResetDetectedAlertBody: "Une réinitialisation de quota Codex vient d’être détectée pour aujourd’hui.",
        .rateLimitResetDetectedBankedAlertBody: "Une réinitialisation est stockée dans la banque pour un usage à la demande ; elle n’actualise pas automatiquement le quota actuel.",
        .rateLimitResetDetectedGlobalAndBankedAlertBody: "La réinitialisation globale est terminée ; une autre réinitialisation est stockée dans la banque pour un usage à la demande et n’actualise pas elle-même le quota actuel.",
        .rateLimitResetDetectedAlertTitle: "Réinitialisation Codex détectée",
        .rateLimitResetDetectedTypedAlertTitle: "Codex — confirmation : %@",
        .rateLimitResetToday: "Réinit. aujourd’hui ?",
        .rateLimitResetTodayAlerts: "Alertes de réinit. du jour",
        .rateLimitResetTodayAlertsDescription: "Notifier lorsqu’une réinitialisation est nouvellement détectée, et lorsqu’une réinitialisation planifiée est dans 1 heure ou 30 minutes.",
        .rateLimitResetTodayAwaiting: "Aucune réinitialisation terminée ou planifiée pour aujourd’hui",
        .rateLimitResetTodayBankedCompletedHint: "Une réinitialisation est stockée dans la banque pour un usage à la demande ; le quota actuel n’a pas été actualisé",
        .rateLimitResetTodayBankedScheduledHint: "Un crédit de réinitialisation est prévu dans la banque aujourd’hui, mais n’est pas encore arrivé",
        .rateLimitResetTodayCheckCost: "Coût de la vérification",
        .rateLimitResetTodayConfidence: "Confiance",
        .rateLimitResetTodayDescription: "Statut public depuis www.codexrunway.com.",
        .rateLimitResetTodayEvidenceBankedReset: "Une réinitialisation mise en réserve a été annoncée ; ce n’est pas une réinitialisation terminée.",
        .rateLimitResetTodayEvidenceBankedCompleted: "L’arrivée d’un crédit dans la banque de réinitialisations est confirmée pour un usage à la demande.",
        .rateLimitResetTodayEvidenceBankedPreview: "Un crédit très probable dans la banque de réinitialisations a été déduit du contexte.",
        .rateLimitResetTodayEvidenceBankedScheduled: "L’arrivée d’un crédit dans la banque de réinitialisations a été explicitement planifiée.",
        .rateLimitResetTodayEvidenceGlobalAndBankedCompleted: "Une réinitialisation globale et un crédit dans la banque sont confirmés.",
        .rateLimitResetTodayEvidenceGlobalAndBankedPreview: "Une réinitialisation globale et un crédit dans la banque très probables ont été déduits du contexte.",
        .rateLimitResetTodayEvidenceGlobalAndBankedScheduled: "Une réinitialisation globale et l’arrivée d’un crédit dans la banque ont été explicitement planifiées.",
        .rateLimitResetTodayEvidenceLimitIncrease: "Une hausse de plafond de quota a été annoncée ; ce n’est pas une réinitialisation.",
        .rateLimitResetTodayEvidenceResetCompleted: "Une réinitialisation explicite de quota Codex a été annoncée.",
        .rateLimitResetTodayEvidenceResetScheduled: "Une réinitialisation explicite de quota Codex a été planifiée.",
        .rateLimitResetTodayEvidenceResetPreview: "Une réinitialisation de quota Codex très probable a été déduite du contexte.",
        .rateLimitResetTodayEvidenceManualCompletion: "Confirmé sans publication de fin sur X.",
        .rateLimitResetTodayEvidenceOperatorCompletion: "Confirmé par les opérateurs ; Tibo n’a pas publié sur X.",
        .rateLimitResetTodayEvidenceOperatorScheduled: "Calendrier confirmé par les opérateurs ; Tibo n’a pas publié sur X.",
        .rateLimitResetTodayEvidenceUncertain: "Ce n’est pas un signal de réinitialisation clair.",
        .rateLimitResetTodayLastCheck: "Dernière vérification",
        .rateLimitResetTodayLastFetched: "Dernière actualisation",
        .rateLimitResetTodayLocalDayHint: "Utilise votre jour civil local et change à minuit.",
        .rateLimitResetTodayLatestEvidence: "Dernière preuve",
        .rateLimitResetTodayNextScheduled: "Prochaine réinit. prévue",
        .rateLimitResetTodayNextScheduledWithCountdown: "Prochaine réinit. prévue : %@ (%@)",
        .rateLimitResetTodayNo: "Non",
        .rateLimitResetTodayNoHint: "Aucune réinitialisation terminée ou planifiée aujourd’hui",
        .rateLimitResetTodayNoHintUncertain: "Aucun signal de réinitialisation clair pour aujourd’hui",
        .rateLimitResetTodayNoHintUnconfirmedSchedule: "L’horaire de {type} est passé sans confirmation",
        .rateLimitResetTodayNoHintWithLast: "Aucune réinitialisation terminée ou planifiée aujourd’hui. Dernière {type} il y a {ago}",
        .rateLimitResetTodayNoHintWithNext: "Pas de réinit. aujourd’hui · prochaine prévue %@",
        .rateLimitResetTodayOpenSource: "Ouvrir la page d’état",
        .rateLimitResetTodayOpenWebsite: "Voir le statut et l’historique sur le site CodexRunway",
        .rateLimitResetTodayOpenEvidence: "Ouvrir la source X",
        .rateLimitResetTodayResetAgo: "Réinit. il y a %@",
        .rateLimitResetTodayUntilReset: "%@ avant réinit.",
        .rateLimitResetTodayPlanAll: "Toutes les offres",
        .rateLimitResetTodayPlanBusiness: "Business",
        .rateLimitResetTodayPlanEnterprise: "Enterprise",
        .rateLimitResetTodayPlanFree: "Free",
        .rateLimitResetTodayPlanPlus: "Plus",
        .rateLimitResetTodayPlanPro: "Pro",
        .rateLimitResetTodayPlanTeam: "Team",
        .rateLimitResetTodayPlanUnknown: "Offre non précisée",
        .rateLimitResetTodayPlans: "Offres",
        .rateLimitResetTodayRefreshInterval: "Actualisation de l’état de réinit.",
        .rateLimitResetTodayReactionPlease: "Demander",
        .rateLimitResetTodayReactionThank: "Merci",
        .rateLimitResetTodayReactionPleaseAria: "Demander une réinit., %@",
        .rateLimitResetTodayReactionThankAria: "Merci pour la réinit., %@",
        .rateLimitResetTodayReactionLimitReached: "Limite quotidienne atteinte",
        .rateLimitResetTodaySeen: "Vu",
        .rateLimitResetTodaySource: "État de réinit. CodexRunway",
        .rateLimitResetTodaySourceInfo: "CodexRunway publie cet état depuis un moniteur hébergé qui utilise l’IA pour analyser les annonces publiques sur X. Les résultats de l’IA peuvent être incomplets ou incorrects.",
        .rateLimitResetTodaySourceTitle: "Source des données",
        .rateLimitResetTodayGlobalAndBankedCompletedHint: "Le quota global est réinitialisé ; une autre réinitialisation est stockée dans la banque pour un usage à la demande",
        .rateLimitResetTodayGlobalAndBankedScheduledHint: "Une réinitialisation globale et un crédit dans la banque sont prévus aujourd’hui, mais ne sont pas encore arrivés",
        .rateLimitResetTypeBanked: "Banque de réinit.",
        .rateLimitResetTypeGlobal: "Réinit. globale",
        .rateLimitResetTypeGlobalAndBanked: "Réinit. globale + banque",
        .rateLimitResetTodayUnknown: "—",
        .rateLimitResetTodayUnknownHint: "L’état est indisponible ou obsolète",
        .rateLimitResetTodayVerdict: "Verdict",
        .rateLimitResetTodayWindowFiveHour: "Fenêtre de 5 heures",
        .rateLimitResetTodayWindowUnknown: "Fenêtre non précisée",
        .rateLimitResetTodayWindowWeekly: "Limite hebdomadaire",
        .rateLimitResetTodayWindows: "Fenêtre de limite",
        .rateLimitResetTodayYes: "Oui",
        .rateLimitResetTodayYesHint: "Les limites ont été réinitialisées aujourd’hui",
        .rateLimitResetTodayYesHintWithTime: "Réinit. aujourd’hui · %@",
        .rateLimitResetTodayYesHintScheduled: "Réinit. globale prévue aujourd’hui, mais pas encore terminée",
        .rateLimitResetTodayYesHintScheduledWithTime: "Prévu aujourd’hui, pas encore terminé · %@",
        .rateLimitResetTodayPercentPrefix: "≥%@%%",
        .rateLimitResetTodayPercentExact: "%@%%",
        .rateLimitResetTodayClockLocal: "heure locale",
        .rateLimitResetTodayConfirmedWhen: "%@ (il y a %@)",
        .rateLimitResetTodayConfirmedHint:
            "Une {type} terminée a été observée aujourd’hui. Confiance d’environ {percent}. Heure de réinit. en {zone} : {when}",
        .rateLimitResetTodayConfirmedHintNoPercent:
            "Une {type} terminée a été observée aujourd’hui. Heure de réinit. en {zone} : {when}",
        .rateLimitResetTodayScheduledChanceHint:
            "Environ {percent} de chances d’une {type} ; actuellement planifiée. Fenêtre approximative en {zone} : {date}",
        .rateLimitResetUpcomingAlertBody1h: "Une réinitialisation Codex planifiée a lieu dans moins d’1 heure.",
        .rateLimitResetUpcomingAlertBody30m: "Une réinitialisation Codex planifiée a lieu dans moins de 30 minutes.",
        .rateLimitResetUpcomingRangeAlertBody: "Fenêtre de réinit. prévue : %@.",
        .rateLimitResetUpcomingRangeAlertTitle: "Fenêtre de réinit. Codex prévue",
        .rateLimitResetUpcomingAlertTitle: "Réinitialisation Codex imminente",
        .rateLimitResetUpcomingTypedAlertTitle: "Codex — %@ imminente",
        .rateLimitResetUpcomingTypedRangeAlertTitle: "Fenêtre Codex prévue — %@",
        .recent: "Récent",
        .recentSessionsDescription: "Analyse les sessions locales lorsqu’il est activé.",
        .refresh: "Actualiser",
        .refreshInterval: "Intervalle d’actualisation",
        .rebuilt: "Reconstruit",
        .repair: "Réparer",
        .repairConfirmMessage: "CodexRunway reconstruira ~/.codex/session_index.jsonl à partir des fichiers de session locaux. Une sauvegarde horodatée sera créée à côté de l’index avant l’écriture. Les journaux de session, auth.json et l’état global ne sont pas modifiés.",
        .repairConfirmTitle: "Réparer l’index de session Codex ?",
        .repairFailed: "Échec de la réparation",
        .repairIndex: "Réparer l’index",
        .resetsIn: "réinit. dans",
        .resetCredits: "Crédits de réinitialisation",
        .resetCreditAlertBody: "Un crédit de réinitialisation expire bientôt.",
        .resetCreditAlertTitle: "Crédit de réinitialisation bientôt expiré",
        .resetCreditAlertsDescription: "Alerte lorsqu’un crédit de réinitialisation disponible expire dans les 7 jours.",
        .resetCreditAlerts: "Alertes de crédits de réinit.",
        .resetCreditDetails: "Détails des crédits de réinit.",
        .restoreDefaultOrder: "Rétablir l’ordre par défaut",
        .runway: "Runway",
        .seconds: "secondes",
        .sessionRepair: "Réparation des sessions",
        .sessionScanFailed: "Échec de l’analyse des sessions",
        .recentSessions: "Sessions récentes",
        .settings: "Réglages",
        .selfCheck: "Auto-diagnostic",
        .showDetails: "Afficher les détails",
        .showCostSummary: "Afficher le résumé du coût API",
        .showModelSpecificQuotaUsage: "Afficher l’usage de quota par modèle",
        .showRateLimitResetToday: "Afficher l’état de réinit. du jour",
        .showRecentSessions: "Afficher les sessions récentes",
        .showSessionRepairSummary: "Afficher le résumé de réparation des sessions",
        .showTokenUsageHeatmap: "Afficher l’usage des jetons",
        .mainPanelModules: "Modules du panneau principal",
        .mainPanelModulesDescription: "Choisissez les modules affichés et leur ordre. Les modules masqués gardent leur position.",
        .moduleAPICostDescription: "Estimation du coût équivalent API à partir des sessions locales.",
        .moduleAppliesCodex: "Codex",
        .moduleAppliesBoth: "Codex et Grok",
        .moduleHidden: "Masqué",
        .moduleQuotaDescription: "Jauges de quota et limites par modèle.",
        .moduleQuotaEstimateDescription: "Estime le quota de la semaine d’après l’historique pour repérer une baisse officielle.",
        .moduleResetCreditsDescription: "Crédits de réinitialisation disponibles et détails d’expiration.",
        .moduleSessionRepairDescription: "État de l’index de session local et outils de réparation.",
        .moduleVisible: "Visible",
        .notificationSettings: "Notifications",
        .tokenUsageHeatmap: "Usage des jetons",
        .tokenUsageHeatmapDescription: "Graphique d’usage des jetons depuis le début de l’année (carte de chaleur, ligne ou barres).",
        .tokenUsageHeatmapUnavailable: "L’usage des jetons est temporairement indisponible",
        .tokenUsageChartStyle: "Style du graphique",
        .tokenUsageChartHeatmap: "Carte de chaleur",
        .tokenUsageChartLine: "Ligne",
        .tokenUsageChartBar: "Barres",
        .heatmapDaily: "Quotidien",
        .heatmapWeekly: "Hebdomadaire",
        .heatmapCumulative: "Total",
        .heatmapMonthly: "Mensuel",
        .heatmapEmpty: "Pas encore d’usage de jetons cette année",
        .heatmapAllDevices: "Stats officielles (tous les appareils)",
        .heatmapLocalDevice: "Journaux locaux (toutes les sessions)",
        .heatmapLocalShort: "Local",
        .heatmapOfficialAsOf: "Officiel jusqu’au %@",
        .heatmapSourceDisclosure: "Les stats officielles peuvent être en retard ou révisées. Les journaux locaux incluent chaque session visible sur ce Mac et peuvent couvrir plusieurs comptes. Les valeurs quotidiennes utilisent les dates UTC.",
        .heatmapSourceMismatch: "Sources différentes ; les valeurs ne sont pas une comparaison d’inclusion.",
        .sourceLocalSessions: "Sessions locales",
        .sourceOnlineSupplement: "Complément en ligne",
        .staleTitles: "Titres obsolètes",
        .status: "État",
        .subscriptionExpired: "Expiré",
        .subscriptionExpires: "Valable jusqu’au",
        .subscriptionExpiringSoon: "Expire bientôt",
        .statusAvailable: "disponible",
        .statusError: "err",
        .statusLogin: "connexion",
        .statusBarBattery: "Batterie avec compte à rebours",
        .statusBarBatteryDetailCountdown: "Compte à rebours de réinit.",
        .statusBarBatteryDetailRemainingPercent: "Pourcentage restant",
        .statusBarBatteryDetailStyle: "Texte au centre de la batterie",
        .statusBarBatteryScope: "Quota de la batterie",
        .statusBarBatteryScopeBoth: "Tous visibles",
        .statusBarBatteryScopeFiveHour: "5 heures",
        .statusBarBatteryScopeWeekly: "Hebdomadaire",
        .statusBarCountdown: "Compte à rebours",
        .statusBarMetersDetailResetTime: "Heure de réinit.",
        .statusBarMetersDetailRemainingPercent: "Pourcentage restant",
        .statusBarMetersDetailBoth: "Les deux",
        .statusBarMetersDetailStyle: "Détail de la barre de quota",
        .statusBarMeters: "Barres de quota",
        .statusBarProviderScope: "Plateformes de la barre d’état",
        .statusBarProviderScopeBoth: "Codex + Grok",
        .statusBarProviderScopeSelected: "Suivre le panneau actuel",
        .statusBarRings: "Anneaux de quota",
        .statusBarStyle: "Style de la barre de menus",
        .statusBarText: "Texte de progression",
        .statusUsed: "utilisé",
        .statusWait: "attente",
        .statusUnknown: "inconnu",
        .startDate: "Date de début",
        .updateAvailable: "Mise à jour disponible",
        .updateCheckFailed: "Échec de la recherche de mises à jour",
        .updateChecking: "Recherche de mises à jour...",
        .updateDownloadAndInstall: "Télécharger et installer",
        .updateDownloadedReady: "CodexRunway %@ a été téléchargé et est prêt à être installé.",
        .updateDownloading: "Téléchargement de la mise à jour...",
        .updateExtracting: "Extraction de la mise à jour...",
        .updateInstallAndRelaunch: "Installer et relancer",
        .updateInstallLater: "Plus tard",
        .updateInstalled: "Mise à jour installée",
        .updateInstalledMessage: "CodexRunway est maintenant à jour.",
        .updateInstalling: "Installation de la mise à jour...",
        .updateLearnMore: "En savoir plus",
        .updateNetworkProxyHint: "Si vous utilisez un proxy système, assurez-vous que github.com et release-assets.githubusercontent.com ne sont pas dans la liste d’exclusion du proxy, ou utilisez le mode TUN.",
        .updateReadyToInstall: "Prêt à installer",
        .updateSigningKeyMissing: "La clé de signature Sparkle n’est pas configurée.",
        .updateSkipVersion: "Ignorer cette version",
        .updateUnavailableInDevelopment: "Les mises à jour ne peuvent pas être installées avec swift run. Utilisez une .app empaquetée ou une build Release pour tester les mises à jour Sparkle.",
        .updateVersionAvailable: "CodexRunway %@ est disponible.",
        .upToDate: "CodexRunway est à jour.",
        .total: "Total",
        .tokens: "Tokens",
        .tokensOnly: "jetons uniquement",
        .testNotification: "Notification de test",
        .testNotificationBody: "Les notifications fonctionnent pour CodexRunway.",
        .testNotificationDevelopmentMode: "Les notifications système nécessitent l’exécution de CodexRunway.app empaqueté. Elles ne peuvent pas être testées depuis swift run.",
        .testNotificationSubtitle: "Demande l’autorisation de notification macOS et envoie une alerte de test.",
        .testNotificationTitle: "Test CodexRunway",
        .threads: "fils",
        .today: "Aujourd’hui",
        .thisMonth: "Ce mois-ci",
        .turns: "tours",
        .unknown: "inconnu",
        .unknownAccount: "Compte inconnu",
        .unknownModels: "Modèles inconnus",
        .unavailableCredits: "Indisponible",
        .usageAnalyticsUnavailable: "Analytique d’usage indisponible",
        .usageAnalyticsEmpty: "Aucun usage dans cette plage",
        .used: "utilisé",
        .usdPerCredit: "USD par crédit",
        .version: "Version",
        .weeklyValueEstimate: "Estimation de la valeur hebdomadaire",
        .weeklyUsage: "Hebdomadaire",
        .widgetAllDevices: "Tous les appareils",
        .widgetBalance: "Solde",
        .widgetCost: "Équivalent API",
        .widgetDataCorrupt: "Les données du widget sont endommagées. Actualisez CodexRunway.",
        .widgetDataOld: "Données anciennes",
        .widgetMetricTitle: "Indicateur clé",
        .widgetNoData: "Ouvrez CodexRunway pour charger les données du widget.",
        .widgetOverviewTitle: "Aperçu des quotas",
        .widgetRefreshInterval: "Actualisation du widget bureau",
        .widgetRefreshIntervalDescription: "CodexRunway demande des mises à jour à cet intervalle pendant l’exécution ; macOS décide du moment où elles apparaissent.",
        .widgetRemaining: "Restant",
        .widgetResetCredits: "Réinit.",
        .widgetResetTodayTitle: "Réinit. du jour",
        .widgetThisMac: "Ce Mac",
        .widgetTokenTrendTitle: "Tendance des jetons",
        .widgetUpdated: "Mis à jour",
        .widgetVersionUnsupported: "Mettez à jour CodexRunway pour lire ces données de widget.",
        .languageTraditionalChinese: "Chinois traditionnel",
        .languageKorean: "Coréen",
        .languageJapanese: "Japonais",
        .languageRussian: "Russe",
        .languageFrench: "Français",
    ]
}
