extension L10n {
    static let ja: [L10nKey: String] = [
        .apiCost: "API 換算コスト",
        .apiCostSummaryRange: "API コスト範囲",
        .apiCostSource: "コストの出典",
        .apiEquivalent: "API 換算",
        .apiTokenPricing: "API トークン価格",
        .appearance: "外観",
        .appearanceDark: "ダーク",
        .appearanceLight: "ライト",
        .appearanceSystem: "システム",
        .auto: "自動",
        .about: "情報",
        .advanced: "詳細",
        .account: "アカウント",
        .accounts: "アカウント",
        .accountsAdd: "アカウントを追加",
        .accountsAddAPIKey: "API Key",
        .accountsAddFile: "ファイルを読み込む",
        .accountsAddLocal: "ローカル auth.json を読み込む",
        .accountsAddOAuth: "ブラウザでサインイン",
        .accountsAddPaste: "トークン / JSON を貼り付け",
        .accountsAPIKeyHint: "OpenAI API キーを貼り付けてください。API アカウントでは ChatGPT のクォータメーターは表示されません。",
        .accountsCurrent: "現在",
        .accountsDelete: "削除",
        .accountsDeleteConfirmMessage: "このアカウントを CodexRunway から削除しますか？現在のアカウントでない限り、公式の Codex ログインは変わりません。",
        .accountsDeleteConfirmTitle: "アカウントを削除しますか？",
        .accountsDeselectAll: "すべて選択解除",
        .accountsEmpty: "管理アカウントはまだありません。ローカルの auth.json を読み込むか、別のアカウントを追加してください。",
        .accountsExport: "書き出す",
        .accountsExportEmpty: "書き出すアカウントがありません。",
        .accountsExportFailed: "書き出しに失敗",
        .accountsExportHint: "現在のプラットフォームで書き出すアカウントを選んでください。ファイルは別の Mac の CodexRunway に読み込めます。",
        .accountsExportSucceeded: "%d 件のアカウントを書き出しました",
        .accountsExportTitle: "アカウントを書き出す",
        .accountsExportWarning: "書き出しファイルにはログイン情報が含まれます。安全に保管・転送してください。",
        .accountsForceCurrent: "環境の現在のログインに強制設定",
        .accountsImportFailed: "読み込みに失敗",
        .accountsImportNoCredentials: "資格情報が見つかりません。auth.json、refresh token、または ChatGPT /auth/session の JSON（accessToken）を貼り付けてください。",
        .accountsImportPreviewHint: "選択したファイルで見つかったアカウントを確認してください。読み込まない項目のチェックを外します。",
        .accountsImportPreviewTitle: "アカウントを読み込む",
        .accountsImportProgress: "読み込み中 %d / %d",
        .accountsImportProviderNotice: "%@ アカウントに読み込みました",
        .accountsImportSelected: "選択した項目を読み込む",
        .accountsImportSucceeded: "%d 件のアカウントを読み込みました",
        .accountsImportWillAdd: "追加されます",
        .accountsImportWillUpdate: "更新されます",
        .accountsUserIdLabel: "ユーザー ID：",
        .accountsWorkspaceIdLabel: "ワークスペース ID：",
        .accountsWorkspaceNameLabel: "ワークスペース：",
        .accountsIsCurrentLogin: "現在の Codex ログインアカウントです",
        .accountsMakeCurrent: "Codex で使う",
        .accountsMoveDown: "下へ",
        .accountsMoveUp: "上へ",
        .accountsNeedsReauth: "再認証が必要",
        .accountsNote: "メモ",
        .accountsOAuthCancelled: "ブラウザのサインインがキャンセルされました。",
        .accountsOAuthFailed: "ブラウザのサインインに失敗",
        .accountsOAuthWaiting: "ブラウザでサインインを完了してください…",
        .accountsPasteFromClipboard: "クリップボードから貼り付け",
        .accountsPasteHint: "refresh token、~/.codex/auth.json、ChatGPT /api/auth/session の JSON、またはアカウントの JSON 配列を貼り付けてください。",
        .accountsRefreshAll: "すべてのクォータを更新",
        .accountsReauthRequired: "再サインイン",
        .accountsRestartCodexAfterSwitch: "切り替え後すぐに Codex を再起動",
        .accountsRestartCodexFailed: "アカウントは切り替えましたが、Codex を再起動できませんでした: %@",
        .accountsRestartCodexSucceeded: "アカウントを切り替えました。Codex を再起動しました。",
        .accountsSelectAll: "すべて選択",
        .accountsSidebarTitle: "アカウント",
        .accountsSwitchConfirmTitle: "アカウントを切り替えますか？",
        .accountsSwitchConfirmMessage: "~/.codex/auth.json を「%@」に置き換え、Codex は再起動後に反映します。",
        .accountsSwitchFailed: "アカウントを切り替えられませんでした",
        .accountsSwitchInvalidCredential: "このアカウントの資格情報が無効または不完全なため、Codex ログインに使えません。",
        .accountsSwitchMissingRefresh: "このアカウントには refresh_token がありません。アクセス トークンが有効な間は切り替えられます。期限切れ後はセッションを再読み込みするか、ブラウザでサインインしてください。",
        .accountsSwitchSessionExpired: "このセッションのアクセス トークンは期限切れで、refresh_token もありません。/auth/session から再読み込みするか、ブラウザでサインインしてください。",
        .accountsSwitching: "アカウントを切り替え中…",
        .accountsSwitchRealHint: "切り替えると選択したアカウントが ~/.codex/auth.json に書き込まれ、Codex CLI と IDE がそれを使います。",
        .alias: "エイリアス",
        .automaticallyCheckForUpdates: "アップデートを自動的に確認",
        .available: "利用可能",
        .availableResets: "利用可能なリセット",
        .back: "戻る",
        .backup: "バックアップ",
        .cachedInput: "キャッシュ済み入力",
        .cachedInputTokens: "キャッシュ済み入力トークン",
        .cancel: "キャンセル",
        .calculate: "計算",
        .calculating: "計算中",
        .codexFolder: "Codex フォルダを開く",
        .controlPanel: "コントロールパネル",
        .calculatedAt: "計算時刻",
        .costShare: "コスト内訳",
        .costScanFailed: "コストスキャンに失敗",
        .costScanPreparing: "使用量スキャンを準備中…",
        .costScanIndexing: "セッションログをインデックス中…",
        .costScanAggregating: "使用量を集計中…",
        .costScanFetchingOnline: "オンライン使用量を取得中…",
        .costScanProgressFiles: "%d / %d ファイル",
        .credit: "クレジット",
        .creditsBalance: "クレジット残高",
        .creditsUsed: "使用済みクレジット",
        .currentCycle: "現在のサイクル",
        .currentCycleAmount: "現在のサイクル金額",
        .customRange: "カスタム",
        .customRangePrompt: "日付範囲を選んでから「計算」をクリック",
        .cycleStarted: "開始",
        .date: "日付",
        .burnRate: "消費速度",
        .duplicate: "重複",
        .duplicateIndexIDs: "重複したインデックス ID",
        .display: "表示",
        .displayAppearanceSection: "外観とメニューバー",
        .endDate: "終了日",
        .estimatedAPICost: "推定 API コスト",
        .expiresRemaining: "残りの有効期間",
        .expiresAt: "期限",
        .expiryRisk: "期限切れリスク",
        .expiringSoon: "まもなく期限切れ",
        .exhaustsIn: "使い切るまで",
        .error: "エラー",
        .exportStatusJSON: "ローカル状態 JSON を書き出す",
        .failed: "失敗",
        .checkForUpdates: "アップデートを確認",
        .fiveHourUsage: "5時間",
        .general: "一般",
        .grokAccountsAddFile: "ファイルを読み込む",
        .grokAccountsAddOAuth: "新しい Grok アカウントでサインイン",
        .grokAccountsAddPaste: "トークン / JSON を貼り付け",
        .grokAccountsCurrent: "現在の Grok アカウント",
        .grokAccountsDeleteConfirmMessage: "このアカウントを CodexRunway から削除しますか？公式の Grok ログインは変わりません。",
        .grokAccountsDeleteConfirmTitle: "Grok アカウントを削除しますか？",
        .grokAccountsEmpty: "管理中の Grok アカウントはまだありません。サインイン、現在の Grok ログインの読み込み、または資格情報の貼り付けを行ってください。",
        .grokAccountsImportNoCredentials: "資格情報が見つかりません。~/.grok/auth.json または Grok の資格情報オブジェクト（key/refresh_token と email、user_id、または principal_id）を貼り付けてください。",
        .grokAccountsImportOfficial: "現在の Grok ログインを読み込む",
        .grokAccountsMakeCurrent: "Grok で使う",
        .grokAccountsPasteHint: "~/.grok/auth.json、単一の Grok OAuth/レガシー資格情報オブジェクト、またはアカウントの JSON 配列を貼り付けてください。API キーのみの資格情報はサポートされません。",
        .grokAccountsRefreshAll: "すべての Grok クォータを更新",
        .grokAccountsRemove: "Grok アカウントを削除",
        .grokAccountsTitle: "Grok アカウント",
        .grokBillingParseFailed: "Grok が未対応の課金応答を返しました。CLI を更新するか、後でもう一度お試しください。",
        .grokBillingPeriod: "課金期間",
        .grokBillingPeriodMonthly: "月次の含まれるクォータ",
        .grokBillingPeriodWeekly: "週次の含まれるクォータ",
        .grokCLIInstallHint: "公式の Grok CLI をインストールし、OAuth でサインインすると課金を確認できます。",
        .grokCLIOpenInstallGuide: "Grok CLI のインストールガイドを開く",
        .grokCLITooOld: "この Grok CLI バージョンは課金に対応していません。CLI を更新して再試行してください。",
        .grokCLIUnavailable: "Grok CLI がインストールされていません",
        .grokCurrentAccountCannotDelete: "現在のアカウントを削除する前に、別の Grok アカウントに切り替えてください。",
        .grokDataSource: "データソース",
        .grokExternalLoginChanged: "別のプロセスが Grok ログインを変更しました。アカウント状態を公式の資格情報から同期しました。",
        .grokImportFailed: "現在の Grok ログインを読み込めませんでした",
        .grokImportSucceeded: "現在の Grok ログインを読み込みました",
        .grokIncludedQuota: "含まれるクォータ",
        .grokIncludedUSD: "含まれる USD クレジット",
        .grokLocalUsage: "ローカルのトークン使用量",
        .grokLocalUsageHint: "この Mac の最近の Grok CLI セッション（turn_completed の使用量）から取得します。",
        .grokLoginCancelled: "Grok のサインインがキャンセルされました。",
        .grokLoginFailed: "Grok のサインインに失敗",
        .grokLoginWaiting: "ブラウザで Grok のサインインを完了してください（デバイス コードのページが自動で開きます）…",
        .grokNoManagedOAuth: "管理可能な OAuth または互換レガシーの Grok ログインが見つかりませんでした。",
        .grokNoQuotaData: "Grok の課金データはまだありません。",
        .grokNotLoggedIn: "Grok にサインインしていません",
        .grokOnDemandLimit: "オンデマンド上限",
        .grokOnDemandUsage: "オンデマンド使用量",
        .grokPlan: "Grok プラン",
        .grokPrepaidBalance: "プリペイド残高",
        .grokProductBuild: "Grok Build",
        .grokProductChat: "Grok Chat",
        .grokProductImagine: "Grok Imagine",
        .grokProductUsage: "プロダクト使用量",
        .grokReauthenticationRequired: "Grok のサインインが期限切れです。再度サインインしてください。",
        .grokRefreshFailed: "Grok の課金を更新できませんでした",
        .grokRefreshCancelled: "Grok の課金更新がキャンセルされました。",
        .grokRefreshTimedOut: "Grok の課金リクエストがタイムアウトしました。",
        .grokRefreshing: "Grok の課金を更新中…",
        .grokResetAt: "リセット",
        .grokSessionsScanned: "%d 件のセッションをスキャン",
        .grokSourceCLI: "Grok CLI 課金 API",
        .grokSourceLocalSessions: "ローカルの Grok セッション",
        .grokSwitchConfirmMessage: "公式の Grok OAuth ログインを「%@」に置き換えますか？新しい Grok セッションだけが確実にこれを使います。",
        .grokSwitchConfirmTitle: "Grok アカウントを切り替えますか？",
        .grokSwitchFailed: "Grok アカウントを切り替えられませんでした",
        .grokSwitchOnlyNewSessions: "アカウントの切り替えは新しい Grok セッションにだけ影響します。",
        .grokSwitchRunningMessage: "1 つ以上の Grok プロセスが実行中です。切り替え後に以前のログインを書き戻す可能性があります。続行すると、新しい Grok セッションだけが選択したアカウントを使うことが保証されます。",
        .grokSwitchRunningTitle: "Grok が実行中です",
        .grokSwitching: "Grok アカウントを切り替え中…",
        .grokUnifiedBilling: "統合課金",
        .grokUpdatedAt: "Grok の課金を更新済み",
        .hours: "時間",
        .modelBreakdown: "モデル別内訳",
        .modelSpecificQuotaUsageDescription: "メニューバーとメインパネルにモデル別クォータの進捗を表示します。",
        .noModelCostData: "モデルのコストデータがありません",
        .nonCachedInput: "非キャッシュ入力",
        .inputShort: "in",
        .inputCachedOutput: "入力 / キャッシュ / 出力",
        .inputTokens: "入力トークン",
        .invalidDateRange: "日付範囲が無効です",
        .language: "言語",
        .languageEnglish: "英語",
        .languageSimplifiedChinese: "簡体字中国語",
        .lastReset: "前回のリセット",
        .lastUpdated: "更新済み",
        .later: "後で",
        .left: "残り",
        .minutes: "分",
        .missing: "欠落",
        .missingFromIndex: "インデックスにありません",
        .nextResetIn: "次のリセット: ",
        .nextExpiry: "次の期限",
        .needsAttention: "要確認",
        .noExpiry: "期限なし",
        .noAvailableResetCredits: "リセットクレジットなし",
        .notLoggedIn: "未サインイン",
        .authExpired: "ログインの期限が切れました。再度サインインするか、有効な refresh_token があるアカウントに切り替えてください。",
        .authFileInvalid: "ローカルの auth.json が無効または不完全です。使えるアカウントを復元するか、再度サインインしてください。",
        .noPreviousIndex: "以前のインデックスなし",
        .notLoaded: "未読み込み",
        .notScanned: "未スキャン",
        .ok: "OK",
        .openControlPanel: "コントロールパネルを開く",
        .openDetailsWindow: "詳細ウィンドウを開く",
        .orphan: "孤立",
        .orphanIndexRows: "孤立したインデックス行",
        .outputTokens: "出力トークン",
        .outputShort: "out",
        .openGithub: "GitHub を開く",
        .tokenComposition: "トークン内訳",
        .feedbackIssue: "フィードバック",
        .historicalUsage: "過去の使用量",
        .privacy: "トークンはこの Mac に留まります。セッション修復はバックアップ作成後にのみローカル インデックスを書き換えます。",
        .plan: "プラン",
        .planAPI: "API",
        .planBusiness: "Business",
        .planEdu: "Edu",
        .planEnterprise: "Enterprise",
        .planFree: "Free",
        .planPlus: "Plus",
        .planPro5x: "Pro 5X",
        .planPro20x: "Pro 20X",
        .planTeam: "Team",
        .planUnknown: "不明",
        .plannedEntries: "予定エントリ",
        .pricingVersion: "価格バージョン",
        .projectBreakdown: "プロジェクト別内訳",
        .projectedAtReset: "リセット時の予測",
        .projectedWeeklyTotal: "週間合計の予測",
        .previousCycle: "前のサイクル",
        .providerCodex: "Codex",
        .providerGrok: "Grok",
        .quota: "クォータ",
        .quotaAlertBody: "%@ の使用量が %@ に達しました。",
        .quotaAlertTitle: "Codex クォータ警告",
        .quotaAlertsDescription: "使用量が 80%、95%、または 100% に達すると通知します。",
        .quotaAlerts: "クォータ通知",
        .quotaEstimate: "週次クォータ推定",
        .quotaEstimateCannotExtrapolate: "週次使用量が足りず推定できません",
        .quotaEstimateCredits: "Credits",
        .quotaEstimateCut: "引き下げの可能性",
        .quotaEstimateHistory: "過去の推定",
        .quotaEstimateIncreased: "前回より増加",
        .quotaEstimateInfo: "公式の使用率と日次 Credits から現在ウィンドウの枠を推定します。使用量と使用率は同じ自動選択ウィンドウに揃えます。換算は 1000 Credits ≈ $40 で非公式です。",
        .quotaEstimateMethodOfficial: "自動ウィンドウ",
        .quotaEstimateMethodRolling: "直近 7 日",
        .quotaEstimateThisWeek: "今週",
        .quotaEstimateThisWeekUsed: "今週の使用量",
        .quotaEstimateUsedPercent: "使用率",
        .quotaEstimateWeekValue: "週次価値（推定）",
        .quotaEstimateWeeklyAllowance: "推定週次枠",
        .quotaEstimateWindowMode: "推定ウィンドウ",
        .quotaEstimateWindowOfficial: "自動ウィンドウ",
        .quotaEstimateWindowRolling: "直近 7 暦日",
        .quotaEstimateVsLast: "前回比",
        .quit: "終了",
        .rawAnalyticsCredits: "生の分析クレジット",
        .rateLimitResetDetectedAlertBody: "本日の Codex クォータ リセットが検出されました。",
        .rateLimitResetDetectedBankedAlertBody: "オンデマンドで使えるリセット回数がリセットバンクに保存されました。現在のクォータは自動では更新されません。",
        .rateLimitResetDetectedGlobalAndBankedAlertBody: "グローバルリセットが完了し、別のリセット回数がオンデマンド用にリセットバンクへ保存されました。バンク分だけでは現在のクォータは更新されません。",
        .rateLimitResetDetectedAlertTitle: "Codex リセットを検出",
        .rateLimitResetDetectedTypedAlertTitle: "Codex %@を確認",
        .rateLimitResetToday: "本日リセット済み？",
        .rateLimitResetTodayAlerts: "本日リセットの通知",
        .rateLimitResetTodayAlertsDescription: "新たに検出されたリセットと、予定リセットが 1 時間または 30 分以内のときに通知します。",
        .rateLimitResetTodayAwaiting: "本日完了または予定のリセットはありません",
        .rateLimitResetTodayBankedCompletedHint: "オンデマンド用の回数がリセットバンクに保存されました。現在のクォータは更新されません",
        .rateLimitResetTodayBankedScheduledHint: "リセットバンクへの付与が本日中に予定されていますが、まだ到着していません",
        .rateLimitResetTodayCheckCost: "確認コスト",
        .rateLimitResetTodayConfidence: "確度",
        .rateLimitResetTodayDescription: "www.codexrunway.com の公開ステータスです。",
        .rateLimitResetTodayEvidenceBankedReset: "蓄積リセットが発表されました。完了したリセットではありません。",
        .rateLimitResetTodayEvidenceBankedCompleted: "オンデマンドで使えるリセットバンク回数の到着が確認されました。",
        .rateLimitResetTodayEvidenceBankedPreview: "文脈から高確率のリセットバンク付与が推定されました。",
        .rateLimitResetTodayEvidenceBankedScheduled: "リセットバンクへの付与が明示的に予定されました。",
        .rateLimitResetTodayEvidenceGlobalAndBankedCompleted: "グローバルリセットとリセットバンクへの付与が確認されました。",
        .rateLimitResetTodayEvidenceGlobalAndBankedPreview: "文脈から高確率のグローバルリセットとリセットバンク付与が推定されました。",
        .rateLimitResetTodayEvidenceGlobalAndBankedScheduled: "グローバルリセットとリセットバンクへの付与が明示的に予定されました。",
        .rateLimitResetTodayEvidenceLimitIncrease: "クォータ上限の引き上げが発表されました。リセットではありません。",
        .rateLimitResetTodayEvidenceResetCompleted: "明示的な Codex クォータ リセットが発表されました。",
        .rateLimitResetTodayEvidenceResetScheduled: "明示的な Codex クォータ リセットが予定されました。",
        .rateLimitResetTodayEvidenceResetPreview: "文脈から高確率の Codex クォータ リセットが推定されました。",
        .rateLimitResetTodayEvidenceManualCompletion: "X の完了投稿なしで確認されました。",
        .rateLimitResetTodayEvidenceOperatorCompletion: "運営側がリセットを確認。Tibo は X に投稿していません。",
        .rateLimitResetTodayEvidenceOperatorScheduled: "運営側がリセット予定を確認。Tibo は X に投稿していません。",
        .rateLimitResetTodayEvidenceUncertain: "明確なリセット信号ではありません。",
        .rateLimitResetTodayLastCheck: "前回の確認",
        .rateLimitResetTodayLastFetched: "前回の更新",
        .rateLimitResetTodayLocalDayHint: "ローカルの暦日を使い、深夜 0 時に切り替わります。",
        .rateLimitResetTodayLatestEvidence: "最新の根拠",
        .rateLimitResetTodayNextScheduled: "次の予想リセット",
        .rateLimitResetTodayNextScheduledWithCountdown: "次の予想リセット: %@ (%@)",
        .rateLimitResetTodayNo: "いいえ",
        .rateLimitResetTodayNoHint: "本日完了または予定のリセットはありません",
        .rateLimitResetTodayNoHintUncertain: "本日の明確なリセット信号はありません",
        .rateLimitResetTodayNoHintUnconfirmedSchedule: "予定されていた{type}の時刻を過ぎましたが、確認はありません",
        .rateLimitResetTodayNoHintWithLast: "本日完了または予定のリセットはありません。前回の{type}は{ago}前",
        .rateLimitResetTodayNoHintWithNext: "本日はリセットなし · 次の予想リセット %@",
        .rateLimitResetTodayOpenSource: "ステータス ページを開く",
        .rateLimitResetTodayOpenWebsite: "CodexRunway のウェブでリセット状況と履歴を見る",
        .rateLimitResetTodayOpenEvidence: "X の出典を開く",
        .rateLimitResetTodayResetAgo: "%@ 前にリセット",
        .rateLimitResetTodayUntilReset: "リセットまで %@",
        .rateLimitResetTodayPlanAll: "すべてのプラン",
        .rateLimitResetTodayPlanBusiness: "Business",
        .rateLimitResetTodayPlanEnterprise: "Enterprise",
        .rateLimitResetTodayPlanFree: "Free",
        .rateLimitResetTodayPlanPlus: "Plus",
        .rateLimitResetTodayPlanPro: "Pro",
        .rateLimitResetTodayPlanTeam: "Team",
        .rateLimitResetTodayPlanUnknown: "プラン未指定",
        .rateLimitResetTodayPlans: "プラン",
        .rateLimitResetTodayRefreshInterval: "リセット状態の更新",
        .rateLimitResetTodayReactionPlease: "リセット希望",
        .rateLimitResetTodayReactionThank: "ありがとう",
        .rateLimitResetTodayReactionPleaseAria: "リセット希望、現在 %@",
        .rateLimitResetTodayReactionThankAria: "リセットへの感謝、現在 %@",
        .rateLimitResetTodayReactionLimitReached: "本日の回数上限に達しました",
        .rateLimitResetTodaySeen: "確認済み",
        .rateLimitResetTodaySource: "CodexRunway リセット状態",
        .rateLimitResetTodaySourceInfo: "CodexRunway は、公開 X 発表を AI で分析するホスト型モニターからこのステータスを公開します。AI の結果は不完全または不正確な場合があります。",
        .rateLimitResetTodaySourceTitle: "データソース",
        .rateLimitResetTodayGlobalAndBankedCompletedHint: "グローバルクォータをリセットし、別の回数をオンデマンド用にリセットバンクへ保存しました",
        .rateLimitResetTodayGlobalAndBankedScheduledHint: "グローバルリセットとリセットバンクへの付与が本日中に予定されていますが、まだ実施されていません",
        .rateLimitResetTypeBanked: "リセットバンク",
        .rateLimitResetTypeGlobal: "グローバルリセット",
        .rateLimitResetTypeGlobalAndBanked: "グローバルリセット + リセットバンク",
        .rateLimitResetTodayUnknown: "—",
        .rateLimitResetTodayUnknownHint: "ステータスが利用できないか古いです",
        .rateLimitResetTodayVerdict: "判定",
        .rateLimitResetTodayWindowFiveHour: "5 時間ウィンドウ",
        .rateLimitResetTodayWindowUnknown: "ウィンドウ未指定",
        .rateLimitResetTodayWindowWeekly: "週間上限",
        .rateLimitResetTodayWindows: "上限ウィンドウ",
        .rateLimitResetTodayYes: "はい",
        .rateLimitResetTodayYesHint: "上限は本日リセット済みです",
        .rateLimitResetTodayYesHintWithTime: "本日リセット · %@",
        .rateLimitResetTodayYesHintScheduled: "グローバルリセットは本日中に予定されていますが、まだ完了していません",
        .rateLimitResetTodayYesHintScheduledWithTime: "本日予定・未完了 · %@",
        .rateLimitResetTodayPercentPrefix: "≥%@%%",
        .rateLimitResetTodayPercentExact: "%@%%",
        .rateLimitResetTodayClockLocal: "現地時間",
        .rateLimitResetTodayConfirmedWhen: "%@（%@前）",
        .rateLimitResetTodayConfirmedHint:
            "本日、完了した{type}を確認しました。信頼度は約{percent}です。{zone}のリセット時刻は{when}",
        .rateLimitResetTodayConfirmedHintNoPercent:
            "本日、完了した{type}を確認しました。{zone}のリセット時刻は{when}",
        .rateLimitResetTodayScheduledChanceHint:
            "約{percent}の確率で{type}が行われます。現在予定済みです。おおよそのリセット時間帯（{zone}）：{date}",
        .rateLimitResetUpcomingAlertBody1h: "予定の Codex リセットまで 1 時間を切っています。",
        .rateLimitResetUpcomingAlertBody30m: "予定の Codex リセットまで 30 分を切っています。",
        .rateLimitResetUpcomingRangeAlertBody: "予想リセットウィンドウ: %@。",
        .rateLimitResetUpcomingRangeAlertTitle: "予想 Codex リセットウィンドウ",
        .rateLimitResetUpcomingAlertTitle: "Codex リセットが近づいています",
        .rateLimitResetUpcomingTypedAlertTitle: "Codex %@が近づいています",
        .rateLimitResetUpcomingTypedRangeAlertTitle: "Codex %@の予想時間帯",
        .recent: "最近",
        .recentSessionsDescription: "有効にするとローカル セッションをスキャンします。",
        .refresh: "更新",
        .refreshInterval: "更新間隔",
        .rebuilt: "再構築済み",
        .repair: "修復",
        .repairConfirmMessage: "CodexRunway はローカルのセッション ファイルから ~/.codex/session_index.jsonl を再構築します。書き込み前にインデックスの横にタイムスタンプ付きバックアップが作られます。セッション ログ、auth.json、グローバル状態は変更しません。",
        .repairConfirmTitle: "Codex セッション インデックスを修復しますか？",
        .repairFailed: "修復に失敗",
        .repairIndex: "インデックスを修復",
        .resetsIn: "リセットまで",
        .resetCredits: "リセットクレジット",
        .resetCreditAlertBody: "リセットクレジットの期限が近づいています。",
        .resetCreditAlertTitle: "リセットクレジットの期限切れ",
        .resetCreditAlertsDescription: "利用可能なリセットクレジットが 7 日以内に期限切れになると通知します。",
        .resetCreditAlerts: "リセットクレジット通知",
        .resetCreditDetails: "リセットクレジットの詳細",
        .restoreDefaultOrder: "デフォルトの順序に戻す",
        .runway: "Runway",
        .seconds: "秒",
        .sessionRepair: "セッション修復",
        .sessionScanFailed: "セッションスキャンに失敗",
        .recentSessions: "最近のセッション",
        .settings: "設定",
        .selfCheck: "セルフチェック",
        .showDetails: "詳細を表示",
        .showCostSummary: "API コスト概要を表示",
        .showModelSpecificQuotaUsage: "モデル別クォータ使用量を表示",
        .showRateLimitResetToday: "本日リセット状態を表示",
        .showRecentSessions: "最近のセッションを表示",
        .showSessionRepairSummary: "セッション修復の概要を表示",
        .showTokenUsageHeatmap: "トークン使用量を表示",
        .mainPanelModules: "メインパネルのモジュール",
        .mainPanelModulesDescription: "表示するモジュールを選び、順序を並べ替えます。非表示のモジュールも位置は保たれます。",
        .moduleAPICostDescription: "ローカル セッションの API 換算コスト見積もり。",
        .moduleAppliesCodex: "Codex",
        .moduleAppliesBoth: "Codex & Grok",
        .moduleHidden: "非表示",
        .moduleQuotaDescription: "クォータメーターとモデル別上限。",
        .moduleQuotaEstimateDescription: "利用履歴から今週の枠を推定し、公式の引き下げを確認します。",
        .moduleResetCreditsDescription: "利用可能なリセットクレジットと期限の詳細。",
        .moduleSessionRepairDescription: "ローカル セッション インデックスの状態と修復ツール。",
        .moduleVisible: "表示",
        .notificationSettings: "通知",
        .tokenUsageHeatmap: "トークン使用量",
        .tokenUsageHeatmapDescription: "年初来のトークン使用量チャート（ヒートマップ、折れ線、棒）。",
        .tokenUsageHeatmapUnavailable: "トークン使用量は一時的に利用できません",
        .tokenUsageChartStyle: "チャートのスタイル",
        .tokenUsageChartHeatmap: "ヒートマップ",
        .tokenUsageChartLine: "折れ線",
        .tokenUsageChartBar: "棒",
        .heatmapDaily: "日次",
        .heatmapWeekly: "週次",
        .heatmapCumulative: "累計",
        .heatmapMonthly: "月次",
        .heatmapEmpty: "今年はまだトークン使用がありません",
        .heatmapAllDevices: "公式統計（全デバイス）",
        .heatmapLocalDevice: "ローカルログ（全セッション）",
        .heatmapLocalShort: "ローカル",
        .heatmapOfficialAsOf: "公式集計日 %@",
        .heatmapSourceDisclosure: "公式統計は遅延したり改訂されたりすることがあります。ローカル ログはこの Mac で見えるすべてのセッションを含み、複数アカウントにまたがる場合があります。日別データには UTC 日付を使用します。",
        .heatmapSourceMismatch: "出典が異なります。包含関係として比較できません。",
        .sourceLocalSessions: "ローカルセッション",
        .sourceOnlineSupplement: "オンライン補完",
        .staleTitles: "古いタイトル",
        .status: "ステータス",
        .subscriptionExpired: "期限切れ",
        .subscriptionExpires: "有効期限",
        .subscriptionExpiringSoon: "まもなく期限切れ",
        .statusAvailable: "利用可能",
        .statusError: "エラー",
        .statusLogin: "ログイン",
        .statusBarBattery: "カウントダウン付きバッテリー",
        .statusBarBatteryDetailCountdown: "リセットのカウントダウン",
        .statusBarBatteryDetailRemainingPercent: "残りのパーセント",
        .statusBarBatteryDetailStyle: "バッテリー中央のテキスト",
        .statusBarBatteryScope: "バッテリーのクォータ",
        .statusBarBatteryScopeBoth: "すべて表示",
        .statusBarBatteryScopeFiveHour: "5時間",
        .statusBarBatteryScopeWeekly: "週間",
        .statusBarCountdown: "カウントダウン",
        .statusBarMetersDetailResetTime: "リセット時刻",
        .statusBarMetersDetailRemainingPercent: "残りのパーセント",
        .statusBarMetersDetailBoth: "両方",
        .statusBarMetersDetailStyle: "クォータバーの詳細",
        .statusBarMeters: "クォータバー",
        .statusBarProviderScope: "ステータスバーのプラットフォーム",
        .statusBarProviderScopeBoth: "Codex + Grok",
        .statusBarProviderScopeSelected: "現在のパネルに合わせる",
        .statusBarRings: "クォータリング",
        .statusBarStyle: "メニューバーのスタイル",
        .statusBarText: "進捗テキスト",
        .statusUsed: "使用済み",
        .statusWait: "待機",
        .statusUnknown: "不明",
        .startDate: "開始日",
        .updateAvailable: "アップデートがあります",
        .updateCheckFailed: "アップデート確認に失敗",
        .updateChecking: "アップデートを確認中...",
        .updateDownloadAndInstall: "ダウンロードしてインストール",
        .updateDownloadedReady: "CodexRunway %@ をダウンロード済みで、インストールできます。",
        .updateDownloading: "アップデートをダウンロード中...",
        .updateExtracting: "アップデートを展開中...",
        .updateInstallAndRelaunch: "インストールして再起動",
        .updateInstallLater: "後で",
        .updateInstalled: "アップデートをインストール済み",
        .updateInstalledMessage: "CodexRunway は更新されました。",
        .updateInstalling: "アップデートをインストール中...",
        .updateLearnMore: "詳細",
        .updateNetworkProxyHint: "システムプロキシを使う場合は、github.com と release-assets.githubusercontent.com がシステムのプロキシ除外リストにないことを確認するか、TUN モードを使ってください。",
        .updateReadyToInstall: "インストール準備完了",
        .updateSigningKeyMissing: "Sparkle の署名キーが設定されていません。",
        .updateSkipVersion: "このバージョンをスキップ",
        .updateUnavailableInDevelopment: "swift run で実行中はアップデートをインストールできません。Sparkle のアップデートをテストするには、パッケージ済みの .app または Release ビルドを使ってください。",
        .updateVersionAvailable: "CodexRunway %@ が利用できます。",
        .upToDate: "CodexRunway は最新です。",
        .total: "合計",
        .totalRemaining: "残りの合計",
        .tokens: "Tokens",
        .tokensOnly: "トークンのみ",
        .testNotification: "テスト通知",
        .testNotificationBody: "CodexRunway の通知は正常に表示されます。",
        .testNotificationDevelopmentMode: "システム通知にはパッケージ済みの CodexRunway.app の実行が必要です。swift run からはテストできません。",
        .testNotificationSubtitle: "macOS の通知許可を要求し、テスト通知を送ります。",
        .testNotificationTitle: "CodexRunway テスト",
        .threads: "スレッド",
        .today: "今日",
        .thisMonth: "今月",
        .turns: "ターン",
        .unknown: "不明",
        .unknownAccount: "不明なアカウント",
        .unknownModels: "不明なモデル",
        .unavailableCredits: "利用不可",
        .usageAnalyticsUnavailable: "使用量分析は利用できません",
        .usageAnalyticsEmpty: "この範囲に使用量はありません",
        .used: "使用済み",
        .usdPerCredit: "クレジットあたりの USD",
        .version: "バージョン",
        .weeklyValueEstimate: "週間価値の見積もり",
        .weeklyUsage: "週間",
        .widgetAllDevices: "すべてのデバイス",
        .widgetBalance: "残高",
        .widgetCost: "API 換算",
        .widgetDataCorrupt: "ウィジェットデータが壊れています。CodexRunway を更新してください。",
        .widgetDataOld: "データが古いです",
        .widgetMetricTitle: "主要指標",
        .widgetNoData: "ウィジェットデータを読み込むには CodexRunway を開いてください。",
        .widgetOverviewTitle: "クォータ概要",
        .widgetRefreshInterval: "デスクトップウィジェットの更新",
        .widgetRefreshIntervalDescription: "CodexRunway は実行中にこの間隔で更新を要求します。実際の表示タイミングは macOS が決めます。",
        .widgetRemaining: "残り",
        .widgetResetCredits: "リセット",
        .widgetResetTodayTitle: "本日のリセット",
        .widgetThisMac: "この Mac",
        .widgetTokenTrendTitle: "トークンの推移",
        .widgetUpdated: "更新済み",
        .widgetVersionUnsupported: "このウィジェットデータを読むには CodexRunway を更新してください。",
        .languageTraditionalChinese: "繁体字中国語",
        .languageKorean: "韓国語",
        .languageJapanese: "日本語",
        .languageRussian: "ロシア語",
        .languageFrench: "フランス語",
    ]
}
