extension L10n {
    static let zhHant: [L10nKey: String] = [
        .apiCost: "API 等价成本",
        .apiCostSummaryRange: "API 成本範圍",
        .apiCostSource: "成本來源",
        .apiEquivalent: "API 等价",
        .apiTokenPricing: "API token 价格",
        .appearance: "外觀",
        .appearanceDark: "深色",
        .appearanceLight: "淺色",
        .appearanceSystem: "跟隨系統",
        .auto: "自動",
        .about: "關於",
        .advanced: "進階",
        .account: "帳號",
        .accounts: "多帳號",
        .accountsAdd: "新增帳號",
        .accountsAddAPIKey: "API Key",
        .accountsAddFile: "匯入檔案",
        .accountsAddLocal: "匯入本機 auth.json",
        .accountsAddOAuth: "瀏覽器登入",
        .accountsAddPaste: "貼上 Token / JSON",
        .accountsAPIKeyHint: "貼上 OpenAI API Key。API 帳號不會顯示 ChatGPT 額度進度條。",
        .accountsCurrent: "目前",
        .accountsDelete: "移除",
        .accountsDeleteConfirmMessage: "从 CodexRunway 移除此帳號？除非它是目前帳號，否則不會改動官方 Codex 登入。",
        .accountsDeleteConfirmTitle: "移除帳號？",
        .accountsDeselectAll: "取消全選",
        .accountsEmpty: "還沒有托管帳號。請先匯入本機 auth.json，或新增其他帳號。",
        .accountsExport: "匯出",
        .accountsExportEmpty: "沒有可匯出的帳號。",
        .accountsExportFailed: "匯出失敗",
        .accountsExportHint: "選擇要匯出的目前平台帳號。匯出檔案可在另一台 Mac 的 CodexRunway 中匯入。",
        .accountsExportSucceeded: "已匯出 %d 个帳號",
        .accountsExportTitle: "匯出帳號",
        .accountsExportWarning: "匯出檔案包含登入憑證，請妥善保管与傳輸。",
        .accountsForceCurrent: "強制設為環境目前帳號",
        .accountsImportFailed: "匯入失敗",
        .accountsImportNoCredentials: "未識別到憑證。請貼上 auth.json、refresh token，或 ChatGPT /auth/session 的 JSON（含 accessToken）。",
        .accountsImportPreviewHint: "以下是从所選檔案解析到的帳號，可取消勾選不需要匯入的項。",
        .accountsImportPreviewTitle: "匯入帳號",
        .accountsImportProgress: "正在匯入 %d / %d",
        .accountsImportProviderNotice: "已匯入到 %@ 帳號庫",
        .accountsImportSelected: "匯入選中",
        .accountsImportSucceeded: "已匯入 %d 个帳號",
        .accountsImportWillAdd: "將新增",
        .accountsImportWillUpdate: "將更新",
        .accountsUserIdLabel: "使用者 ID：",
        .accountsWorkspaceIdLabel: "工作區 ID：",
        .accountsWorkspaceNameLabel: "工作區：",
        .accountsIsCurrentLogin: "為目前 Codex 的登入帳號",
        .accountsMakeCurrent: "設為目前",
        .accountsMoveDown: "下移",
        .accountsMoveUp: "上移",
        .accountsNeedsReauth: "需要重新登入",
        .accountsNote: "備注",
        .accountsOAuthCancelled: "已取消瀏覽器登入。",
        .accountsOAuthFailed: "瀏覽器登入失敗",
        .accountsOAuthWaiting: "請在瀏覽器中完成登入…",
        .accountsPasteFromClipboard: "从剪貼板貼上",
        .accountsPasteHint: "貼上 refresh token、~/.codex/auth.json、ChatGPT /api/auth/session JSON，或帳號 JSON 數組。",
        .accountsRefreshAll: "全部重新整理額度",
        .accountsReauthRequired: "請重新登入",
        .accountsRestartCodexAfterSwitch: "切換後立即重新啟動 Codex",
        .accountsRestartCodexFailed: "帳號已切換，但重新啟動 Codex 失敗：%@",
        .accountsRestartCodexSucceeded: "帳號已切換，並已重新啟動 Codex。",
        .accountsSelectAll: "全選",
        .accountsSidebarTitle: "帳號",
        .accountsSwitchConfirmTitle: "切換帳號？",
        .accountsSwitchConfirmMessage: "將使用「%@」覆蓋 ~/.codex/auth.json，需重新啟動 Codex 後才會生效。",
        .accountsSwitchFailed: "切換帳號失敗",
        .accountsSwitchInvalidCredential: "該帳號憑證無效或不完整，不能作為 Codex 登入帳號。",
        .accountsSwitchMissingRefresh: "該帳號沒有 refresh_token。access_token 仍有效時可切換；過期後請重新匯入 /auth/session 或使用瀏覽器登入。",
        .accountsSwitchSessionExpired: "該 session 的 access_token 已過期，且沒有 refresh_token，無法切換。請重新从 /auth/session 匯入，或使用瀏覽器登入。",
        .accountsSwitching: "正在切換帳號…",
        .accountsSwitchRealHint: "切換會將選中帳號寫入 ~/.codex/auth.json，Codex CLI 与 IDE 會同步使用。",
        .alias: "別名",
        .automaticallyCheckForUpdates: "自動檢查更新",
        .available: "可用",
        .availableResets: "可用重置",
        .back: "返回",
        .backup: "備份",
        .cachedInput: "快取輸入",
        .cachedInputTokens: "快取輸入 tokens",
        .cancel: "取消",
        .calculate: "計算",
        .calculating: "計算中",
        .codexFolder: "開啟 Codex 檔案夾",
        .controlPanel: "控制台",
        .calculatedAt: "計算于",
        .costShare: "成本佔比",
        .costScanFailed: "費用掃描失敗",
        .costScanPreparing: "正在準備用量掃描…",
        .costScanIndexing: "正在索引工作階段日誌…",
        .costScanAggregating: "正在匯總用量…",
        .costScanFetchingOnline: "正在請求線上用量…",
        .costScanProgressFiles: "%d / %d 个檔案",
        .credit: "次數",
        .creditsBalance: "Credits 餘額",
        .creditsUsed: "已用 Credits",
        .currentCycle: "本週期",
        .currentCycleAmount: "本週期金額",
        .customRange: "自訂",
        .customRangePrompt: "請選擇日期，然後點一下計算",
        .cycleStarted: "始于",
        .date: "日期",
        .burnRate: "消耗速度",
        .duplicate: "重復",
        .duplicateIndexIDs: "重復索引 ID",
        .display: "顯示",
        .displayAppearanceSection: "外觀与選單列",
        .mainPanelBackground: "彈窗背景",
        .mainPanelBackgroundDescription: "半透明會透出彈窗後方的視窗。",
        .mainPanelBackgroundOpaque: "不透明",
        .mainPanelBackgroundTranslucent: "半透明",
        .endDate: "結束日期",
        .estimatedAPICost: "估算 API 成本",
        .expiresRemaining: "有效期剩餘",
        .expiresAt: "到期時間",
        .expiryRisk: "到期風險",
        .expiringSoon: "即將過期",
        .exhaustsIn: "預計耗盡于",
        .error: "錯誤",
        .exportStatusJSON: "匯出本機狀態 JSON",
        .failed: "失敗",
        .checkForUpdates: "檢查更新",
        .fiveHourUsage: "5小時",
        .general: "通用",
        .grokAccountsAddFile: "匯入檔案",
        .grokAccountsAddOAuth: "登入新的 Grok 帳號",
        .grokAccountsAddPaste: "貼上 Token / JSON",
        .grokAccountsCurrent: "目前 Grok 帳號",
        .grokAccountsDeleteConfirmMessage: "从 CodexRunway 移除此帳號？官方 Grok 登入不會改變。",
        .grokAccountsDeleteConfirmTitle: "移除 Grok 帳號？",
        .grokAccountsEmpty: "還沒有托管的 Grok 帳號。請登入、匯入目前 Grok 登入，或貼上憑證。",
        .grokAccountsImportNoCredentials: "未識別到憑證。請貼上 ~/.grok/auth.json，或 Grok 憑證對象（含 key/refresh_token，以及 email、user_id 或 principal_id）。",
        .grokAccountsImportOfficial: "匯入目前 Grok 登入",
        .grokAccountsMakeCurrent: "設為 Grok 目前帳號",
        .grokAccountsPasteHint: "貼上 ~/.grok/auth.json、單个 Grok OAuth/legacy 憑證對象，或帳號 JSON 數組。仅含 API Key 的憑證不受支持。",
        .grokAccountsRefreshAll: "全部重新整理 Grok 額度",
        .grokAccountsRemove: "移除 Grok 帳號",
        .grokAccountsTitle: "Grok 帳號",
        .grokBillingParseFailed: "Grok 返回了不支持的帳單結構。請更新 CLI，或稍後重試。",
        .grokBillingPeriod: "帳單週期",
        .grokBillingPeriodMonthly: "月度包含額度",
        .grokBillingPeriodWeekly: "週度包含額度",
        .grokCLIInstallHint: "請先安裝官方 Grok CLI，再使用 OAuth 登入以查看額度。",
        .grokCLIOpenInstallGuide: "開啟 Grok CLI 安裝說明",
        .grokCLITooOld: "目前 Grok CLI 版本不支持帳單查詢。請更新 CLI 後重試。",
        .grokCLIUnavailable: "未安裝 Grok CLI",
        .grokCurrentAccountCannotDelete: "請先切換到其他 Grok 帳號，再移除目前帳號。",
        .grokDataSource: "資料來源",
        .grokExternalLoginChanged: "Grok 登入已被其他進程改變，帳號狀態已按官方憑證同步。",
        .grokImportFailed: "匯入目前 Grok 登入失敗",
        .grokImportSucceeded: "已匯入目前 Grok 登入",
        .grokIncludedQuota: "包含額度",
        .grokIncludedUSD: "包含美金額度",
        .grokLocalUsage: "本機 Token 用量",
        .grokLocalUsageHint: "來自本機最近 Grok CLI 工作階段（turn_completed 用量）。",
        .grokLoginCancelled: "已取消 Grok 登入。",
        .grokLoginFailed: "Grok 登入失敗",
        .grokLoginWaiting: "請在瀏覽器中完成 Grok 登入（將自動開啟裝置授權頁）…",
        .grokNoManagedOAuth: "沒有找到可托管的 OAuth 或兼容 legacy Grok 登入。",
        .grokNoQuotaData: "暫無 Grok 額度資料。",
        .grokNotLoggedIn: "Grok 未登入",
        .grokOnDemandLimit: "按需使用上限",
        .grokOnDemandUsage: "按需使用",
        .grokPlan: "Grok 套餐",
        .grokPrepaidBalance: "預付餘額",
        .grokProductBuild: "Grok Build",
        .grokProductChat: "Grok Chat",
        .grokProductImagine: "Grok Imagine",
        .grokProductUsage: "产品用量",
        .grokReauthenticationRequired: "Grok 登入已失效，請重新登入。",
        .grokRefreshFailed: "Grok 額度重新整理失敗",
        .grokRefreshCancelled: "已取消 Grok 額度重新整理。",
        .grokRefreshTimedOut: "Grok 額度重新整理超時。",
        .grokRefreshing: "正在重新整理 Grok 額度…",
        .grokResetAt: "重置時間",
        .grokSessionsScanned: "已掃描 %d 个工作階段",
        .grokSourceCLI: "Grok CLI 帳單 API",
        .grokSourceLocalSessions: "本機 Grok 工作階段",
        .grokSwitchConfirmMessage: "將官方 Grok OAuth 登入切換為「%@」？仅保證新的 Grok 工作階段使用該帳號。",
        .grokSwitchConfirmTitle: "切換 Grok 帳號？",
        .grokSwitchFailed: "Grok 帳號切換失敗",
        .grokSwitchOnlyNewSessions: "帳號切換只影響新的 Grok 工作階段。",
        .grokSwitchRunningMessage: "檢測到仍在運行的 Grok 進程。切換後，這些進程可能把舊登入重新寫回；繼續操作只保證新的 Grok 工作階段使用所選帳號。",
        .grokSwitchRunningTitle: "Grok 正在運行",
        .grokSwitching: "正在切換 Grok 帳號…",
        .grokUnifiedBilling: "統一計費",
        .grokUpdatedAt: "Grok 額度更新于",
        .hours: "小時",
        .modelBreakdown: "模型明細",
        .modelSpecificQuotaUsageDescription: "在選單列和主面板中顯示特有模型的獨立額度進度。",
        .noModelCostData: "暫無模型成本資料",
        .nonCachedInput: "非快取輸入",
        .inputShort: "輸入",
        .inputCachedOutput: "輸入 / 快取 / 輸出",
        .inputTokens: "輸入 tokens",
        .invalidDateRange: "日期範圍無效",
        .language: "語言",
        .languageEnglish: "英文",
        .languageSimplifiedChinese: "簡體中文",
        .lastReset: "上次重置",
        .lastUpdated: "更新于",
        .later: "後",
        .left: "剩餘",
        .minutes: "分鐘",
        .missing: "缺失",
        .missingFromIndex: "索引缺失",
        .nextResetIn: "下次重置于：",
        .nextExpiry: "最近到期",
        .needsAttention: "需要處理",
        .noExpiry: "無到期時間",
        .noAvailableResetCredits: "無可用重置次數",
        .notLoggedIn: "未登入",
        .authExpired: "登入已失效。請重新登入，或切換到含有效 refresh_token 的帳號。",
        .authFileInvalid: "本機 auth.json 無效或不完整。請恢復可用帳號，或重新登入。",
        .noPreviousIndex: "沒有舊索引",
        .notLoaded: "未載入",
        .notScanned: "未掃描",
        .ok: "好",
        .openControlPanel: "開啟控制台",
        .openDetailsWindow: "開啟詳細資料視窗",
        .orphan: "孤立",
        .orphanIndexRows: "孤立索引行",
        .outputTokens: "輸出 tokens",
        .outputShort: "輸出",
        .openGithub: "開啟 GitHub",
        .tokenComposition: "Tokens 組成",
        .feedbackIssue: "反饋建議",
        .historicalUsage: "歷史記錄",
        .privacy: "Token 只保留在本機。工作階段修復只會在創建備份後重建本機索引。",
        .plan: "套餐",
        .planAPI: "API",
        .planBusiness: "Business",
        .planEdu: "Edu",
        .planEnterprise: "Enterprise",
        .planFree: "Free",
        .planPlus: "Plus",
        .planPro5x: "Pro 5X",
        .planPro20x: "Pro 20X",
        .planTeam: "Team",
        .planUnknown: "Unknown",
        .plannedEntries: "計劃寫入條目",
        .pricingVersion: "价格版本",
        .projectBreakdown: "專案明細",
        .projectedAtReset: "重置時預計",
        .projectedWeeklyTotal: "推算週總額",
        .previousCycle: "上个週期",
        .providerCodex: "Codex",
        .providerGrok: "Grok",
        .quota: "配額",
        .quotaAlertBody: "%@ 已達到 %@ 用量。",
        .quotaAlertTitle: "Codex 配額提醒",
        .quotaAlertsDescription: "用量達到 80%、95% 或 100% 時提醒。",
        .quotaAlerts: "配額提醒",
        .quotaEstimate: "訂閱額度推算",
        .quotaEstimateCannotExtrapolate: "本週用量不足，暫無法推算",
        .quotaEstimateCredits: "Credits",
        .quotaEstimateCut: "可能被下調",
        .quotaEstimateHistory: "歷次推算",
        .quotaEstimateIncreased: "較上次上調",
        .quotaEstimateInfo: "使用官方占用率和每日 Credits 推算額度；1000 Credits ≈ $40 僅為非官方換算，與明細中的 Token 參考價成本不同；每日彙總無法精確切分配額窗口邊界，結果僅供參考",
        .quotaEstimateMethodOfficial: "自動窗口",
        .quotaEstimateMethodRolling: "最近 7 天",
        .quotaEstimateMissingCredits: "官方統計未提供完整 Credits，目前無法推算",
        .quotaEstimateNoUsage: "目前窗口尚無用量，暫時無法推算",
        .quotaEstimateShowingPreviousData: "重新整理失敗，正在顯示上次取得的資料",
        .quotaEstimateStatsThrough: "統計截至 %@",
        .quotaEstimateUnavailableWindow: "目前沒有可用於推算的配額窗口",
        .quotaEstimateZeroCreditsWithUsage: "官方統計已記錄 Token 用量，但 Credits 回傳 0，目前無法推算",
        .quotaEstimateZeroPercent: "目前占用率為 0%，暫時無法推算",
        .quotaEstimateThisWeek: "本週明細",
        .quotaEstimateThisWeekUsed: "本週已用",
        .quotaEstimateUsedPercent: "已用比例",
        .quotaEstimateWeekValue: "週價值（估算）",
        .quotaEstimateWeeklyAllowance: "推算週額度",
        .quotaEstimateWindowMode: "推算窗口",
        .quotaEstimateWindowOfficial: "自動窗口",
        .quotaEstimateWindowRolling: "最近 7 個自然日",
        .quotaEstimateVsLast: "較上次",
        .quit: "退出",
        .rawAnalyticsCredits: "原始 analytics Credits",
        .rateLimitResetDetectedAlertBody: "剛剛檢測到今日 Codex 配額已重置。",
        .rateLimitResetDetectedBankedAlertBody: "一個可按需使用的重置次數已存入重置銀行，不會自動重新整理目前配額。",
        .rateLimitResetDetectedGlobalAndBankedAlertBody: "全域重置已完成；另有一個可按需使用的次數存入重置銀行，銀行額度本身不會自動重新整理目前配額。",
        .rateLimitResetDetectedAlertTitle: "檢測到 Codex 重置",
        .rateLimitResetDetectedTypedAlertTitle: "Codex %@已確認",
        .rateLimitResetToday: "今日是否重置",
        .rateLimitResetTodayAlerts: "重置提醒",
        .rateLimitResetTodayAlertsDescription: "新檢測到重置時提醒；計劃重置不足 1 小時或 30 分鐘時也會提醒。",
        .rateLimitResetTodayAwaiting: "今日沒有已完成或已排期的重置",
        .rateLimitResetTodayBankedCompletedHint: "重置次數已存入重置銀行，可按需使用；不會自動重新整理目前配額",
        .rateLimitResetTodayBankedScheduledHint: "今日稍後有重置銀行到帳排期，目前尚未到帳",
        .rateLimitResetTodayCheckCost: "檢查成本",
        .rateLimitResetTodayConfidence: "置信度",
        .rateLimitResetTodayDescription: "資料來自 www.codexrunway.com。",
        .rateLimitResetTodayEvidenceBankedReset: "公告涉及 banked reset，不代表已完成重置。",
        .rateLimitResetTodayEvidenceBankedCompleted: "已確認重置銀行額度到帳，可按需使用。",
        .rateLimitResetTodayEvidenceBankedPreview: "根據上下文推斷出高概率的重置銀行額度預告。",
        .rateLimitResetTodayEvidenceBankedScheduled: "發現明確的重置銀行到帳安排。",
        .rateLimitResetTodayEvidenceGlobalAndBankedCompleted: "已確認全域重置完成，並有額度存入重置銀行。",
        .rateLimitResetTodayEvidenceGlobalAndBankedPreview: "根據上下文推斷出高概率的全域重置及重置銀行預告。",
        .rateLimitResetTodayEvidenceGlobalAndBankedScheduled: "發現明確的全域重置及重置銀行到帳安排。",
        .rateLimitResetTodayEvidenceLimitIncrease: "公告涉及提高配額，不代表發生重置。",
        .rateLimitResetTodayEvidenceResetCompleted: "發現明確的 Codex 配額重置公告。",
        .rateLimitResetTodayEvidenceResetScheduled: "發現明確的 Codex 配額重置安排。",
        .rateLimitResetTodayEvidenceResetPreview: "根據上下文推斷出高概率的 Codex 配額重置預告。",
        .rateLimitResetTodayEvidenceManualCompletion: "已確認發生重置，但沒有對應的 X 完成帖。",
        .rateLimitResetTodayEvidenceOperatorCompletion: "營運確認已重置，Tibo 未發 X。",
        .rateLimitResetTodayEvidenceOperatorScheduled: "營運確認已排期重置，Tibo 未發 X。",
        .rateLimitResetTodayEvidenceUncertain: "不是明確的重置信號。",
        .rateLimitResetTodayLastCheck: "最近檢查",
        .rateLimitResetTodayLastFetched: "最後重新整理",
        .rateLimitResetTodayLocalDayHint: "按本機時區的自然日計算，午夜切換。",
        .rateLimitResetTodayLatestEvidence: "最近依據",
        .rateLimitResetTodayNextScheduled: "預計下次重置",
        .rateLimitResetTodayNextScheduledWithCountdown: "預計下次重置：%@（%@）",
        .rateLimitResetTodayNo: "否",
        .rateLimitResetTodayNoHint: "今日暫無已完成或已排期的重置",
        .rateLimitResetTodayNoHintUncertain: "今日無明確的重置信號",
        .rateLimitResetTodayNoHintUnconfirmedSchedule: "已排期的{type}時間已過，但未得到確認",
        .rateLimitResetTodayNoHintWithLast: "今日暫無已完成或已排期的重置，上次發生{type}為{ago}之前",
        .rateLimitResetTodayNoHintWithNext: "今日沒有重置 · 預計下次重置 %@",
        .rateLimitResetTodayOpenSource: "開啟狀態頁",
        .rateLimitResetTodayOpenWebsite: "前往 CodexRunway 網頁查看重置資訊與歷史紀錄",
        .rateLimitResetTodayOpenEvidence: "開啟 X 來源",
        .rateLimitResetTodayResetAgo: "已重置%@",
        .rateLimitResetTodayUntilReset: "距離重置還有%@",
        .rateLimitResetTodayPlanAll: "全部套餐",
        .rateLimitResetTodayPlanBusiness: "Business",
        .rateLimitResetTodayPlanEnterprise: "Enterprise",
        .rateLimitResetTodayPlanFree: "Free",
        .rateLimitResetTodayPlanPlus: "Plus",
        .rateLimitResetTodayPlanPro: "Pro",
        .rateLimitResetTodayPlanTeam: "Team",
        .rateLimitResetTodayPlanUnknown: "套餐未指明",
        .rateLimitResetTodayPlans: "套餐",
        .rateLimitResetTodayRefreshInterval: "重置狀態重新整理",
        .rateLimitResetTodayReactionPlease: "求重置",
        .rateLimitResetTodayReactionThank: "感謝",
        .rateLimitResetTodayReactionPleaseAria: "求重置，目前 %@",
        .rateLimitResetTodayReactionThankAria: "感謝重置，目前 %@",
        .rateLimitResetTodayReactionLimitReached: "今日次數已用完",
        .rateLimitResetTodaySeen: "見于",
        .rateLimitResetTodaySource: "CodexRunway 重置狀態",
        .rateLimitResetTodaySourceInfo: "該狀態由 CodexRunway 托管的監控任務生成，並使用 AI 分析公開的 X 公告。AI 結果可能不完整或有誤。",
        .rateLimitResetTodaySourceTitle: "資料來源",
        .rateLimitResetTodayGlobalAndBankedCompletedHint: "全域配額已重置；另有一次重置存入重置銀行",
        .rateLimitResetTodayGlobalAndBankedScheduledHint: "今日稍後有全域重置及重置銀行到帳排期，目前均尚未發生",
        .rateLimitResetTypeBanked: "重置銀行",
        .rateLimitResetTypeGlobal: "全域重置",
        .rateLimitResetTypeGlobalAndBanked: "全域重置 + 重置銀行",
        .rateLimitResetTodayUnknown: "—",
        .rateLimitResetTodayUnknownHint: "狀態不可用或已過期",
        .rateLimitResetTodayVerdict: "判定",
        .rateLimitResetTodayWindowFiveHour: "5 小時視窗",
        .rateLimitResetTodayWindowUnknown: "視窗未指明",
        .rateLimitResetTodayWindowWeekly: "週額度",
        .rateLimitResetTodayWindows: "額度視窗",
        .rateLimitResetTodayYes: "是",
        .rateLimitResetTodayYesHint: "今日額度已重置",
        .rateLimitResetTodayYesHintWithTime: "今日已重置 · %@",
        .rateLimitResetTodayYesHintScheduled: "今日稍後有全域重置排期，目前尚未完成",
        .rateLimitResetTodayYesHintScheduledWithTime: "今日已排期、尚未完成 · %@",
        .rateLimitResetTodayPercentPrefix: "≥%@%%",
        .rateLimitResetTodayPercentExact: "%@%%",
        .rateLimitResetTodayClockLocal: "本地時間",
        .rateLimitResetTodayConfirmedWhen: "%@（%@前）",
        .rateLimitResetTodayConfirmedHint: "監測到今天已有完成的{type}，置信度約為{percent}，重置的{zone}為{when}",
        .rateLimitResetTodayConfirmedHintNoPercent: "監測到今天已有完成的{type}，重置的{zone}為{when}",
        .rateLimitResetTodayScheduledChanceHint:
            "約{percent}的可能性會進行{type}，目前計畫已排期，重置時間範圍大約在{zone}：{date}",
        .rateLimitResetUpcomingAlertBody1h: "計劃中的 Codex 重置將在 1 小時內到來。",
        .rateLimitResetUpcomingAlertBody30m: "計劃中的 Codex 重置將在 30 分鐘內到來。",
        .rateLimitResetUpcomingRangeAlertBody: "預計重置時間範圍：%@。",
        .rateLimitResetUpcomingRangeAlertTitle: "預計 Codex 重置時間範圍",
        .rateLimitResetUpcomingAlertTitle: "即將重置",
        .rateLimitResetUpcomingTypedAlertTitle: "Codex %@即將到來",
        .rateLimitResetUpcomingTypedRangeAlertTitle: "預計 Codex %@時間範圍",
        .recent: "最近活躍",
        .recentSessionsDescription: "開啟後才掃描本機最近工作階段。",
        .refresh: "重新整理",
        .refreshInterval: "重新整理間隔",
        .rebuilt: "已重建",
        .repair: "修復",
        .repairConfirmMessage: "CodexRunway 將从本機工作階段檔案重建 ~/.codex/session_index.jsonl。寫入前會在同目錄創建帶時間戳的備份。不會修改工作階段日誌、auth.json 或全局狀態。",
        .repairConfirmTitle: "修復 Codex 工作階段索引？",
        .repairFailed: "修復失敗",
        .repairIndex: "修復索引",
        .resetsIn: "重置于",
        .resetCredits: "重置次數",
        .resetCreditAlertBody: "有重置次數即將過期。",
        .resetCreditAlertTitle: "重置次數即將過期",
        .resetCreditAlertsDescription: "可用重置次數將在 7 天內過期時提醒。",
        .resetCreditAlerts: "重置次數提醒",
        .resetCreditDetails: "重置次數詳細資料",
        .restoreDefaultOrder: "恢復預設順序",
        .runway: "Runway",
        .seconds: "秒",
        .sessionRepair: "工作階段修復",
        .sessionScanFailed: "工作階段掃描失敗",
        .recentSessions: "最近工作階段",
        .settings: "設定",
        .selfCheck: "自檢",
        .showDetails: "顯示詳細資料",
        .showCostSummary: "顯示 API 成本摘要",
        .showModelSpecificQuotaUsage: "特有模型額度用量展示",
        .showRateLimitResetToday: "顯示今日是否重置",
        .showRecentSessions: "顯示最近工作階段",
        .showSessionRepairSummary: "顯示工作階段修復摘要",
        .showTokenUsageHeatmap: "顯示 Token 用量",
        .mainPanelModules: "主面板模組",
        .mainPanelModulesDescription: "選擇需要顯示的模組並調整排列順序；隱藏模組仍會保留目前位置。",
        .moduleAPICostDescription: "按本機工作階段估算 API 等价成本。",
        .moduleAppliesCodex: "Codex",
        .moduleAppliesBoth: "Codex 与 Grok",
        .moduleHidden: "已隱藏",
        .moduleQuotaDescription: "額度進度与特有模型限額。",
        .moduleQuotaEstimateDescription: "根據歷史用量推算本週額度，便於發現官方是否下調。",
        .moduleResetCreditsDescription: "可用重置次數及到期資訊。",
        .moduleSessionRepairDescription: "本機工作階段索引狀態与修復工具。",
        .moduleVisible: "顯示",
        .notificationSettings: "通知提醒",
        .tokenUsageHeatmap: "Token 用量",
        .tokenUsageHeatmapDescription: "本年至今的 token 用量圖表（熱力圖、折線圖或長條圖）。",
        .tokenUsageHeatmapUnavailable: "Token 用量暫時不可用",
        .tokenUsageChartStyle: "圖表類型",
        .tokenUsageChartHeatmap: "熱力圖",
        .tokenUsageChartLine: "折線圖",
        .tokenUsageChartBar: "長條圖",
        .heatmapDaily: "每日",
        .heatmapWeekly: "每週",
        .heatmapCumulative: "累計",
        .heatmapMonthly: "每月",
        .heatmapEmpty: "本年暫無 token 用量",
        .heatmapAllDevices: "官方統計（多端）",
        .heatmapLocalDevice: "本機日志（全部本機工作階段）",
        .heatmapLocalShort: "本機",
        .heatmapOfficialAsOf: "官方截至 %@",
        .heatmapSourceDisclosure: "官方統計可能延遲或調整；本機日志包含這台 Mac 可見的全部工作階段，可能跨帳號。每日數據使用 UTC 日期。",
        .heatmapSourceMismatch: "資料來源口徑不同，不能作為包含關系比較",
        .sourceLocalSessions: "本機工作階段",
        .sourceOnlineSupplement: "線上補全",
        .staleTitles: "過期標題",
        .status: "狀態",
        .subscriptionExpired: "已到期",
        .subscriptionExpires: "訂閱有效期至",
        .subscriptionExpiringSoon: "訂閱即將到期",
        .statusAvailable: "可用",
        .statusError: "錯",
        .statusLogin: "登入",
        .statusBarBattery: "電池倒計時",
        .statusBarBatteryDetailCountdown: "重新整理倒計時",
        .statusBarBatteryDetailRemainingPercent: "剩餘百分比",
        .statusBarBatteryDetailStyle: "電池中心顯示",
        .statusBarBatteryScope: "電池額度",
        .statusBarBatteryScopeBoth: "全部可見額度",
        .statusBarBatteryScopeFiveHour: "5小時",
        .statusBarBatteryScopeWeekly: "每週",
        .statusBarCountdown: "倒計時",
        .statusBarMetersDetailResetTime: "重置時間",
        .statusBarMetersDetailRemainingPercent: "剩餘百分比",
        .statusBarMetersDetailBoth: "两者都顯示",
        .statusBarMetersDetailStyle: "額度條右側顯示",
        .statusBarMeters: "額度條",
        .statusBarProviderScope: "狀態欄平台",
        .statusBarProviderScopeBoth: "Codex + Grok",
        .statusBarProviderScopeSelected: "跟隨目前面板",
        .statusBarRings: "圓環進度",
        .statusBarStyle: "狀態欄樣式",
        .statusBarText: "進度文本",
        .statusUsed: "已使用",
        .statusWait: "等",
        .statusUnknown: "未知",
        .startDate: "開始日期",
        .updateAvailable: "發現新版本",
        .updateCheckFailed: "更新檢查失敗",
        .updateChecking: "正在檢查更新...",
        .updateDownloadAndInstall: "下載並安裝",
        .updateDownloadedReady: "CodexRunway %@ 已下載，可以安裝。",
        .updateDownloading: "正在下載更新...",
        .updateExtracting: "正在解壓更新...",
        .updateInstallAndRelaunch: "安裝並重新啟動",
        .updateInstallLater: "稍後",
        .updateInstalled: "更新已安裝",
        .updateInstalledMessage: "CodexRunway 已完成更新。",
        .updateInstalling: "正在安裝更新...",
        .updateLearnMore: "了解更多",
        .updateNetworkProxyHint: "如果你使用系統代理，請確認 github.com 和 release-assets.githubusercontent.com 不在系統代理繞過列表中，或使用 TUN 模式。",
        .updateReadyToInstall: "準備安裝",
        .updateSigningKeyMissing: "Sparkle 簽名公鑰未組態。",
        .updateSkipVersion: "跳過此版本",
        .updateUnavailableInDevelopment: "使用 swift run 運行時無法安裝更新。請使用打包後的 .app 或 Release 版本測試 Sparkle 更新。",
        .updateVersionAvailable: "CodexRunway %@ 可用。",
        .upToDate: "CodexRunway 已是最新版本。",
        .total: "總數",
        .totalRemaining: "總剩餘",
        .tokens: "Tokens",
        .tokensOnly: "仅 tokens",
        .testNotification: "測試提醒",
        .testNotificationBody: "CodexRunway 的通知可以正常顯示。",
        .testNotificationDevelopmentMode: "系統通知需要運行打包後的 CodexRunway.app，無法在 swift run 中測試。",
        .testNotificationSubtitle: "請求 macOS 通知權限並發送一條測試提醒。",
        .testNotificationTitle: "CodexRunway 測試提醒",
        .threads: "執行緒",
        .today: "今日",
        .thisMonth: "本月",
        .turns: "輪",
        .unknown: "未知",
        .unknownAccount: "未知帳號",
        .unknownModels: "未知模型",
        .unavailableCredits: "不可用次數",
        .usageAnalyticsUnavailable: "用量分析不可用",
        .usageAnalyticsEmpty: "該時間段暫無用量",
        .used: "已用",
        .usdPerCredit: "每 Credit 美元",
        .version: "版本",
        .weeklyValueEstimate: "週總額估算",
        .weeklyUsage: "每週",
        .widgetAllDevices: "所有裝置",
        .widgetBalance: "餘額",
        .widgetCost: "API 等价成本",
        .widgetDataCorrupt: "小工具資料已損壞，請重新整理 CodexRunway。",
        .widgetDataOld: "資料已過期",
        .widgetMetricTitle: "關鍵指標",
        .widgetNoData: "開啟 CodexRunway 以載入小工具資料。",
        .widgetOverviewTitle: "額度總覽",
        .widgetRefreshInterval: "桌面小工具重新整理間隔",
        .widgetRefreshIntervalDescription: "CodexRunway 主程式運行時按此間隔請求更新；實際顯示時機由 macOS 決定。",
        .widgetRemaining: "剩餘額度",
        .widgetResetCredits: "重置次數",
        .widgetResetTodayTitle: "今日重置",
        .widgetThisMac: "本機",
        .widgetTokenTrendTitle: "Token 趨勢",
        .widgetUpdated: "更新于",
        .widgetVersionUnsupported: "請更新 CodexRunway 以讀取小工具資料。",
        .languageTraditionalChinese: "繁體中文",
        .languageKorean: "韓語",
        .languageJapanese: "日語",
        .languageRussian: "俄語",
        .languageFrench: "法語",
    ]
}
